// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2
// Source: course.proto

package server

import (
	"context"

	"teaching-backend/application/course/rpc/internal/logic"
	"teaching-backend/application/course/rpc/internal/svc"
	"teaching-backend/application/course/rpc/pb"
)

type CourseServer struct {
	svcCtx *svc.ServiceContext
	pb.UnimplementedCourseServer
}

func NewCourseServer(svcCtx *svc.ServiceContext) *CourseServer {
	return &CourseServer{
		svcCtx: svcCtx,
	}
}

// 创建课程
func (s *CourseServer) CreateCourse(ctx context.Context, in *pb.CreateCourseReq) (*pb.CreateCourseRes, error) {
	l := logic.NewCreateCourseLogic(ctx, s.svcCtx)
	return l.CreateCourse(in)
}

// 课程列表
func (s *CourseServer) CourseList(ctx context.Context, in *pb.CourseListReq) (*pb.CourseListRes, error) {
	l := logic.NewCourseListLogic(ctx, s.svcCtx)
	return l.CourseList(in)
}

// 课程详情
func (s *CourseServer) CourseDetail(ctx context.Context, in *pb.CourseDetailReq) (*pb.CourseDetailRes, error) {
	l := logic.NewCourseDetailLogic(ctx, s.svcCtx)
	return l.CourseDetail(in)
}

// 更新课程
func (s *CourseServer) UpdateCourse(ctx context.Context, in *pb.UpdateCourseReq) (*pb.UpdateCourseRes, error) {
	l := logic.NewUpdateCourseLogic(ctx, s.svcCtx)
	return l.UpdateCourse(in)
}

// 删除课程
func (s *CourseServer) DeleteCourse(ctx context.Context, in *pb.DeleteCourseReq) (*pb.DeleteCourseRes, error) {
	l := logic.NewDeleteCourseLogic(ctx, s.svcCtx)
	return l.DeleteCourse(in)
}

// 创建章节
func (s *CourseServer) CreateChapter(ctx context.Context, in *pb.CreateChapterReq) (*pb.CreateChapterRes, error) {
	l := logic.NewCreateChapterLogic(ctx, s.svcCtx)
	return l.CreateChapter(in)
}

// 章节列表
func (s *CourseServer) ChapterList(ctx context.Context, in *pb.ChapterListReq) (*pb.ChapterListRes, error) {
	l := logic.NewChapterListLogic(ctx, s.svcCtx)
	return l.ChapterList(in)
}

// 更新章节
func (s *CourseServer) UpdateChapter(ctx context.Context, in *pb.UpdateChapterReq) (*pb.UpdateChapterRes, error) {
	l := logic.NewUpdateChapterLogic(ctx, s.svcCtx)
	return l.UpdateChapter(in)
}

// 删除章节
func (s *CourseServer) DeleteChapter(ctx context.Context, in *pb.DeleteChapterReq) (*pb.DeleteChapterRes, error) {
	l := logic.NewDeleteChapterLogic(ctx, s.svcCtx)
	return l.DeleteChapter(in)
}

// 上传课件
func (s *CourseServer) CreateMaterial(ctx context.Context, in *pb.CreateMaterialReq) (*pb.CreateMaterialRes, error) {
	l := logic.NewCreateMaterialLogic(ctx, s.svcCtx)
	return l.CreateMaterial(in)
}

// 课件列表
func (s *CourseServer) MaterialList(ctx context.Context, in *pb.MaterialListReq) (*pb.MaterialListRes, error) {
	l := logic.NewMaterialListLogic(ctx, s.svcCtx)
	return l.MaterialList(in)
}

// 删除课件
func (s *CourseServer) DeleteMaterial(ctx context.Context, in *pb.DeleteMaterialReq) (*pb.DeleteMaterialRes, error) {
	l := logic.NewDeleteMaterialLogic(ctx, s.svcCtx)
	return l.DeleteMaterial(in)
}

// 更新课件AI处理状态
func (s *CourseServer) UpdateMaterialAiStatus(ctx context.Context, in *pb.UpdateMaterialAiStatusReq) (*pb.UpdateMaterialAiStatusRes, error) {
	l := logic.NewUpdateMaterialAiStatusLogic(ctx, s.svcCtx)
	return l.UpdateMaterialAiStatus(in)
}

// 更新学习进度
func (s *CourseServer) UpdateStudyProgress(ctx context.Context, in *pb.UpdateStudyProgressReq) (*pb.UpdateStudyProgressRes, error) {
	l := logic.NewUpdateStudyProgressLogic(ctx, s.svcCtx)
	return l.UpdateStudyProgress(in)
}

// 获取学习进度
func (s *CourseServer) GetStudyProgress(ctx context.Context, in *pb.GetStudyProgressReq) (*pb.GetStudyProgressRes, error) {
	l := logic.NewGetStudyProgressLogic(ctx, s.svcCtx)
	return l.GetStudyProgress(in)
}

// 选课
func (s *CourseServer) EnrollCourse(ctx context.Context, in *pb.EnrollCourseReq) (*pb.EnrollCourseRes, error) {
	l := logic.NewEnrollCourseLogic(ctx, s.svcCtx)
	return l.EnrollCourse(in)
}

// 退课
func (s *CourseServer) DropCourse(ctx context.Context, in *pb.DropCourseReq) (*pb.DropCourseRes, error) {
	l := logic.NewDropCourseLogic(ctx, s.svcCtx)
	return l.DropCourse(in)
}

// 获取学生已选课程列表
func (s *CourseServer) GetEnrollmentList(ctx context.Context, in *pb.GetEnrollmentListReq) (*pb.GetEnrollmentListRes, error) {
	l := logic.NewGetEnrollmentListLogic(ctx, s.svcCtx)
	return l.GetEnrollmentList(in)
}

// 检查是否已选课
func (s *CourseServer) CheckEnrollment(ctx context.Context, in *pb.CheckEnrollmentReq) (*pb.CheckEnrollmentRes, error) {
	l := logic.NewCheckEnrollmentLogic(ctx, s.svcCtx)
	return l.CheckEnrollment(in)
}

// 获取课程已选学生列表（教师用）
func (s *CourseServer) GetCourseStudents(ctx context.Context, in *pb.GetCourseStudentsReq) (*pb.GetCourseStudentsRes, error) {
	l := logic.NewGetCourseStudentsLogic(ctx, s.svcCtx)
	return l.GetCourseStudents(in)
}
