// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.9.2

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	courseEnrollmentFieldNames          = builder.RawFieldNames(&CourseEnrollment{})
	courseEnrollmentRows                = strings.Join(courseEnrollmentFieldNames, ",")
	courseEnrollmentRowsExpectAutoSet   = strings.Join(stringx.Remove(courseEnrollmentFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	courseEnrollmentRowsWithPlaceHolder = strings.Join(stringx.Remove(courseEnrollmentFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"

	cacheTeachingCourseCourseEnrollmentIdPrefix             = "cache:teachingCourse:courseEnrollment:id:"
	cacheTeachingCourseCourseEnrollmentUserIdCourseIdPrefix = "cache:teachingCourse:courseEnrollment:userId:courseId:"
)

type (
	courseEnrollmentModel interface {
		Insert(ctx context.Context, data *CourseEnrollment) (sql.Result, error)
		FindOne(ctx context.Context, id uint64) (*CourseEnrollment, error)
		FindOneByUserIdCourseId(ctx context.Context, userId uint64, courseId uint64) (*CourseEnrollment, error)
		Update(ctx context.Context, data *CourseEnrollment) error
		Delete(ctx context.Context, id uint64) error
	}

	defaultCourseEnrollmentModel struct {
		sqlc.CachedConn
		table string
	}

	CourseEnrollment struct {
		Id         uint64    `db:"id"`          // 主键ID
		UserId     uint64    `db:"user_id"`     // 学生ID
		CourseId   uint64    `db:"course_id"`   // 课程ID
		Status     int64     `db:"status"`      // 状态 1:已选 2:已退
		CreateTime time.Time `db:"create_time"` // 选课时间
		UpdateTime time.Time `db:"update_time"` // 更新时间
	}
)

func newCourseEnrollmentModel(conn sqlx.SqlConn, c cache.CacheConf, opts ...cache.Option) *defaultCourseEnrollmentModel {
	return &defaultCourseEnrollmentModel{
		CachedConn: sqlc.NewConn(conn, c, opts...),
		table:      "`course_enrollment`",
	}
}

func (m *defaultCourseEnrollmentModel) Delete(ctx context.Context, id uint64) error {
	data, err := m.FindOne(ctx, id)
	if err != nil {
		return err
	}

	teachingCourseCourseEnrollmentIdKey := fmt.Sprintf("%s%v", cacheTeachingCourseCourseEnrollmentIdPrefix, id)
	teachingCourseCourseEnrollmentUserIdCourseIdKey := fmt.Sprintf("%s%v:%v", cacheTeachingCourseCourseEnrollmentUserIdCourseIdPrefix, data.UserId, data.CourseId)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
		return conn.ExecCtx(ctx, query, id)
	}, teachingCourseCourseEnrollmentIdKey, teachingCourseCourseEnrollmentUserIdCourseIdKey)
	return err
}

func (m *defaultCourseEnrollmentModel) FindOne(ctx context.Context, id uint64) (*CourseEnrollment, error) {
	teachingCourseCourseEnrollmentIdKey := fmt.Sprintf("%s%v", cacheTeachingCourseCourseEnrollmentIdPrefix, id)
	var resp CourseEnrollment
	err := m.QueryRowCtx(ctx, &resp, teachingCourseCourseEnrollmentIdKey, func(ctx context.Context, conn sqlx.SqlConn, v any) error {
		query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", courseEnrollmentRows, m.table)
		return conn.QueryRowCtx(ctx, v, query, id)
	})
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultCourseEnrollmentModel) FindOneByUserIdCourseId(ctx context.Context, userId uint64, courseId uint64) (*CourseEnrollment, error) {
	teachingCourseCourseEnrollmentUserIdCourseIdKey := fmt.Sprintf("%s%v:%v", cacheTeachingCourseCourseEnrollmentUserIdCourseIdPrefix, userId, courseId)
	var resp CourseEnrollment
	err := m.QueryRowIndexCtx(ctx, &resp, teachingCourseCourseEnrollmentUserIdCourseIdKey, m.formatPrimary, func(ctx context.Context, conn sqlx.SqlConn, v any) (i any, e error) {
		query := fmt.Sprintf("select %s from %s where `user_id` = ? and `course_id` = ? limit 1", courseEnrollmentRows, m.table)
		if err := conn.QueryRowCtx(ctx, &resp, query, userId, courseId); err != nil {
			return nil, err
		}
		return resp.Id, nil
	}, m.queryPrimary)
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultCourseEnrollmentModel) Insert(ctx context.Context, data *CourseEnrollment) (sql.Result, error) {
	teachingCourseCourseEnrollmentIdKey := fmt.Sprintf("%s%v", cacheTeachingCourseCourseEnrollmentIdPrefix, data.Id)
	teachingCourseCourseEnrollmentUserIdCourseIdKey := fmt.Sprintf("%s%v:%v", cacheTeachingCourseCourseEnrollmentUserIdCourseIdPrefix, data.UserId, data.CourseId)
	ret, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?)", m.table, courseEnrollmentRowsExpectAutoSet)
		return conn.ExecCtx(ctx, query, data.UserId, data.CourseId, data.Status)
	}, teachingCourseCourseEnrollmentIdKey, teachingCourseCourseEnrollmentUserIdCourseIdKey)
	return ret, err
}

func (m *defaultCourseEnrollmentModel) Update(ctx context.Context, newData *CourseEnrollment) error {
	data, err := m.FindOne(ctx, newData.Id)
	if err != nil {
		return err
	}

	teachingCourseCourseEnrollmentIdKey := fmt.Sprintf("%s%v", cacheTeachingCourseCourseEnrollmentIdPrefix, data.Id)
	teachingCourseCourseEnrollmentUserIdCourseIdKey := fmt.Sprintf("%s%v:%v", cacheTeachingCourseCourseEnrollmentUserIdCourseIdPrefix, data.UserId, data.CourseId)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, courseEnrollmentRowsWithPlaceHolder)
		return conn.ExecCtx(ctx, query, newData.UserId, newData.CourseId, newData.Status, newData.Id)
	}, teachingCourseCourseEnrollmentIdKey, teachingCourseCourseEnrollmentUserIdCourseIdKey)
	return err
}

func (m *defaultCourseEnrollmentModel) formatPrimary(primary any) string {
	return fmt.Sprintf("%s%v", cacheTeachingCourseCourseEnrollmentIdPrefix, primary)
}

func (m *defaultCourseEnrollmentModel) queryPrimary(ctx context.Context, conn sqlx.SqlConn, v, primary any) error {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", courseEnrollmentRows, m.table)
	return conn.QueryRowCtx(ctx, v, query, primary)
}

func (m *defaultCourseEnrollmentModel) tableName() string {
	return m.table
}
