// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.9.2

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	courseMaterialFieldNames          = builder.RawFieldNames(&CourseMaterial{})
	courseMaterialRows                = strings.Join(courseMaterialFieldNames, ",")
	courseMaterialRowsExpectAutoSet   = strings.Join(stringx.Remove(courseMaterialFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	courseMaterialRowsWithPlaceHolder = strings.Join(stringx.Remove(courseMaterialFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"

	cacheTeachingCourseCourseMaterialIdPrefix = "cache:teachingCourse:courseMaterial:id:"
)

type (
	courseMaterialModel interface {
		Insert(ctx context.Context, data *CourseMaterial) (sql.Result, error)
		FindOne(ctx context.Context, id uint64) (*CourseMaterial, error)
		Update(ctx context.Context, data *CourseMaterial) error
		Delete(ctx context.Context, id uint64) error
	}

	defaultCourseMaterialModel struct {
		sqlc.CachedConn
		table string
	}

	CourseMaterial struct {
		Id         uint64       `db:"id"`          // 主键ID
		ChapterId  uint64       `db:"chapter_id"`  // 章节ID
		Title      string       `db:"title"`       // 课件标题
		Type       int64        `db:"type"`        // 资料类型 2:PDF 3:文档
		Url        string       `db:"url"`         // OSS存储链接
		FileHash   string       `db:"file_hash"`   // 文件Hash(MD5等)
		FileSize   int64        `db:"file_size"`   // 文件大小(字节)
		AiStatus   int64        `db:"ai_status"`   // 向量化状态 0:未处理 1:处理中 2:已完成 3:失败
		Sort       int64        `db:"sort"`        // 排序
		CreateTime time.Time    `db:"create_time"` // 创建时间
		UpdateTime time.Time    `db:"update_time"` // 更新时间
		DeletedAt  sql.NullTime `db:"deleted_at"`  // 删除时间
	}
)

func newCourseMaterialModel(conn sqlx.SqlConn, c cache.CacheConf, opts ...cache.Option) *defaultCourseMaterialModel {
	return &defaultCourseMaterialModel{
		CachedConn: sqlc.NewConn(conn, c, opts...),
		table:      "`course_material`",
	}
}

func (m *defaultCourseMaterialModel) Delete(ctx context.Context, id uint64) error {
	teachingCourseCourseMaterialIdKey := fmt.Sprintf("%s%v", cacheTeachingCourseCourseMaterialIdPrefix, id)
	_, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
		return conn.ExecCtx(ctx, query, id)
	}, teachingCourseCourseMaterialIdKey)
	return err
}

func (m *defaultCourseMaterialModel) FindOne(ctx context.Context, id uint64) (*CourseMaterial, error) {
	teachingCourseCourseMaterialIdKey := fmt.Sprintf("%s%v", cacheTeachingCourseCourseMaterialIdPrefix, id)
	var resp CourseMaterial
	err := m.QueryRowCtx(ctx, &resp, teachingCourseCourseMaterialIdKey, func(ctx context.Context, conn sqlx.SqlConn, v any) error {
		query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", courseMaterialRows, m.table)
		return conn.QueryRowCtx(ctx, v, query, id)
	})
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultCourseMaterialModel) Insert(ctx context.Context, data *CourseMaterial) (sql.Result, error) {
	teachingCourseCourseMaterialIdKey := fmt.Sprintf("%s%v", cacheTeachingCourseCourseMaterialIdPrefix, data.Id)
	ret, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?, ?, ?, ?)", m.table, courseMaterialRowsExpectAutoSet)
		return conn.ExecCtx(ctx, query, data.ChapterId, data.Title, data.Type, data.Url, data.FileHash, data.FileSize, data.AiStatus, data.Sort, data.DeletedAt)
	}, teachingCourseCourseMaterialIdKey)
	return ret, err
}

func (m *defaultCourseMaterialModel) Update(ctx context.Context, data *CourseMaterial) error {
	teachingCourseCourseMaterialIdKey := fmt.Sprintf("%s%v", cacheTeachingCourseCourseMaterialIdPrefix, data.Id)
	_, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, courseMaterialRowsWithPlaceHolder)
		return conn.ExecCtx(ctx, query, data.ChapterId, data.Title, data.Type, data.Url, data.FileHash, data.FileSize, data.AiStatus, data.Sort, data.DeletedAt, data.Id)
	}, teachingCourseCourseMaterialIdKey)
	return err
}

func (m *defaultCourseMaterialModel) formatPrimary(primary any) string {
	return fmt.Sprintf("%s%v", cacheTeachingCourseCourseMaterialIdPrefix, primary)
}

func (m *defaultCourseMaterialModel) queryPrimary(ctx context.Context, conn sqlx.SqlConn, v, primary any) error {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", courseMaterialRows, m.table)
	return conn.QueryRowCtx(ctx, v, query, primary)
}

func (m *defaultCourseMaterialModel) tableName() string {
	return m.table
}
