// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.9.2

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	courseFieldNames          = builder.RawFieldNames(&Course{})
	courseRows                = strings.Join(courseFieldNames, ",")
	courseRowsExpectAutoSet   = strings.Join(stringx.Remove(courseFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	courseRowsWithPlaceHolder = strings.Join(stringx.Remove(courseFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"

	cacheTeachingCourseCourseIdPrefix = "cache:teachingCourse:course:id:"
)

type (
	courseModel interface {
		Insert(ctx context.Context, data *Course) (sql.Result, error)
		FindOne(ctx context.Context, id uint64) (*Course, error)
		Update(ctx context.Context, data *Course) error
		Delete(ctx context.Context, id uint64) error
	}

	defaultCourseModel struct {
		sqlc.CachedConn
		table string
	}

	Course struct {
		Id          uint64         `db:"id"`          // 主键ID
		Title       string         `db:"title"`       // 课程名称
		Cover       string         `db:"cover"`       // 课程封面URL
		Description sql.NullString `db:"description"` // 课程描述
		TeacherId   uint64         `db:"teacher_id"`  // 教师ID
		Status      int64          `db:"status"`      // 状态 0:未发布 1:已发布
		CreateTime  time.Time      `db:"create_time"` // 创建时间
		UpdateTime  time.Time      `db:"update_time"` // 更新时间
		DeletedAt   sql.NullTime   `db:"deleted_at"`  // 删除时间
	}
)

func newCourseModel(conn sqlx.SqlConn, c cache.CacheConf, opts ...cache.Option) *defaultCourseModel {
	return &defaultCourseModel{
		CachedConn: sqlc.NewConn(conn, c, opts...),
		table:      "`course`",
	}
}

func (m *defaultCourseModel) Delete(ctx context.Context, id uint64) error {
	teachingCourseCourseIdKey := fmt.Sprintf("%s%v", cacheTeachingCourseCourseIdPrefix, id)
	_, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
		return conn.ExecCtx(ctx, query, id)
	}, teachingCourseCourseIdKey)
	return err
}

func (m *defaultCourseModel) FindOne(ctx context.Context, id uint64) (*Course, error) {
	teachingCourseCourseIdKey := fmt.Sprintf("%s%v", cacheTeachingCourseCourseIdPrefix, id)
	var resp Course
	err := m.QueryRowCtx(ctx, &resp, teachingCourseCourseIdKey, func(ctx context.Context, conn sqlx.SqlConn, v any) error {
		query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", courseRows, m.table)
		return conn.QueryRowCtx(ctx, v, query, id)
	})
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultCourseModel) Insert(ctx context.Context, data *Course) (sql.Result, error) {
	teachingCourseCourseIdKey := fmt.Sprintf("%s%v", cacheTeachingCourseCourseIdPrefix, data.Id)
	ret, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?)", m.table, courseRowsExpectAutoSet)
		return conn.ExecCtx(ctx, query, data.Title, data.Cover, data.Description, data.TeacherId, data.Status, data.DeletedAt)
	}, teachingCourseCourseIdKey)
	return ret, err
}

func (m *defaultCourseModel) Update(ctx context.Context, data *Course) error {
	teachingCourseCourseIdKey := fmt.Sprintf("%s%v", cacheTeachingCourseCourseIdPrefix, data.Id)
	_, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, courseRowsWithPlaceHolder)
		return conn.ExecCtx(ctx, query, data.Title, data.Cover, data.Description, data.TeacherId, data.Status, data.DeletedAt, data.Id)
	}, teachingCourseCourseIdKey)
	return err
}

func (m *defaultCourseModel) formatPrimary(primary any) string {
	return fmt.Sprintf("%s%v", cacheTeachingCourseCourseIdPrefix, primary)
}

func (m *defaultCourseModel) queryPrimary(ctx context.Context, conn sqlx.SqlConn, v, primary any) error {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", courseRows, m.table)
	return conn.QueryRowCtx(ctx, v, query, primary)
}

func (m *defaultCourseModel) tableName() string {
	return m.table
}
