// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.9.2

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	courseChapterFieldNames          = builder.RawFieldNames(&CourseChapter{})
	courseChapterRows                = strings.Join(courseChapterFieldNames, ",")
	courseChapterRowsExpectAutoSet   = strings.Join(stringx.Remove(courseChapterFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	courseChapterRowsWithPlaceHolder = strings.Join(stringx.Remove(courseChapterFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"

	cacheTeachingCourseCourseChapterIdPrefix = "cache:teachingCourse:courseChapter:id:"
)

type (
	courseChapterModel interface {
		Insert(ctx context.Context, data *CourseChapter) (sql.Result, error)
		FindOne(ctx context.Context, id uint64) (*CourseChapter, error)
		Update(ctx context.Context, data *CourseChapter) error
		Delete(ctx context.Context, id uint64) error
	}

	defaultCourseChapterModel struct {
		sqlc.CachedConn
		table string
	}

	CourseChapter struct {
		Id         uint64    `db:"id"`          // 主键ID
		CourseId   uint64    `db:"course_id"`   // 课程ID
		Title      string    `db:"title"`       // 章节标题
		Sort       int64     `db:"sort"`        // 排序
		CreateTime time.Time `db:"create_time"` // 创建时间
		UpdateTime time.Time `db:"update_time"` // 更新时间
	}
)

func newCourseChapterModel(conn sqlx.SqlConn, c cache.CacheConf, opts ...cache.Option) *defaultCourseChapterModel {
	return &defaultCourseChapterModel{
		CachedConn: sqlc.NewConn(conn, c, opts...),
		table:      "`course_chapter`",
	}
}

func (m *defaultCourseChapterModel) Delete(ctx context.Context, id uint64) error {
	teachingCourseCourseChapterIdKey := fmt.Sprintf("%s%v", cacheTeachingCourseCourseChapterIdPrefix, id)
	_, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
		return conn.ExecCtx(ctx, query, id)
	}, teachingCourseCourseChapterIdKey)
	return err
}

func (m *defaultCourseChapterModel) FindOne(ctx context.Context, id uint64) (*CourseChapter, error) {
	teachingCourseCourseChapterIdKey := fmt.Sprintf("%s%v", cacheTeachingCourseCourseChapterIdPrefix, id)
	var resp CourseChapter
	err := m.QueryRowCtx(ctx, &resp, teachingCourseCourseChapterIdKey, func(ctx context.Context, conn sqlx.SqlConn, v any) error {
		query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", courseChapterRows, m.table)
		return conn.QueryRowCtx(ctx, v, query, id)
	})
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultCourseChapterModel) Insert(ctx context.Context, data *CourseChapter) (sql.Result, error) {
	teachingCourseCourseChapterIdKey := fmt.Sprintf("%s%v", cacheTeachingCourseCourseChapterIdPrefix, data.Id)
	ret, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?)", m.table, courseChapterRowsExpectAutoSet)
		return conn.ExecCtx(ctx, query, data.CourseId, data.Title, data.Sort)
	}, teachingCourseCourseChapterIdKey)
	return ret, err
}

func (m *defaultCourseChapterModel) Update(ctx context.Context, data *CourseChapter) error {
	teachingCourseCourseChapterIdKey := fmt.Sprintf("%s%v", cacheTeachingCourseCourseChapterIdPrefix, data.Id)
	_, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, courseChapterRowsWithPlaceHolder)
		return conn.ExecCtx(ctx, query, data.CourseId, data.Title, data.Sort, data.Id)
	}, teachingCourseCourseChapterIdKey)
	return err
}

func (m *defaultCourseChapterModel) formatPrimary(primary any) string {
	return fmt.Sprintf("%s%v", cacheTeachingCourseCourseChapterIdPrefix, primary)
}

func (m *defaultCourseChapterModel) queryPrimary(ctx context.Context, conn sqlx.SqlConn, v, primary any) error {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", courseChapterRows, m.table)
	return conn.QueryRowCtx(ctx, v, query, primary)
}

func (m *defaultCourseChapterModel) tableName() string {
	return m.table
}
