// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.9.2

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	studyProgressFieldNames          = builder.RawFieldNames(&StudyProgress{})
	studyProgressRows                = strings.Join(studyProgressFieldNames, ",")
	studyProgressRowsExpectAutoSet   = strings.Join(stringx.Remove(studyProgressFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	studyProgressRowsWithPlaceHolder = strings.Join(stringx.Remove(studyProgressFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"

	cacheTeachingCourseStudyProgressIdPrefix               = "cache:teachingCourse:studyProgress:id:"
	cacheTeachingCourseStudyProgressUserIdMaterialIdPrefix = "cache:teachingCourse:studyProgress:userId:materialId:"
)

type (
	studyProgressModel interface {
		Insert(ctx context.Context, data *StudyProgress) (sql.Result, error)
		FindOne(ctx context.Context, id uint64) (*StudyProgress, error)
		FindOneByUserIdMaterialId(ctx context.Context, userId uint64, materialId uint64) (*StudyProgress, error)
		Update(ctx context.Context, data *StudyProgress) error
		Delete(ctx context.Context, id uint64) error
	}

	defaultStudyProgressModel struct {
		sqlc.CachedConn
		table string
	}

	StudyProgress struct {
		Id         uint64       `db:"id"`          // 主键ID
		UserId     uint64       `db:"user_id"`     // 学生ID
		CourseId   uint64       `db:"course_id"`   // 课程ID
		ChapterId  uint64       `db:"chapter_id"`  // 章节ID
		MaterialId uint64       `db:"material_id"` // 课件ID
		Progress   int64        `db:"progress"`    // 进度百分比 0~100
		CreateTime time.Time    `db:"create_time"` // 创建时间
		UpdateTime time.Time    `db:"update_time"` // 更新时间
		DeletedAt  sql.NullTime `db:"deleted_at"`  // 删除时间
	}
)

func newStudyProgressModel(conn sqlx.SqlConn, c cache.CacheConf, opts ...cache.Option) *defaultStudyProgressModel {
	return &defaultStudyProgressModel{
		CachedConn: sqlc.NewConn(conn, c, opts...),
		table:      "`study_progress`",
	}
}

func (m *defaultStudyProgressModel) Delete(ctx context.Context, id uint64) error {
	data, err := m.FindOne(ctx, id)
	if err != nil {
		return err
	}

	teachingCourseStudyProgressIdKey := fmt.Sprintf("%s%v", cacheTeachingCourseStudyProgressIdPrefix, id)
	teachingCourseStudyProgressUserIdMaterialIdKey := fmt.Sprintf("%s%v:%v", cacheTeachingCourseStudyProgressUserIdMaterialIdPrefix, data.UserId, data.MaterialId)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
		return conn.ExecCtx(ctx, query, id)
	}, teachingCourseStudyProgressIdKey, teachingCourseStudyProgressUserIdMaterialIdKey)
	return err
}

func (m *defaultStudyProgressModel) FindOne(ctx context.Context, id uint64) (*StudyProgress, error) {
	teachingCourseStudyProgressIdKey := fmt.Sprintf("%s%v", cacheTeachingCourseStudyProgressIdPrefix, id)
	var resp StudyProgress
	err := m.QueryRowCtx(ctx, &resp, teachingCourseStudyProgressIdKey, func(ctx context.Context, conn sqlx.SqlConn, v any) error {
		query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", studyProgressRows, m.table)
		return conn.QueryRowCtx(ctx, v, query, id)
	})
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultStudyProgressModel) FindOneByUserIdMaterialId(ctx context.Context, userId uint64, materialId uint64) (*StudyProgress, error) {
	teachingCourseStudyProgressUserIdMaterialIdKey := fmt.Sprintf("%s%v:%v", cacheTeachingCourseStudyProgressUserIdMaterialIdPrefix, userId, materialId)
	var resp StudyProgress
	err := m.QueryRowIndexCtx(ctx, &resp, teachingCourseStudyProgressUserIdMaterialIdKey, m.formatPrimary, func(ctx context.Context, conn sqlx.SqlConn, v any) (i any, e error) {
		query := fmt.Sprintf("select %s from %s where `user_id` = ? and `material_id` = ? limit 1", studyProgressRows, m.table)
		if err := conn.QueryRowCtx(ctx, &resp, query, userId, materialId); err != nil {
			return nil, err
		}
		return resp.Id, nil
	}, m.queryPrimary)
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultStudyProgressModel) Insert(ctx context.Context, data *StudyProgress) (sql.Result, error) {
	teachingCourseStudyProgressIdKey := fmt.Sprintf("%s%v", cacheTeachingCourseStudyProgressIdPrefix, data.Id)
	teachingCourseStudyProgressUserIdMaterialIdKey := fmt.Sprintf("%s%v:%v", cacheTeachingCourseStudyProgressUserIdMaterialIdPrefix, data.UserId, data.MaterialId)
	ret, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?)", m.table, studyProgressRowsExpectAutoSet)
		return conn.ExecCtx(ctx, query, data.UserId, data.CourseId, data.ChapterId, data.MaterialId, data.Progress, data.DeletedAt)
	}, teachingCourseStudyProgressIdKey, teachingCourseStudyProgressUserIdMaterialIdKey)
	return ret, err
}

func (m *defaultStudyProgressModel) Update(ctx context.Context, newData *StudyProgress) error {
	data, err := m.FindOne(ctx, newData.Id)
	if err != nil {
		return err
	}

	teachingCourseStudyProgressIdKey := fmt.Sprintf("%s%v", cacheTeachingCourseStudyProgressIdPrefix, data.Id)
	teachingCourseStudyProgressUserIdMaterialIdKey := fmt.Sprintf("%s%v:%v", cacheTeachingCourseStudyProgressUserIdMaterialIdPrefix, data.UserId, data.MaterialId)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, studyProgressRowsWithPlaceHolder)
		return conn.ExecCtx(ctx, query, newData.UserId, newData.CourseId, newData.ChapterId, newData.MaterialId, newData.Progress, newData.DeletedAt, newData.Id)
	}, teachingCourseStudyProgressIdKey, teachingCourseStudyProgressUserIdMaterialIdKey)
	return err
}

func (m *defaultStudyProgressModel) formatPrimary(primary any) string {
	return fmt.Sprintf("%s%v", cacheTeachingCourseStudyProgressIdPrefix, primary)
}

func (m *defaultStudyProgressModel) queryPrimary(ctx context.Context, conn sqlx.SqlConn, v, primary any) error {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", studyProgressRows, m.table)
	return conn.QueryRowCtx(ctx, v, query, primary)
}

func (m *defaultStudyProgressModel) tableName() string {
	return m.table
}
