// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.9.2

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	examQuestionFieldNames          = builder.RawFieldNames(&ExamQuestion{})
	examQuestionRows                = strings.Join(examQuestionFieldNames, ",")
	examQuestionRowsExpectAutoSet   = strings.Join(stringx.Remove(examQuestionFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	examQuestionRowsWithPlaceHolder = strings.Join(stringx.Remove(examQuestionFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"

	cacheExamQuestionIdPrefix               = "cache:examQuestion:id:"
	cacheExamQuestionExamIdQuestionIdPrefix = "cache:examQuestion:examId:questionId:"
)

type (
	examQuestionModel interface {
		Insert(ctx context.Context, data *ExamQuestion) (sql.Result, error)
		FindOne(ctx context.Context, id uint64) (*ExamQuestion, error)
		FindOneByExamIdQuestionId(ctx context.Context, examId uint64, questionId uint64) (*ExamQuestion, error)
		Update(ctx context.Context, data *ExamQuestion) error
		Delete(ctx context.Context, id uint64) error
	}

	defaultExamQuestionModel struct {
		sqlc.CachedConn
		table string
	}

	ExamQuestion struct {
		Id         uint64  `db:"id"`          // 主键ID
		ExamId     uint64  `db:"exam_id"`     // 试卷ID
		QuestionId uint64  `db:"question_id"` // 题目ID
		Score      float64 `db:"score"`       // 本试卷中该题分值
		Sort       int64   `db:"sort"`        // 题号排序
	}
)

func newExamQuestionModel(conn sqlx.SqlConn, c cache.CacheConf, opts ...cache.Option) *defaultExamQuestionModel {
	return &defaultExamQuestionModel{
		CachedConn: sqlc.NewConn(conn, c, opts...),
		table:      "`exam_question`",
	}
}

func (m *defaultExamQuestionModel) Delete(ctx context.Context, id uint64) error {
	data, err := m.FindOne(ctx, id)
	if err != nil {
		return err
	}

	examQuestionExamIdQuestionIdKey := fmt.Sprintf("%s%v:%v", cacheExamQuestionExamIdQuestionIdPrefix, data.ExamId, data.QuestionId)
	examQuestionIdKey := fmt.Sprintf("%s%v", cacheExamQuestionIdPrefix, id)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
		return conn.ExecCtx(ctx, query, id)
	}, examQuestionExamIdQuestionIdKey, examQuestionIdKey)
	return err
}

func (m *defaultExamQuestionModel) FindOne(ctx context.Context, id uint64) (*ExamQuestion, error) {
	examQuestionIdKey := fmt.Sprintf("%s%v", cacheExamQuestionIdPrefix, id)
	var resp ExamQuestion
	err := m.QueryRowCtx(ctx, &resp, examQuestionIdKey, func(ctx context.Context, conn sqlx.SqlConn, v any) error {
		query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", examQuestionRows, m.table)
		return conn.QueryRowCtx(ctx, v, query, id)
	})
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultExamQuestionModel) FindOneByExamIdQuestionId(ctx context.Context, examId uint64, questionId uint64) (*ExamQuestion, error) {
	examQuestionExamIdQuestionIdKey := fmt.Sprintf("%s%v:%v", cacheExamQuestionExamIdQuestionIdPrefix, examId, questionId)
	var resp ExamQuestion
	err := m.QueryRowIndexCtx(ctx, &resp, examQuestionExamIdQuestionIdKey, m.formatPrimary, func(ctx context.Context, conn sqlx.SqlConn, v any) (i any, e error) {
		query := fmt.Sprintf("select %s from %s where `exam_id` = ? and `question_id` = ? limit 1", examQuestionRows, m.table)
		if err := conn.QueryRowCtx(ctx, &resp, query, examId, questionId); err != nil {
			return nil, err
		}
		return resp.Id, nil
	}, m.queryPrimary)
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultExamQuestionModel) Insert(ctx context.Context, data *ExamQuestion) (sql.Result, error) {
	examQuestionExamIdQuestionIdKey := fmt.Sprintf("%s%v:%v", cacheExamQuestionExamIdQuestionIdPrefix, data.ExamId, data.QuestionId)
	examQuestionIdKey := fmt.Sprintf("%s%v", cacheExamQuestionIdPrefix, data.Id)
	ret, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?)", m.table, examQuestionRowsExpectAutoSet)
		return conn.ExecCtx(ctx, query, data.ExamId, data.QuestionId, data.Score, data.Sort)
	}, examQuestionExamIdQuestionIdKey, examQuestionIdKey)
	return ret, err
}

func (m *defaultExamQuestionModel) Update(ctx context.Context, newData *ExamQuestion) error {
	data, err := m.FindOne(ctx, newData.Id)
	if err != nil {
		return err
	}

	examQuestionExamIdQuestionIdKey := fmt.Sprintf("%s%v:%v", cacheExamQuestionExamIdQuestionIdPrefix, data.ExamId, data.QuestionId)
	examQuestionIdKey := fmt.Sprintf("%s%v", cacheExamQuestionIdPrefix, data.Id)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, examQuestionRowsWithPlaceHolder)
		return conn.ExecCtx(ctx, query, newData.ExamId, newData.QuestionId, newData.Score, newData.Sort, newData.Id)
	}, examQuestionExamIdQuestionIdKey, examQuestionIdKey)
	return err
}

func (m *defaultExamQuestionModel) formatPrimary(primary any) string {
	return fmt.Sprintf("%s%v", cacheExamQuestionIdPrefix, primary)
}

func (m *defaultExamQuestionModel) queryPrimary(ctx context.Context, conn sqlx.SqlConn, v, primary any) error {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", examQuestionRows, m.table)
	return conn.QueryRowCtx(ctx, v, query, primary)
}

func (m *defaultExamQuestionModel) tableName() string {
	return m.table
}
