// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.9.2

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	examFieldNames          = builder.RawFieldNames(&Exam{})
	examRows                = strings.Join(examFieldNames, ",")
	examRowsExpectAutoSet   = strings.Join(stringx.Remove(examFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	examRowsWithPlaceHolder = strings.Join(stringx.Remove(examFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"

	cacheExamIdPrefix = "cache:exam:id:"
)

type (
	examModel interface {
		Insert(ctx context.Context, data *Exam) (sql.Result, error)
		FindOne(ctx context.Context, id uint64) (*Exam, error)
		Update(ctx context.Context, data *Exam) error
		Delete(ctx context.Context, id uint64) error
	}

	defaultExamModel struct {
		sqlc.CachedConn
		table string
	}

	Exam struct {
		Id         uint64         `db:"id"`          // 主键ID
		CourseId   uint64         `db:"course_id"`   // 关联课程ID
		Title      string         `db:"title"`       // 试卷名称
		TotalScore float64        `db:"total_score"` // 总分
		PassScore  float64        `db:"pass_score"`  // 及格分
		Duration   int64          `db:"duration"`    // 考试时长(分钟)
		StartTime  sql.NullTime   `db:"start_time"`  // 考试开始时间
		EndTime    sql.NullTime   `db:"end_time"`    // 考试结束时间
		ExamType   int64          `db:"exam_type"`   // 组卷模式 1:固定 2:随机
		RuleJson   sql.NullString `db:"rule_json"`   // 随机组卷规则JSON
		Status     int64          `db:"status"`      // 状态 0:未开始 1:进行中 2:已结束
		CreateTime time.Time      `db:"create_time"` // 创建时间
		UpdateTime time.Time      `db:"update_time"` // 更新时间
		DeletedAt  sql.NullTime   `db:"deleted_at"`  // 删除时间
	}
)

func newExamModel(conn sqlx.SqlConn, c cache.CacheConf, opts ...cache.Option) *defaultExamModel {
	return &defaultExamModel{
		CachedConn: sqlc.NewConn(conn, c, opts...),
		table:      "`exam`",
	}
}

func (m *defaultExamModel) Delete(ctx context.Context, id uint64) error {
	examIdKey := fmt.Sprintf("%s%v", cacheExamIdPrefix, id)
	_, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
		return conn.ExecCtx(ctx, query, id)
	}, examIdKey)
	return err
}

func (m *defaultExamModel) FindOne(ctx context.Context, id uint64) (*Exam, error) {
	examIdKey := fmt.Sprintf("%s%v", cacheExamIdPrefix, id)
	var resp Exam
	err := m.QueryRowCtx(ctx, &resp, examIdKey, func(ctx context.Context, conn sqlx.SqlConn, v any) error {
		query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", examRows, m.table)
		return conn.QueryRowCtx(ctx, v, query, id)
	})
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultExamModel) Insert(ctx context.Context, data *Exam) (sql.Result, error) {
	examIdKey := fmt.Sprintf("%s%v", cacheExamIdPrefix, data.Id)
	ret, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)", m.table, examRowsExpectAutoSet)
		return conn.ExecCtx(ctx, query, data.CourseId, data.Title, data.TotalScore, data.PassScore, data.Duration, data.StartTime, data.EndTime, data.ExamType, data.RuleJson, data.Status, data.DeletedAt)
	}, examIdKey)
	return ret, err
}

func (m *defaultExamModel) Update(ctx context.Context, data *Exam) error {
	examIdKey := fmt.Sprintf("%s%v", cacheExamIdPrefix, data.Id)
	_, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, examRowsWithPlaceHolder)
		return conn.ExecCtx(ctx, query, data.CourseId, data.Title, data.TotalScore, data.PassScore, data.Duration, data.StartTime, data.EndTime, data.ExamType, data.RuleJson, data.Status, data.DeletedAt, data.Id)
	}, examIdKey)
	return err
}

func (m *defaultExamModel) formatPrimary(primary any) string {
	return fmt.Sprintf("%s%v", cacheExamIdPrefix, primary)
}

func (m *defaultExamModel) queryPrimary(ctx context.Context, conn sqlx.SqlConn, v, primary any) error {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", examRows, m.table)
	return conn.QueryRowCtx(ctx, v, query, primary)
}

func (m *defaultExamModel) tableName() string {
	return m.table
}
