// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.9.2

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	questionFieldNames          = builder.RawFieldNames(&Question{})
	questionRows                = strings.Join(questionFieldNames, ",")
	questionRowsExpectAutoSet   = strings.Join(stringx.Remove(questionFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	questionRowsWithPlaceHolder = strings.Join(stringx.Remove(questionFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"

	cacheQuestionIdPrefix = "cache:question:id:"
)

type (
	questionModel interface {
		Insert(ctx context.Context, data *Question) (sql.Result, error)
		FindOne(ctx context.Context, id uint64) (*Question, error)
		Update(ctx context.Context, data *Question) error
		Delete(ctx context.Context, id uint64) error
	}

	defaultQuestionModel struct {
		sqlc.CachedConn
		table string
	}

	Question struct {
		Id              uint64         `db:"id"`               // 主键ID
		CourseId        uint64         `db:"course_id"`        // 归属课程ID
		TeacherId       uint64         `db:"teacher_id"`       // 创建者教师ID
		Type            int64          `db:"type"`             // 题型 1:单选 2:多选 3:判断 4:填空 5:简答/主观题
		Content         string         `db:"content"`          // 题目内容(JSON,含选项)
		Answer          string         `db:"answer"`           // 标准答案
		Analysis        sql.NullString `db:"analysis"`         // 题目解析
		KnowledgePoints string         `db:"knowledge_points"` // 知识点(关联RAG)
		Score           float64        `db:"score"`            // 默认分值
		Difficulty      int64          `db:"difficulty"`       // 难度 1:简单 2:中等 3:困难
		CreateTime      time.Time      `db:"create_time"`      // 创建时间
		UpdateTime      time.Time      `db:"update_time"`      // 更新时间
		DeletedAt       sql.NullTime   `db:"deleted_at"`       // 删除时间
	}
)

func newQuestionModel(conn sqlx.SqlConn, c cache.CacheConf, opts ...cache.Option) *defaultQuestionModel {
	return &defaultQuestionModel{
		CachedConn: sqlc.NewConn(conn, c, opts...),
		table:      "`question`",
	}
}

func (m *defaultQuestionModel) Delete(ctx context.Context, id uint64) error {
	questionIdKey := fmt.Sprintf("%s%v", cacheQuestionIdPrefix, id)
	_, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
		return conn.ExecCtx(ctx, query, id)
	}, questionIdKey)
	return err
}

func (m *defaultQuestionModel) FindOne(ctx context.Context, id uint64) (*Question, error) {
	questionIdKey := fmt.Sprintf("%s%v", cacheQuestionIdPrefix, id)
	var resp Question
	err := m.QueryRowCtx(ctx, &resp, questionIdKey, func(ctx context.Context, conn sqlx.SqlConn, v any) error {
		query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", questionRows, m.table)
		return conn.QueryRowCtx(ctx, v, query, id)
	})
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultQuestionModel) Insert(ctx context.Context, data *Question) (sql.Result, error) {
	questionIdKey := fmt.Sprintf("%s%v", cacheQuestionIdPrefix, data.Id)
	ret, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)", m.table, questionRowsExpectAutoSet)
		return conn.ExecCtx(ctx, query, data.CourseId, data.TeacherId, data.Type, data.Content, data.Answer, data.Analysis, data.KnowledgePoints, data.Score, data.Difficulty, data.DeletedAt)
	}, questionIdKey)
	return ret, err
}

func (m *defaultQuestionModel) Update(ctx context.Context, data *Question) error {
	questionIdKey := fmt.Sprintf("%s%v", cacheQuestionIdPrefix, data.Id)
	_, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, questionRowsWithPlaceHolder)
		return conn.ExecCtx(ctx, query, data.CourseId, data.TeacherId, data.Type, data.Content, data.Answer, data.Analysis, data.KnowledgePoints, data.Score, data.Difficulty, data.DeletedAt, data.Id)
	}, questionIdKey)
	return err
}

func (m *defaultQuestionModel) formatPrimary(primary any) string {
	return fmt.Sprintf("%s%v", cacheQuestionIdPrefix, primary)
}

func (m *defaultQuestionModel) queryPrimary(ctx context.Context, conn sqlx.SqlConn, v, primary any) error {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", questionRows, m.table)
	return conn.QueryRowCtx(ctx, v, query, primary)
}

func (m *defaultQuestionModel) tableName() string {
	return m.table
}
