// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2
// Source: course.proto

package course

import (
	"context"

	"teaching-backend/application/course/rpc/pb"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	ChapterItem            = pb.ChapterItem
	ChapterListReq         = pb.ChapterListReq
	ChapterListRes         = pb.ChapterListRes
	CourseDetailReq        = pb.CourseDetailReq
	CourseDetailRes        = pb.CourseDetailRes
	CourseItem             = pb.CourseItem
	CourseListReq          = pb.CourseListReq
	CourseListRes          = pb.CourseListRes
	CreateChapterReq       = pb.CreateChapterReq
	CreateChapterRes       = pb.CreateChapterRes
	CreateCourseReq        = pb.CreateCourseReq
	CreateCourseRes        = pb.CreateCourseRes
	CreateMaterialReq      = pb.CreateMaterialReq
	CreateMaterialRes      = pb.CreateMaterialRes
	DeleteChapterReq       = pb.DeleteChapterReq
	DeleteChapterRes       = pb.DeleteChapterRes
	DeleteCourseReq        = pb.DeleteCourseReq
	DeleteCourseRes        = pb.DeleteCourseRes
	DeleteMaterialReq      = pb.DeleteMaterialReq
	DeleteMaterialRes      = pb.DeleteMaterialRes
	GetStudyProgressReq    = pb.GetStudyProgressReq
	GetStudyProgressRes    = pb.GetStudyProgressRes
	MaterialItem           = pb.MaterialItem
	MaterialListReq        = pb.MaterialListReq
	MaterialListRes        = pb.MaterialListRes
	StudyProgressItem      = pb.StudyProgressItem
	UpdateChapterReq       = pb.UpdateChapterReq
	UpdateChapterRes       = pb.UpdateChapterRes
	UpdateCourseReq        = pb.UpdateCourseReq
	UpdateCourseRes        = pb.UpdateCourseRes
	UpdateStudyProgressReq = pb.UpdateStudyProgressReq
	UpdateStudyProgressRes = pb.UpdateStudyProgressRes

	Course interface {
		// 创建课程
		CreateCourse(ctx context.Context, in *CreateCourseReq, opts ...grpc.CallOption) (*CreateCourseRes, error)
		// 课程列表
		CourseList(ctx context.Context, in *CourseListReq, opts ...grpc.CallOption) (*CourseListRes, error)
		// 课程详情
		CourseDetail(ctx context.Context, in *CourseDetailReq, opts ...grpc.CallOption) (*CourseDetailRes, error)
		// 更新课程
		UpdateCourse(ctx context.Context, in *UpdateCourseReq, opts ...grpc.CallOption) (*UpdateCourseRes, error)
		// 删除课程
		DeleteCourse(ctx context.Context, in *DeleteCourseReq, opts ...grpc.CallOption) (*DeleteCourseRes, error)
		// 创建章节
		CreateChapter(ctx context.Context, in *CreateChapterReq, opts ...grpc.CallOption) (*CreateChapterRes, error)
		// 章节列表
		ChapterList(ctx context.Context, in *ChapterListReq, opts ...grpc.CallOption) (*ChapterListRes, error)
		// 更新章节
		UpdateChapter(ctx context.Context, in *UpdateChapterReq, opts ...grpc.CallOption) (*UpdateChapterRes, error)
		// 删除章节
		DeleteChapter(ctx context.Context, in *DeleteChapterReq, opts ...grpc.CallOption) (*DeleteChapterRes, error)
		// 上传课件
		CreateMaterial(ctx context.Context, in *CreateMaterialReq, opts ...grpc.CallOption) (*CreateMaterialRes, error)
		// 课件列表
		MaterialList(ctx context.Context, in *MaterialListReq, opts ...grpc.CallOption) (*MaterialListRes, error)
		// 删除课件
		DeleteMaterial(ctx context.Context, in *DeleteMaterialReq, opts ...grpc.CallOption) (*DeleteMaterialRes, error)
		// 更新学习进度
		UpdateStudyProgress(ctx context.Context, in *UpdateStudyProgressReq, opts ...grpc.CallOption) (*UpdateStudyProgressRes, error)
		// 获取学习进度
		GetStudyProgress(ctx context.Context, in *GetStudyProgressReq, opts ...grpc.CallOption) (*GetStudyProgressRes, error)
	}

	defaultCourse struct {
		cli zrpc.Client
	}
)

func NewCourse(cli zrpc.Client) Course {
	return &defaultCourse{
		cli: cli,
	}
}

// 创建课程
func (m *defaultCourse) CreateCourse(ctx context.Context, in *CreateCourseReq, opts ...grpc.CallOption) (*CreateCourseRes, error) {
	client := pb.NewCourseClient(m.cli.Conn())
	return client.CreateCourse(ctx, in, opts...)
}

// 课程列表
func (m *defaultCourse) CourseList(ctx context.Context, in *CourseListReq, opts ...grpc.CallOption) (*CourseListRes, error) {
	client := pb.NewCourseClient(m.cli.Conn())
	return client.CourseList(ctx, in, opts...)
}

// 课程详情
func (m *defaultCourse) CourseDetail(ctx context.Context, in *CourseDetailReq, opts ...grpc.CallOption) (*CourseDetailRes, error) {
	client := pb.NewCourseClient(m.cli.Conn())
	return client.CourseDetail(ctx, in, opts...)
}

// 更新课程
func (m *defaultCourse) UpdateCourse(ctx context.Context, in *UpdateCourseReq, opts ...grpc.CallOption) (*UpdateCourseRes, error) {
	client := pb.NewCourseClient(m.cli.Conn())
	return client.UpdateCourse(ctx, in, opts...)
}

// 删除课程
func (m *defaultCourse) DeleteCourse(ctx context.Context, in *DeleteCourseReq, opts ...grpc.CallOption) (*DeleteCourseRes, error) {
	client := pb.NewCourseClient(m.cli.Conn())
	return client.DeleteCourse(ctx, in, opts...)
}

// 创建章节
func (m *defaultCourse) CreateChapter(ctx context.Context, in *CreateChapterReq, opts ...grpc.CallOption) (*CreateChapterRes, error) {
	client := pb.NewCourseClient(m.cli.Conn())
	return client.CreateChapter(ctx, in, opts...)
}

// 章节列表
func (m *defaultCourse) ChapterList(ctx context.Context, in *ChapterListReq, opts ...grpc.CallOption) (*ChapterListRes, error) {
	client := pb.NewCourseClient(m.cli.Conn())
	return client.ChapterList(ctx, in, opts...)
}

// 更新章节
func (m *defaultCourse) UpdateChapter(ctx context.Context, in *UpdateChapterReq, opts ...grpc.CallOption) (*UpdateChapterRes, error) {
	client := pb.NewCourseClient(m.cli.Conn())
	return client.UpdateChapter(ctx, in, opts...)
}

// 删除章节
func (m *defaultCourse) DeleteChapter(ctx context.Context, in *DeleteChapterReq, opts ...grpc.CallOption) (*DeleteChapterRes, error) {
	client := pb.NewCourseClient(m.cli.Conn())
	return client.DeleteChapter(ctx, in, opts...)
}

// 上传课件
func (m *defaultCourse) CreateMaterial(ctx context.Context, in *CreateMaterialReq, opts ...grpc.CallOption) (*CreateMaterialRes, error) {
	client := pb.NewCourseClient(m.cli.Conn())
	return client.CreateMaterial(ctx, in, opts...)
}

// 课件列表
func (m *defaultCourse) MaterialList(ctx context.Context, in *MaterialListReq, opts ...grpc.CallOption) (*MaterialListRes, error) {
	client := pb.NewCourseClient(m.cli.Conn())
	return client.MaterialList(ctx, in, opts...)
}

// 删除课件
func (m *defaultCourse) DeleteMaterial(ctx context.Context, in *DeleteMaterialReq, opts ...grpc.CallOption) (*DeleteMaterialRes, error) {
	client := pb.NewCourseClient(m.cli.Conn())
	return client.DeleteMaterial(ctx, in, opts...)
}

// 更新学习进度
func (m *defaultCourse) UpdateStudyProgress(ctx context.Context, in *UpdateStudyProgressReq, opts ...grpc.CallOption) (*UpdateStudyProgressRes, error) {
	client := pb.NewCourseClient(m.cli.Conn())
	return client.UpdateStudyProgress(ctx, in, opts...)
}

// 获取学习进度
func (m *defaultCourse) GetStudyProgress(ctx context.Context, in *GetStudyProgressReq, opts ...grpc.CallOption) (*GetStudyProgressRes, error) {
	client := pb.NewCourseClient(m.cli.Conn())
	return client.GetStudyProgress(ctx, in, opts...)
}
