// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: application/user/rpc/user.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RegisterReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Email         string                 `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	Code          string                 `protobuf:"bytes,3,opt,name=code,proto3" json:"code,omitempty"`  // 验证码
	Role          int32                  `protobuf:"varint,4,opt,name=role,proto3" json:"role,omitempty"` // 1:学生 2:教师 3:管理员
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterReq) Reset() {
	*x = RegisterReq{}
	mi := &file_application_user_rpc_user_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterReq) ProtoMessage() {}

func (x *RegisterReq) ProtoReflect() protoreflect.Message {
	mi := &file_application_user_rpc_user_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterReq.ProtoReflect.Descriptor instead.
func (*RegisterReq) Descriptor() ([]byte, []int) {
	return file_application_user_rpc_user_proto_rawDescGZIP(), []int{0}
}

func (x *RegisterReq) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *RegisterReq) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *RegisterReq) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *RegisterReq) GetRole() int32 {
	if x != nil {
		return x.Role
	}
	return 0
}

type RegisterRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterRes) Reset() {
	*x = RegisterRes{}
	mi := &file_application_user_rpc_user_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterRes) ProtoMessage() {}

func (x *RegisterRes) ProtoReflect() protoreflect.Message {
	mi := &file_application_user_rpc_user_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterRes.ProtoReflect.Descriptor instead.
func (*RegisterRes) Descriptor() ([]byte, []int) {
	return file_application_user_rpc_user_proto_rawDescGZIP(), []int{1}
}

func (x *RegisterRes) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type LoginReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Email         string                 `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginReq) Reset() {
	*x = LoginReq{}
	mi := &file_application_user_rpc_user_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginReq) ProtoMessage() {}

func (x *LoginReq) ProtoReflect() protoreflect.Message {
	mi := &file_application_user_rpc_user_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginReq.ProtoReflect.Descriptor instead.
func (*LoginReq) Descriptor() ([]byte, []int) {
	return file_application_user_rpc_user_proto_rawDescGZIP(), []int{2}
}

func (x *LoginReq) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *LoginReq) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type LoginRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Role          int32                  `protobuf:"varint,2,opt,name=role,proto3" json:"role,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginRes) Reset() {
	*x = LoginRes{}
	mi := &file_application_user_rpc_user_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginRes) ProtoMessage() {}

func (x *LoginRes) ProtoReflect() protoreflect.Message {
	mi := &file_application_user_rpc_user_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginRes.ProtoReflect.Descriptor instead.
func (*LoginRes) Descriptor() ([]byte, []int) {
	return file_application_user_rpc_user_proto_rawDescGZIP(), []int{3}
}

func (x *LoginRes) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *LoginRes) GetRole() int32 {
	if x != nil {
		return x.Role
	}
	return 0
}

type FindByIdReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FindByIdReq) Reset() {
	*x = FindByIdReq{}
	mi := &file_application_user_rpc_user_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FindByIdReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindByIdReq) ProtoMessage() {}

func (x *FindByIdReq) ProtoReflect() protoreflect.Message {
	mi := &file_application_user_rpc_user_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindByIdReq.ProtoReflect.Descriptor instead.
func (*FindByIdReq) Descriptor() ([]byte, []int) {
	return file_application_user_rpc_user_proto_rawDescGZIP(), []int{4}
}

func (x *FindByIdReq) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type FindByIdRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Email         string                 `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	Nickname      string                 `protobuf:"bytes,3,opt,name=nickname,proto3" json:"nickname,omitempty"`
	Avatar        string                 `protobuf:"bytes,4,opt,name=avatar,proto3" json:"avatar,omitempty"`
	Role          int32                  `protobuf:"varint,5,opt,name=role,proto3" json:"role,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FindByIdRes) Reset() {
	*x = FindByIdRes{}
	mi := &file_application_user_rpc_user_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FindByIdRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindByIdRes) ProtoMessage() {}

func (x *FindByIdRes) ProtoReflect() protoreflect.Message {
	mi := &file_application_user_rpc_user_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindByIdRes.ProtoReflect.Descriptor instead.
func (*FindByIdRes) Descriptor() ([]byte, []int) {
	return file_application_user_rpc_user_proto_rawDescGZIP(), []int{5}
}

func (x *FindByIdRes) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *FindByIdRes) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *FindByIdRes) GetNickname() string {
	if x != nil {
		return x.Nickname
	}
	return ""
}

func (x *FindByIdRes) GetAvatar() string {
	if x != nil {
		return x.Avatar
	}
	return ""
}

func (x *FindByIdRes) GetRole() int32 {
	if x != nil {
		return x.Role
	}
	return 0
}

type FindByEmailReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Email         string                 `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FindByEmailReq) Reset() {
	*x = FindByEmailReq{}
	mi := &file_application_user_rpc_user_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FindByEmailReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindByEmailReq) ProtoMessage() {}

func (x *FindByEmailReq) ProtoReflect() protoreflect.Message {
	mi := &file_application_user_rpc_user_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindByEmailReq.ProtoReflect.Descriptor instead.
func (*FindByEmailReq) Descriptor() ([]byte, []int) {
	return file_application_user_rpc_user_proto_rawDescGZIP(), []int{6}
}

func (x *FindByEmailReq) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

type FindByEmailRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Email         string                 `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	Nickname      string                 `protobuf:"bytes,3,opt,name=nickname,proto3" json:"nickname,omitempty"`
	Avatar        string                 `protobuf:"bytes,4,opt,name=avatar,proto3" json:"avatar,omitempty"`
	Role          int32                  `protobuf:"varint,5,opt,name=role,proto3" json:"role,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FindByEmailRes) Reset() {
	*x = FindByEmailRes{}
	mi := &file_application_user_rpc_user_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FindByEmailRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindByEmailRes) ProtoMessage() {}

func (x *FindByEmailRes) ProtoReflect() protoreflect.Message {
	mi := &file_application_user_rpc_user_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindByEmailRes.ProtoReflect.Descriptor instead.
func (*FindByEmailRes) Descriptor() ([]byte, []int) {
	return file_application_user_rpc_user_proto_rawDescGZIP(), []int{7}
}

func (x *FindByEmailRes) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *FindByEmailRes) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *FindByEmailRes) GetNickname() string {
	if x != nil {
		return x.Nickname
	}
	return ""
}

func (x *FindByEmailRes) GetAvatar() string {
	if x != nil {
		return x.Avatar
	}
	return ""
}

func (x *FindByEmailRes) GetRole() int32 {
	if x != nil {
		return x.Role
	}
	return 0
}

type SendVerifyCodeReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Email         string                 `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendVerifyCodeReq) Reset() {
	*x = SendVerifyCodeReq{}
	mi := &file_application_user_rpc_user_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendVerifyCodeReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendVerifyCodeReq) ProtoMessage() {}

func (x *SendVerifyCodeReq) ProtoReflect() protoreflect.Message {
	mi := &file_application_user_rpc_user_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendVerifyCodeReq.ProtoReflect.Descriptor instead.
func (*SendVerifyCodeReq) Descriptor() ([]byte, []int) {
	return file_application_user_rpc_user_proto_rawDescGZIP(), []int{8}
}

func (x *SendVerifyCodeReq) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

type SendVerifyCodeRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendVerifyCodeRes) Reset() {
	*x = SendVerifyCodeRes{}
	mi := &file_application_user_rpc_user_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendVerifyCodeRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendVerifyCodeRes) ProtoMessage() {}

func (x *SendVerifyCodeRes) ProtoReflect() protoreflect.Message {
	mi := &file_application_user_rpc_user_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendVerifyCodeRes.ProtoReflect.Descriptor instead.
func (*SendVerifyCodeRes) Descriptor() ([]byte, []int) {
	return file_application_user_rpc_user_proto_rawDescGZIP(), []int{9}
}

var File_application_user_rpc_user_proto protoreflect.FileDescriptor

const file_application_user_rpc_user_proto_rawDesc = "" +
	"\n" +
	"\x1fapplication/user/rpc/user.proto\x12\x04user\"g\n" +
	"\vRegisterReq\x12\x14\n" +
	"\x05email\x18\x01 \x01(\tR\x05email\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\x12\x12\n" +
	"\x04code\x18\x03 \x01(\tR\x04code\x12\x12\n" +
	"\x04role\x18\x04 \x01(\x05R\x04role\"&\n" +
	"\vRegisterRes\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\"<\n" +
	"\bLoginReq\x12\x14\n" +
	"\x05email\x18\x01 \x01(\tR\x05email\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\"7\n" +
	"\bLoginRes\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12\x12\n" +
	"\x04role\x18\x02 \x01(\x05R\x04role\"&\n" +
	"\vFindByIdReq\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\"\x84\x01\n" +
	"\vFindByIdRes\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12\x14\n" +
	"\x05email\x18\x02 \x01(\tR\x05email\x12\x1a\n" +
	"\bnickname\x18\x03 \x01(\tR\bnickname\x12\x16\n" +
	"\x06avatar\x18\x04 \x01(\tR\x06avatar\x12\x12\n" +
	"\x04role\x18\x05 \x01(\x05R\x04role\"&\n" +
	"\x0eFindByEmailReq\x12\x14\n" +
	"\x05email\x18\x01 \x01(\tR\x05email\"\x87\x01\n" +
	"\x0eFindByEmailRes\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12\x14\n" +
	"\x05email\x18\x02 \x01(\tR\x05email\x12\x1a\n" +
	"\bnickname\x18\x03 \x01(\tR\bnickname\x12\x16\n" +
	"\x06avatar\x18\x04 \x01(\tR\x06avatar\x12\x12\n" +
	"\x04role\x18\x05 \x01(\x05R\x04role\")\n" +
	"\x11SendVerifyCodeReq\x12\x14\n" +
	"\x05email\x18\x01 \x01(\tR\x05email\"\x13\n" +
	"\x11SendVerifyCodeRes2\x92\x02\n" +
	"\x04User\x120\n" +
	"\bRegister\x12\x11.user.RegisterReq\x1a\x11.user.RegisterRes\x12'\n" +
	"\x05Login\x12\x0e.user.LoginReq\x1a\x0e.user.LoginRes\x120\n" +
	"\bFindById\x12\x11.user.FindByIdReq\x1a\x11.user.FindByIdRes\x129\n" +
	"\vFindByEmail\x12\x14.user.FindByEmailReq\x1a\x14.user.FindByEmailRes\x12B\n" +
	"\x0eSendVerifyCode\x12\x17.user.SendVerifyCodeReq\x1a\x17.user.SendVerifyCodeResB\x06Z\x04./pbb\x06proto3"

var (
	file_application_user_rpc_user_proto_rawDescOnce sync.Once
	file_application_user_rpc_user_proto_rawDescData []byte
)

func file_application_user_rpc_user_proto_rawDescGZIP() []byte {
	file_application_user_rpc_user_proto_rawDescOnce.Do(func() {
		file_application_user_rpc_user_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_application_user_rpc_user_proto_rawDesc), len(file_application_user_rpc_user_proto_rawDesc)))
	})
	return file_application_user_rpc_user_proto_rawDescData
}

var file_application_user_rpc_user_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_application_user_rpc_user_proto_goTypes = []any{
	(*RegisterReq)(nil),       // 0: user.RegisterReq
	(*RegisterRes)(nil),       // 1: user.RegisterRes
	(*LoginReq)(nil),          // 2: user.LoginReq
	(*LoginRes)(nil),          // 3: user.LoginRes
	(*FindByIdReq)(nil),       // 4: user.FindByIdReq
	(*FindByIdRes)(nil),       // 5: user.FindByIdRes
	(*FindByEmailReq)(nil),    // 6: user.FindByEmailReq
	(*FindByEmailRes)(nil),    // 7: user.FindByEmailRes
	(*SendVerifyCodeReq)(nil), // 8: user.SendVerifyCodeReq
	(*SendVerifyCodeRes)(nil), // 9: user.SendVerifyCodeRes
}
var file_application_user_rpc_user_proto_depIdxs = []int32{
	0, // 0: user.User.Register:input_type -> user.RegisterReq
	2, // 1: user.User.Login:input_type -> user.LoginReq
	4, // 2: user.User.FindById:input_type -> user.FindByIdReq
	6, // 3: user.User.FindByEmail:input_type -> user.FindByEmailReq
	8, // 4: user.User.SendVerifyCode:input_type -> user.SendVerifyCodeReq
	1, // 5: user.User.Register:output_type -> user.RegisterRes
	3, // 6: user.User.Login:output_type -> user.LoginRes
	5, // 7: user.User.FindById:output_type -> user.FindByIdRes
	7, // 8: user.User.FindByEmail:output_type -> user.FindByEmailRes
	9, // 9: user.User.SendVerifyCode:output_type -> user.SendVerifyCodeRes
	5, // [5:10] is the sub-list for method output_type
	0, // [0:5] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_application_user_rpc_user_proto_init() }
func file_application_user_rpc_user_proto_init() {
	if File_application_user_rpc_user_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_application_user_rpc_user_proto_rawDesc), len(file_application_user_rpc_user_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_application_user_rpc_user_proto_goTypes,
		DependencyIndexes: file_application_user_rpc_user_proto_depIdxs,
		MessageInfos:      file_application_user_rpc_user_proto_msgTypes,
	}.Build()
	File_application_user_rpc_user_proto = out.File
	file_application_user_rpc_user_proto_goTypes = nil
	file_application_user_rpc_user_proto_depIdxs = nil
}
