// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2
// Source: exam.proto

package exam

import (
	"context"

	"teaching-backend/application/exam/rpc/pb"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	AddExamQuestionReq    = pb.AddExamQuestionReq
	AddExamQuestionRes    = pb.AddExamQuestionRes
	AnswerItem            = pb.AnswerItem
	CreateExamReq         = pb.CreateExamReq
	CreateExamRes         = pb.CreateExamRes
	CreateQuestionReq     = pb.CreateQuestionReq
	CreateQuestionRes     = pb.CreateQuestionRes
	DeleteExamReq         = pb.DeleteExamReq
	DeleteExamRes         = pb.DeleteExamRes
	DeleteQuestionReq     = pb.DeleteQuestionReq
	DeleteQuestionRes     = pb.DeleteQuestionRes
	ExamDetailReq         = pb.ExamDetailReq
	ExamDetailRes         = pb.ExamDetailRes
	ExamItem              = pb.ExamItem
	ExamListReq           = pb.ExamListReq
	ExamListRes           = pb.ExamListRes
	ExamQuestionItem      = pb.ExamQuestionItem
	GetExamResultReq      = pb.GetExamResultReq
	GetExamResultRes      = pb.GetExamResultRes
	GetUserAnswersReq     = pb.GetUserAnswersReq
	GetUserAnswersRes     = pb.GetUserAnswersRes
	QuestionDetailReq     = pb.QuestionDetailReq
	QuestionDetailRes     = pb.QuestionDetailRes
	QuestionItem          = pb.QuestionItem
	QuestionListReq       = pb.QuestionListReq
	QuestionListRes       = pb.QuestionListRes
	RemoveExamQuestionReq = pb.RemoveExamQuestionReq
	RemoveExamQuestionRes = pb.RemoveExamQuestionRes
	SaveAnswerSnapshotReq = pb.SaveAnswerSnapshotReq
	SaveAnswerSnapshotRes = pb.SaveAnswerSnapshotRes
	StartExamReq          = pb.StartExamReq
	StartExamRes          = pb.StartExamRes
	SubmitExamReq         = pb.SubmitExamReq
	SubmitExamRes         = pb.SubmitExamRes
	UpdateExamReq         = pb.UpdateExamReq
	UpdateExamRes         = pb.UpdateExamRes
	UpdateQuestionReq     = pb.UpdateQuestionReq
	UpdateQuestionRes     = pb.UpdateQuestionRes
	UserAnswerItem        = pb.UserAnswerItem

	Exam interface {
		// ========== 题库管理 ==========
		CreateQuestion(ctx context.Context, in *CreateQuestionReq, opts ...grpc.CallOption) (*CreateQuestionRes, error)
		// 题目列表
		QuestionList(ctx context.Context, in *QuestionListReq, opts ...grpc.CallOption) (*QuestionListRes, error)
		// 题目详情
		QuestionDetail(ctx context.Context, in *QuestionDetailReq, opts ...grpc.CallOption) (*QuestionDetailRes, error)
		// 更新题目
		UpdateQuestion(ctx context.Context, in *UpdateQuestionReq, opts ...grpc.CallOption) (*UpdateQuestionRes, error)
		// 删除题目
		DeleteQuestion(ctx context.Context, in *DeleteQuestionReq, opts ...grpc.CallOption) (*DeleteQuestionRes, error)
		// ========== 试卷管理 ==========
		CreateExam(ctx context.Context, in *CreateExamReq, opts ...grpc.CallOption) (*CreateExamRes, error)
		// 试卷列表
		ExamList(ctx context.Context, in *ExamListReq, opts ...grpc.CallOption) (*ExamListRes, error)
		// 试卷详情(含题目)
		ExamDetail(ctx context.Context, in *ExamDetailReq, opts ...grpc.CallOption) (*ExamDetailRes, error)
		// 更新试卷
		UpdateExam(ctx context.Context, in *UpdateExamReq, opts ...grpc.CallOption) (*UpdateExamRes, error)
		// 删除试卷
		DeleteExam(ctx context.Context, in *DeleteExamReq, opts ...grpc.CallOption) (*DeleteExamRes, error)
		// 给试卷添加题目
		AddExamQuestion(ctx context.Context, in *AddExamQuestionReq, opts ...grpc.CallOption) (*AddExamQuestionRes, error)
		// 移除试卷题目
		RemoveExamQuestion(ctx context.Context, in *RemoveExamQuestionReq, opts ...grpc.CallOption) (*RemoveExamQuestionRes, error)
		// ========== 考试作答 ==========
		StartExam(ctx context.Context, in *StartExamReq, opts ...grpc.CallOption) (*StartExamRes, error)
		// 提交答卷
		SubmitExam(ctx context.Context, in *SubmitExamReq, opts ...grpc.CallOption) (*SubmitExamRes, error)
		// 考试心跳与答案快照保存 (存Redis)
		SaveAnswerSnapshot(ctx context.Context, in *SaveAnswerSnapshotReq, opts ...grpc.CallOption) (*SaveAnswerSnapshotRes, error)
		// 获取考试结果
		GetExamResult(ctx context.Context, in *GetExamResultReq, opts ...grpc.CallOption) (*GetExamResultRes, error)
		// 获取学生答题明细
		GetUserAnswers(ctx context.Context, in *GetUserAnswersReq, opts ...grpc.CallOption) (*GetUserAnswersRes, error)
	}

	defaultExam struct {
		cli zrpc.Client
	}
)

func NewExam(cli zrpc.Client) Exam {
	return &defaultExam{
		cli: cli,
	}
}

// ========== 题库管理 ==========
func (m *defaultExam) CreateQuestion(ctx context.Context, in *CreateQuestionReq, opts ...grpc.CallOption) (*CreateQuestionRes, error) {
	client := pb.NewExamClient(m.cli.Conn())
	return client.CreateQuestion(ctx, in, opts...)
}

// 题目列表
func (m *defaultExam) QuestionList(ctx context.Context, in *QuestionListReq, opts ...grpc.CallOption) (*QuestionListRes, error) {
	client := pb.NewExamClient(m.cli.Conn())
	return client.QuestionList(ctx, in, opts...)
}

// 题目详情
func (m *defaultExam) QuestionDetail(ctx context.Context, in *QuestionDetailReq, opts ...grpc.CallOption) (*QuestionDetailRes, error) {
	client := pb.NewExamClient(m.cli.Conn())
	return client.QuestionDetail(ctx, in, opts...)
}

// 更新题目
func (m *defaultExam) UpdateQuestion(ctx context.Context, in *UpdateQuestionReq, opts ...grpc.CallOption) (*UpdateQuestionRes, error) {
	client := pb.NewExamClient(m.cli.Conn())
	return client.UpdateQuestion(ctx, in, opts...)
}

// 删除题目
func (m *defaultExam) DeleteQuestion(ctx context.Context, in *DeleteQuestionReq, opts ...grpc.CallOption) (*DeleteQuestionRes, error) {
	client := pb.NewExamClient(m.cli.Conn())
	return client.DeleteQuestion(ctx, in, opts...)
}

// ========== 试卷管理 ==========
func (m *defaultExam) CreateExam(ctx context.Context, in *CreateExamReq, opts ...grpc.CallOption) (*CreateExamRes, error) {
	client := pb.NewExamClient(m.cli.Conn())
	return client.CreateExam(ctx, in, opts...)
}

// 试卷列表
func (m *defaultExam) ExamList(ctx context.Context, in *ExamListReq, opts ...grpc.CallOption) (*ExamListRes, error) {
	client := pb.NewExamClient(m.cli.Conn())
	return client.ExamList(ctx, in, opts...)
}

// 试卷详情(含题目)
func (m *defaultExam) ExamDetail(ctx context.Context, in *ExamDetailReq, opts ...grpc.CallOption) (*ExamDetailRes, error) {
	client := pb.NewExamClient(m.cli.Conn())
	return client.ExamDetail(ctx, in, opts...)
}

// 更新试卷
func (m *defaultExam) UpdateExam(ctx context.Context, in *UpdateExamReq, opts ...grpc.CallOption) (*UpdateExamRes, error) {
	client := pb.NewExamClient(m.cli.Conn())
	return client.UpdateExam(ctx, in, opts...)
}

// 删除试卷
func (m *defaultExam) DeleteExam(ctx context.Context, in *DeleteExamReq, opts ...grpc.CallOption) (*DeleteExamRes, error) {
	client := pb.NewExamClient(m.cli.Conn())
	return client.DeleteExam(ctx, in, opts...)
}

// 给试卷添加题目
func (m *defaultExam) AddExamQuestion(ctx context.Context, in *AddExamQuestionReq, opts ...grpc.CallOption) (*AddExamQuestionRes, error) {
	client := pb.NewExamClient(m.cli.Conn())
	return client.AddExamQuestion(ctx, in, opts...)
}

// 移除试卷题目
func (m *defaultExam) RemoveExamQuestion(ctx context.Context, in *RemoveExamQuestionReq, opts ...grpc.CallOption) (*RemoveExamQuestionRes, error) {
	client := pb.NewExamClient(m.cli.Conn())
	return client.RemoveExamQuestion(ctx, in, opts...)
}

// ========== 考试作答 ==========
func (m *defaultExam) StartExam(ctx context.Context, in *StartExamReq, opts ...grpc.CallOption) (*StartExamRes, error) {
	client := pb.NewExamClient(m.cli.Conn())
	return client.StartExam(ctx, in, opts...)
}

// 提交答卷
func (m *defaultExam) SubmitExam(ctx context.Context, in *SubmitExamReq, opts ...grpc.CallOption) (*SubmitExamRes, error) {
	client := pb.NewExamClient(m.cli.Conn())
	return client.SubmitExam(ctx, in, opts...)
}

// 考试心跳与答案快照保存 (存Redis)
func (m *defaultExam) SaveAnswerSnapshot(ctx context.Context, in *SaveAnswerSnapshotReq, opts ...grpc.CallOption) (*SaveAnswerSnapshotRes, error) {
	client := pb.NewExamClient(m.cli.Conn())
	return client.SaveAnswerSnapshot(ctx, in, opts...)
}

// 获取考试结果
func (m *defaultExam) GetExamResult(ctx context.Context, in *GetExamResultReq, opts ...grpc.CallOption) (*GetExamResultRes, error) {
	client := pb.NewExamClient(m.cli.Conn())
	return client.GetExamResult(ctx, in, opts...)
}

// 获取学生答题明细
func (m *defaultExam) GetUserAnswers(ctx context.Context, in *GetUserAnswersReq, opts ...grpc.CallOption) (*GetUserAnswersRes, error) {
	client := pb.NewExamClient(m.cli.Conn())
	return client.GetUserAnswers(ctx, in, opts...)
}
