// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.19.4
// source: ai.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SubjectiveQuestionInput struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	RecordId        int64                  `protobuf:"varint,1,opt,name=record_id,json=recordId,proto3" json:"record_id,omitempty"`
	QuestionId      int64                  `protobuf:"varint,2,opt,name=question_id,json=questionId,proto3" json:"question_id,omitempty"`
	QuestionContent string                 `protobuf:"bytes,3,opt,name=question_content,json=questionContent,proto3" json:"question_content,omitempty"`
	StandardAnswer  string                 `protobuf:"bytes,4,opt,name=standard_answer,json=standardAnswer,proto3" json:"standard_answer,omitempty"`
	KnowledgePoints string                 `protobuf:"bytes,5,opt,name=knowledge_points,json=knowledgePoints,proto3" json:"knowledge_points,omitempty"`
	UserAnswer      string                 `protobuf:"bytes,6,opt,name=user_answer,json=userAnswer,proto3" json:"user_answer,omitempty"`
	MaxScore        string                 `protobuf:"bytes,7,opt,name=max_score,json=maxScore,proto3" json:"max_score,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *SubjectiveQuestionInput) Reset() {
	*x = SubjectiveQuestionInput{}
	mi := &file_ai_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubjectiveQuestionInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubjectiveQuestionInput) ProtoMessage() {}

func (x *SubjectiveQuestionInput) ProtoReflect() protoreflect.Message {
	mi := &file_ai_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubjectiveQuestionInput.ProtoReflect.Descriptor instead.
func (*SubjectiveQuestionInput) Descriptor() ([]byte, []int) {
	return file_ai_proto_rawDescGZIP(), []int{0}
}

func (x *SubjectiveQuestionInput) GetRecordId() int64 {
	if x != nil {
		return x.RecordId
	}
	return 0
}

func (x *SubjectiveQuestionInput) GetQuestionId() int64 {
	if x != nil {
		return x.QuestionId
	}
	return 0
}

func (x *SubjectiveQuestionInput) GetQuestionContent() string {
	if x != nil {
		return x.QuestionContent
	}
	return ""
}

func (x *SubjectiveQuestionInput) GetStandardAnswer() string {
	if x != nil {
		return x.StandardAnswer
	}
	return ""
}

func (x *SubjectiveQuestionInput) GetKnowledgePoints() string {
	if x != nil {
		return x.KnowledgePoints
	}
	return ""
}

func (x *SubjectiveQuestionInput) GetUserAnswer() string {
	if x != nil {
		return x.UserAnswer
	}
	return ""
}

func (x *SubjectiveQuestionInput) GetMaxScore() string {
	if x != nil {
		return x.MaxScore
	}
	return ""
}

type GradeSubjectiveQuestionReq struct {
	state         protoimpl.MessageState   `protogen:"open.v1"`
	Input         *SubjectiveQuestionInput `protobuf:"bytes,1,opt,name=input,proto3" json:"input,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GradeSubjectiveQuestionReq) Reset() {
	*x = GradeSubjectiveQuestionReq{}
	mi := &file_ai_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GradeSubjectiveQuestionReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GradeSubjectiveQuestionReq) ProtoMessage() {}

func (x *GradeSubjectiveQuestionReq) ProtoReflect() protoreflect.Message {
	mi := &file_ai_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GradeSubjectiveQuestionReq.ProtoReflect.Descriptor instead.
func (*GradeSubjectiveQuestionReq) Descriptor() ([]byte, []int) {
	return file_ai_proto_rawDescGZIP(), []int{1}
}

func (x *GradeSubjectiveQuestionReq) GetInput() *SubjectiveQuestionInput {
	if x != nil {
		return x.Input
	}
	return nil
}

type GradeSubjectiveQuestionRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	QuestionId    int64                  `protobuf:"varint,1,opt,name=question_id,json=questionId,proto3" json:"question_id,omitempty"`
	Score         string                 `protobuf:"bytes,2,opt,name=score,proto3" json:"score,omitempty"`
	IsCorrect     int32                  `protobuf:"varint,3,opt,name=is_correct,json=isCorrect,proto3" json:"is_correct,omitempty"`
	AiComment     string                 `protobuf:"bytes,4,opt,name=ai_comment,json=aiComment,proto3" json:"ai_comment,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GradeSubjectiveQuestionRes) Reset() {
	*x = GradeSubjectiveQuestionRes{}
	mi := &file_ai_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GradeSubjectiveQuestionRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GradeSubjectiveQuestionRes) ProtoMessage() {}

func (x *GradeSubjectiveQuestionRes) ProtoReflect() protoreflect.Message {
	mi := &file_ai_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GradeSubjectiveQuestionRes.ProtoReflect.Descriptor instead.
func (*GradeSubjectiveQuestionRes) Descriptor() ([]byte, []int) {
	return file_ai_proto_rawDescGZIP(), []int{2}
}

func (x *GradeSubjectiveQuestionRes) GetQuestionId() int64 {
	if x != nil {
		return x.QuestionId
	}
	return 0
}

func (x *GradeSubjectiveQuestionRes) GetScore() string {
	if x != nil {
		return x.Score
	}
	return ""
}

func (x *GradeSubjectiveQuestionRes) GetIsCorrect() int32 {
	if x != nil {
		return x.IsCorrect
	}
	return 0
}

func (x *GradeSubjectiveQuestionRes) GetAiComment() string {
	if x != nil {
		return x.AiComment
	}
	return ""
}

type GradeExamSubjectiveReq struct {
	state         protoimpl.MessageState     `protogen:"open.v1"`
	RecordId      int64                      `protobuf:"varint,1,opt,name=record_id,json=recordId,proto3" json:"record_id,omitempty"`
	ExamId        int64                      `protobuf:"varint,2,opt,name=exam_id,json=examId,proto3" json:"exam_id,omitempty"`
	UserId        int64                      `protobuf:"varint,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Questions     []*SubjectiveQuestionInput `protobuf:"bytes,4,rep,name=questions,proto3" json:"questions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GradeExamSubjectiveReq) Reset() {
	*x = GradeExamSubjectiveReq{}
	mi := &file_ai_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GradeExamSubjectiveReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GradeExamSubjectiveReq) ProtoMessage() {}

func (x *GradeExamSubjectiveReq) ProtoReflect() protoreflect.Message {
	mi := &file_ai_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GradeExamSubjectiveReq.ProtoReflect.Descriptor instead.
func (*GradeExamSubjectiveReq) Descriptor() ([]byte, []int) {
	return file_ai_proto_rawDescGZIP(), []int{3}
}

func (x *GradeExamSubjectiveReq) GetRecordId() int64 {
	if x != nil {
		return x.RecordId
	}
	return 0
}

func (x *GradeExamSubjectiveReq) GetExamId() int64 {
	if x != nil {
		return x.ExamId
	}
	return 0
}

func (x *GradeExamSubjectiveReq) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *GradeExamSubjectiveReq) GetQuestions() []*SubjectiveQuestionInput {
	if x != nil {
		return x.Questions
	}
	return nil
}

type GradeExamSubjectiveRes struct {
	state         protoimpl.MessageState        `protogen:"open.v1"`
	Results       []*GradeSubjectiveQuestionRes `protobuf:"bytes,1,rep,name=results,proto3" json:"results,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GradeExamSubjectiveRes) Reset() {
	*x = GradeExamSubjectiveRes{}
	mi := &file_ai_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GradeExamSubjectiveRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GradeExamSubjectiveRes) ProtoMessage() {}

func (x *GradeExamSubjectiveRes) ProtoReflect() protoreflect.Message {
	mi := &file_ai_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GradeExamSubjectiveRes.ProtoReflect.Descriptor instead.
func (*GradeExamSubjectiveRes) Descriptor() ([]byte, []int) {
	return file_ai_proto_rawDescGZIP(), []int{4}
}

func (x *GradeExamSubjectiveRes) GetResults() []*GradeSubjectiveQuestionRes {
	if x != nil {
		return x.Results
	}
	return nil
}

type EmbedMaterialReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MaterialId    int64                  `protobuf:"varint,1,opt,name=material_id,json=materialId,proto3" json:"material_id,omitempty"`
	CourseId      int64                  `protobuf:"varint,2,opt,name=course_id,json=courseId,proto3" json:"course_id,omitempty"`
	Title         string                 `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	Url           string                 `protobuf:"bytes,4,opt,name=url,proto3" json:"url,omitempty"`
	Type          int32                  `protobuf:"varint,5,opt,name=type,proto3" json:"type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EmbedMaterialReq) Reset() {
	*x = EmbedMaterialReq{}
	mi := &file_ai_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EmbedMaterialReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmbedMaterialReq) ProtoMessage() {}

func (x *EmbedMaterialReq) ProtoReflect() protoreflect.Message {
	mi := &file_ai_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmbedMaterialReq.ProtoReflect.Descriptor instead.
func (*EmbedMaterialReq) Descriptor() ([]byte, []int) {
	return file_ai_proto_rawDescGZIP(), []int{5}
}

func (x *EmbedMaterialReq) GetMaterialId() int64 {
	if x != nil {
		return x.MaterialId
	}
	return 0
}

func (x *EmbedMaterialReq) GetCourseId() int64 {
	if x != nil {
		return x.CourseId
	}
	return 0
}

func (x *EmbedMaterialReq) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *EmbedMaterialReq) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *EmbedMaterialReq) GetType() int32 {
	if x != nil {
		return x.Type
	}
	return 0
}

type EmbedMaterialRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Accepted      bool                   `protobuf:"varint,1,opt,name=accepted,proto3" json:"accepted,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EmbedMaterialRes) Reset() {
	*x = EmbedMaterialRes{}
	mi := &file_ai_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EmbedMaterialRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmbedMaterialRes) ProtoMessage() {}

func (x *EmbedMaterialRes) ProtoReflect() protoreflect.Message {
	mi := &file_ai_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmbedMaterialRes.ProtoReflect.Descriptor instead.
func (*EmbedMaterialRes) Descriptor() ([]byte, []int) {
	return file_ai_proto_rawDescGZIP(), []int{6}
}

func (x *EmbedMaterialRes) GetAccepted() bool {
	if x != nil {
		return x.Accepted
	}
	return false
}

type GetEmbedStatusReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MaterialId    int64                  `protobuf:"varint,1,opt,name=material_id,json=materialId,proto3" json:"material_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetEmbedStatusReq) Reset() {
	*x = GetEmbedStatusReq{}
	mi := &file_ai_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetEmbedStatusReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetEmbedStatusReq) ProtoMessage() {}

func (x *GetEmbedStatusReq) ProtoReflect() protoreflect.Message {
	mi := &file_ai_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetEmbedStatusReq.ProtoReflect.Descriptor instead.
func (*GetEmbedStatusReq) Descriptor() ([]byte, []int) {
	return file_ai_proto_rawDescGZIP(), []int{7}
}

func (x *GetEmbedStatusReq) GetMaterialId() int64 {
	if x != nil {
		return x.MaterialId
	}
	return 0
}

type GetEmbedStatusRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AiStatus      int32                  `protobuf:"varint,1,opt,name=ai_status,json=aiStatus,proto3" json:"ai_status,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetEmbedStatusRes) Reset() {
	*x = GetEmbedStatusRes{}
	mi := &file_ai_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetEmbedStatusRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetEmbedStatusRes) ProtoMessage() {}

func (x *GetEmbedStatusRes) ProtoReflect() protoreflect.Message {
	mi := &file_ai_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetEmbedStatusRes.ProtoReflect.Descriptor instead.
func (*GetEmbedStatusRes) Descriptor() ([]byte, []int) {
	return file_ai_proto_rawDescGZIP(), []int{8}
}

func (x *GetEmbedStatusRes) GetAiStatus() int32 {
	if x != nil {
		return x.AiStatus
	}
	return 0
}

func (x *GetEmbedStatusRes) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type AskQuestionReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CourseId      int64                  `protobuf:"varint,1,opt,name=course_id,json=courseId,proto3" json:"course_id,omitempty"`
	UserId        int64                  `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Question      string                 `protobuf:"bytes,3,opt,name=question,proto3" json:"question,omitempty"`
	History       []string               `protobuf:"bytes,4,rep,name=history,proto3" json:"history,omitempty"`
	SessionId     string                 `protobuf:"bytes,5,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"` // 多轮对话标识；为空则服务端新建会话
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AskQuestionReq) Reset() {
	*x = AskQuestionReq{}
	mi := &file_ai_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AskQuestionReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AskQuestionReq) ProtoMessage() {}

func (x *AskQuestionReq) ProtoReflect() protoreflect.Message {
	mi := &file_ai_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AskQuestionReq.ProtoReflect.Descriptor instead.
func (*AskQuestionReq) Descriptor() ([]byte, []int) {
	return file_ai_proto_rawDescGZIP(), []int{9}
}

func (x *AskQuestionReq) GetCourseId() int64 {
	if x != nil {
		return x.CourseId
	}
	return 0
}

func (x *AskQuestionReq) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *AskQuestionReq) GetQuestion() string {
	if x != nil {
		return x.Question
	}
	return ""
}

func (x *AskQuestionReq) GetHistory() []string {
	if x != nil {
		return x.History
	}
	return nil
}

func (x *AskQuestionReq) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

type AskQuestionRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Answer        string                 `protobuf:"bytes,1,opt,name=answer,proto3" json:"answer,omitempty"`
	Sources       []string               `protobuf:"bytes,2,rep,name=sources,proto3" json:"sources,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AskQuestionRes) Reset() {
	*x = AskQuestionRes{}
	mi := &file_ai_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AskQuestionRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AskQuestionRes) ProtoMessage() {}

func (x *AskQuestionRes) ProtoReflect() protoreflect.Message {
	mi := &file_ai_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AskQuestionRes.ProtoReflect.Descriptor instead.
func (*AskQuestionRes) Descriptor() ([]byte, []int) {
	return file_ai_proto_rawDescGZIP(), []int{10}
}

func (x *AskQuestionRes) GetAnswer() string {
	if x != nil {
		return x.Answer
	}
	return ""
}

func (x *AskQuestionRes) GetSources() []string {
	if x != nil {
		return x.Sources
	}
	return nil
}

type AskQuestionStreamRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Delta         string                 `protobuf:"bytes,1,opt,name=delta,proto3" json:"delta,omitempty"`
	Sources       []string               `protobuf:"bytes,2,rep,name=sources,proto3" json:"sources,omitempty"`
	Finished      bool                   `protobuf:"varint,3,opt,name=finished,proto3" json:"finished,omitempty"`
	SessionId     string                 `protobuf:"bytes,4,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"` // 首帧返回，客户端保存用于后续多轮
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AskQuestionStreamRes) Reset() {
	*x = AskQuestionStreamRes{}
	mi := &file_ai_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AskQuestionStreamRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AskQuestionStreamRes) ProtoMessage() {}

func (x *AskQuestionStreamRes) ProtoReflect() protoreflect.Message {
	mi := &file_ai_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AskQuestionStreamRes.ProtoReflect.Descriptor instead.
func (*AskQuestionStreamRes) Descriptor() ([]byte, []int) {
	return file_ai_proto_rawDescGZIP(), []int{11}
}

func (x *AskQuestionStreamRes) GetDelta() string {
	if x != nil {
		return x.Delta
	}
	return ""
}

func (x *AskQuestionStreamRes) GetSources() []string {
	if x != nil {
		return x.Sources
	}
	return nil
}

func (x *AskQuestionStreamRes) GetFinished() bool {
	if x != nil {
		return x.Finished
	}
	return false
}

func (x *AskQuestionStreamRes) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

type GenerateCoursewareStreamRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Delta         string                 `protobuf:"bytes,1,opt,name=delta,proto3" json:"delta,omitempty"`
	Finished      bool                   `protobuf:"varint,2,opt,name=finished,proto3" json:"finished,omitempty"`
	SessionId     string                 `protobuf:"bytes,3,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"` // 首帧返回
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GenerateCoursewareStreamRes) Reset() {
	*x = GenerateCoursewareStreamRes{}
	mi := &file_ai_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenerateCoursewareStreamRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateCoursewareStreamRes) ProtoMessage() {}

func (x *GenerateCoursewareStreamRes) ProtoReflect() protoreflect.Message {
	mi := &file_ai_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerateCoursewareStreamRes.ProtoReflect.Descriptor instead.
func (*GenerateCoursewareStreamRes) Descriptor() ([]byte, []int) {
	return file_ai_proto_rawDescGZIP(), []int{12}
}

func (x *GenerateCoursewareStreamRes) GetDelta() string {
	if x != nil {
		return x.Delta
	}
	return ""
}

func (x *GenerateCoursewareStreamRes) GetFinished() bool {
	if x != nil {
		return x.Finished
	}
	return false
}

func (x *GenerateCoursewareStreamRes) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

type GenerateQuestionsReq struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	CourseId        int64                  `protobuf:"varint,1,opt,name=course_id,json=courseId,proto3" json:"course_id,omitempty"`
	KnowledgePoints string                 `protobuf:"bytes,2,opt,name=knowledge_points,json=knowledgePoints,proto3" json:"knowledge_points,omitempty"`
	Count           int32                  `protobuf:"varint,3,opt,name=count,proto3" json:"count,omitempty"`
	Type            int32                  `protobuf:"varint,4,opt,name=type,proto3" json:"type,omitempty"`
	Difficulty      int32                  `protobuf:"varint,5,opt,name=difficulty,proto3" json:"difficulty,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *GenerateQuestionsReq) Reset() {
	*x = GenerateQuestionsReq{}
	mi := &file_ai_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenerateQuestionsReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateQuestionsReq) ProtoMessage() {}

func (x *GenerateQuestionsReq) ProtoReflect() protoreflect.Message {
	mi := &file_ai_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerateQuestionsReq.ProtoReflect.Descriptor instead.
func (*GenerateQuestionsReq) Descriptor() ([]byte, []int) {
	return file_ai_proto_rawDescGZIP(), []int{13}
}

func (x *GenerateQuestionsReq) GetCourseId() int64 {
	if x != nil {
		return x.CourseId
	}
	return 0
}

func (x *GenerateQuestionsReq) GetKnowledgePoints() string {
	if x != nil {
		return x.KnowledgePoints
	}
	return ""
}

func (x *GenerateQuestionsReq) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

func (x *GenerateQuestionsReq) GetType() int32 {
	if x != nil {
		return x.Type
	}
	return 0
}

func (x *GenerateQuestionsReq) GetDifficulty() int32 {
	if x != nil {
		return x.Difficulty
	}
	return 0
}

type GeneratedQuestion struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Content         string                 `protobuf:"bytes,1,opt,name=content,proto3" json:"content,omitempty"`
	Answer          string                 `protobuf:"bytes,2,opt,name=answer,proto3" json:"answer,omitempty"`
	Analysis        string                 `protobuf:"bytes,3,opt,name=analysis,proto3" json:"analysis,omitempty"`
	KnowledgePoints string                 `protobuf:"bytes,4,opt,name=knowledge_points,json=knowledgePoints,proto3" json:"knowledge_points,omitempty"`
	Score           string                 `protobuf:"bytes,5,opt,name=score,proto3" json:"score,omitempty"`
	Type            int32                  `protobuf:"varint,6,opt,name=type,proto3" json:"type,omitempty"`
	Difficulty      int32                  `protobuf:"varint,7,opt,name=difficulty,proto3" json:"difficulty,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *GeneratedQuestion) Reset() {
	*x = GeneratedQuestion{}
	mi := &file_ai_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GeneratedQuestion) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GeneratedQuestion) ProtoMessage() {}

func (x *GeneratedQuestion) ProtoReflect() protoreflect.Message {
	mi := &file_ai_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GeneratedQuestion.ProtoReflect.Descriptor instead.
func (*GeneratedQuestion) Descriptor() ([]byte, []int) {
	return file_ai_proto_rawDescGZIP(), []int{14}
}

func (x *GeneratedQuestion) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *GeneratedQuestion) GetAnswer() string {
	if x != nil {
		return x.Answer
	}
	return ""
}

func (x *GeneratedQuestion) GetAnalysis() string {
	if x != nil {
		return x.Analysis
	}
	return ""
}

func (x *GeneratedQuestion) GetKnowledgePoints() string {
	if x != nil {
		return x.KnowledgePoints
	}
	return ""
}

func (x *GeneratedQuestion) GetScore() string {
	if x != nil {
		return x.Score
	}
	return ""
}

func (x *GeneratedQuestion) GetType() int32 {
	if x != nil {
		return x.Type
	}
	return 0
}

func (x *GeneratedQuestion) GetDifficulty() int32 {
	if x != nil {
		return x.Difficulty
	}
	return 0
}

type GenerateCourseOutlineReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CourseId      int64                  `protobuf:"varint,1,opt,name=course_id,json=courseId,proto3" json:"course_id,omitempty"`
	Topic         string                 `protobuf:"bytes,2,opt,name=topic,proto3" json:"topic,omitempty"`
	Requirements  string                 `protobuf:"bytes,3,opt,name=requirements,proto3" json:"requirements,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GenerateCourseOutlineReq) Reset() {
	*x = GenerateCourseOutlineReq{}
	mi := &file_ai_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenerateCourseOutlineReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateCourseOutlineReq) ProtoMessage() {}

func (x *GenerateCourseOutlineReq) ProtoReflect() protoreflect.Message {
	mi := &file_ai_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerateCourseOutlineReq.ProtoReflect.Descriptor instead.
func (*GenerateCourseOutlineReq) Descriptor() ([]byte, []int) {
	return file_ai_proto_rawDescGZIP(), []int{15}
}

func (x *GenerateCourseOutlineReq) GetCourseId() int64 {
	if x != nil {
		return x.CourseId
	}
	return 0
}

func (x *GenerateCourseOutlineReq) GetTopic() string {
	if x != nil {
		return x.Topic
	}
	return ""
}

func (x *GenerateCourseOutlineReq) GetRequirements() string {
	if x != nil {
		return x.Requirements
	}
	return ""
}

type GenerateCoursewareReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChapterId     int64                  `protobuf:"varint,1,opt,name=chapter_id,json=chapterId,proto3" json:"chapter_id,omitempty"`
	Requirements  string                 `protobuf:"bytes,2,opt,name=requirements,proto3" json:"requirements,omitempty"`
	UserId        int64                  `protobuf:"varint,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`         // 用于 session 隔离
	SessionId     string                 `protobuf:"bytes,4,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"` // 多轮对话标识；为空则服务端新建会话
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GenerateCoursewareReq) Reset() {
	*x = GenerateCoursewareReq{}
	mi := &file_ai_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenerateCoursewareReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateCoursewareReq) ProtoMessage() {}

func (x *GenerateCoursewareReq) ProtoReflect() protoreflect.Message {
	mi := &file_ai_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerateCoursewareReq.ProtoReflect.Descriptor instead.
func (*GenerateCoursewareReq) Descriptor() ([]byte, []int) {
	return file_ai_proto_rawDescGZIP(), []int{16}
}

func (x *GenerateCoursewareReq) GetChapterId() int64 {
	if x != nil {
		return x.ChapterId
	}
	return 0
}

func (x *GenerateCoursewareReq) GetRequirements() string {
	if x != nil {
		return x.Requirements
	}
	return ""
}

func (x *GenerateCoursewareReq) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *GenerateCoursewareReq) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

type GenerateTaskRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GenerateTaskRes) Reset() {
	*x = GenerateTaskRes{}
	mi := &file_ai_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenerateTaskRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateTaskRes) ProtoMessage() {}

func (x *GenerateTaskRes) ProtoReflect() protoreflect.Message {
	mi := &file_ai_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerateTaskRes.ProtoReflect.Descriptor instead.
func (*GenerateTaskRes) Descriptor() ([]byte, []int) {
	return file_ai_proto_rawDescGZIP(), []int{17}
}

func (x *GenerateTaskRes) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

type GetAiTaskStatusReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAiTaskStatusReq) Reset() {
	*x = GetAiTaskStatusReq{}
	mi := &file_ai_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAiTaskStatusReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAiTaskStatusReq) ProtoMessage() {}

func (x *GetAiTaskStatusReq) ProtoReflect() protoreflect.Message {
	mi := &file_ai_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAiTaskStatusReq.ProtoReflect.Descriptor instead.
func (*GetAiTaskStatusReq) Descriptor() ([]byte, []int) {
	return file_ai_proto_rawDescGZIP(), []int{18}
}

func (x *GetAiTaskStatusReq) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

type GetAiTaskStatusRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        int32                  `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	Result        string                 `protobuf:"bytes,2,opt,name=result,proto3" json:"result,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAiTaskStatusRes) Reset() {
	*x = GetAiTaskStatusRes{}
	mi := &file_ai_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAiTaskStatusRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAiTaskStatusRes) ProtoMessage() {}

func (x *GetAiTaskStatusRes) ProtoReflect() protoreflect.Message {
	mi := &file_ai_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAiTaskStatusRes.ProtoReflect.Descriptor instead.
func (*GetAiTaskStatusRes) Descriptor() ([]byte, []int) {
	return file_ai_proto_rawDescGZIP(), []int{19}
}

func (x *GetAiTaskStatusRes) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *GetAiTaskStatusRes) GetResult() string {
	if x != nil {
		return x.Result
	}
	return ""
}

func (x *GetAiTaskStatusRes) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_ai_proto protoreflect.FileDescriptor

const file_ai_proto_rawDesc = "" +
	"\n" +
	"\bai.proto\x12\x02ai\"\x94\x02\n" +
	"\x17SubjectiveQuestionInput\x12\x1b\n" +
	"\trecord_id\x18\x01 \x01(\x03R\brecordId\x12\x1f\n" +
	"\vquestion_id\x18\x02 \x01(\x03R\n" +
	"questionId\x12)\n" +
	"\x10question_content\x18\x03 \x01(\tR\x0fquestionContent\x12'\n" +
	"\x0fstandard_answer\x18\x04 \x01(\tR\x0estandardAnswer\x12)\n" +
	"\x10knowledge_points\x18\x05 \x01(\tR\x0fknowledgePoints\x12\x1f\n" +
	"\vuser_answer\x18\x06 \x01(\tR\n" +
	"userAnswer\x12\x1b\n" +
	"\tmax_score\x18\a \x01(\tR\bmaxScore\"O\n" +
	"\x1aGradeSubjectiveQuestionReq\x121\n" +
	"\x05input\x18\x01 \x01(\v2\x1b.ai.SubjectiveQuestionInputR\x05input\"\x91\x01\n" +
	"\x1aGradeSubjectiveQuestionRes\x12\x1f\n" +
	"\vquestion_id\x18\x01 \x01(\x03R\n" +
	"questionId\x12\x14\n" +
	"\x05score\x18\x02 \x01(\tR\x05score\x12\x1d\n" +
	"\n" +
	"is_correct\x18\x03 \x01(\x05R\tisCorrect\x12\x1d\n" +
	"\n" +
	"ai_comment\x18\x04 \x01(\tR\taiComment\"\xa2\x01\n" +
	"\x16GradeExamSubjectiveReq\x12\x1b\n" +
	"\trecord_id\x18\x01 \x01(\x03R\brecordId\x12\x17\n" +
	"\aexam_id\x18\x02 \x01(\x03R\x06examId\x12\x17\n" +
	"\auser_id\x18\x03 \x01(\x03R\x06userId\x129\n" +
	"\tquestions\x18\x04 \x03(\v2\x1b.ai.SubjectiveQuestionInputR\tquestions\"R\n" +
	"\x16GradeExamSubjectiveRes\x128\n" +
	"\aresults\x18\x01 \x03(\v2\x1e.ai.GradeSubjectiveQuestionResR\aresults\"\x8c\x01\n" +
	"\x10EmbedMaterialReq\x12\x1f\n" +
	"\vmaterial_id\x18\x01 \x01(\x03R\n" +
	"materialId\x12\x1b\n" +
	"\tcourse_id\x18\x02 \x01(\x03R\bcourseId\x12\x14\n" +
	"\x05title\x18\x03 \x01(\tR\x05title\x12\x10\n" +
	"\x03url\x18\x04 \x01(\tR\x03url\x12\x12\n" +
	"\x04type\x18\x05 \x01(\x05R\x04type\".\n" +
	"\x10EmbedMaterialRes\x12\x1a\n" +
	"\baccepted\x18\x01 \x01(\bR\baccepted\"4\n" +
	"\x11GetEmbedStatusReq\x12\x1f\n" +
	"\vmaterial_id\x18\x01 \x01(\x03R\n" +
	"materialId\"J\n" +
	"\x11GetEmbedStatusRes\x12\x1b\n" +
	"\tai_status\x18\x01 \x01(\x05R\baiStatus\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\x9b\x01\n" +
	"\x0eAskQuestionReq\x12\x1b\n" +
	"\tcourse_id\x18\x01 \x01(\x03R\bcourseId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\x03R\x06userId\x12\x1a\n" +
	"\bquestion\x18\x03 \x01(\tR\bquestion\x12\x18\n" +
	"\ahistory\x18\x04 \x03(\tR\ahistory\x12\x1d\n" +
	"\n" +
	"session_id\x18\x05 \x01(\tR\tsessionId\"B\n" +
	"\x0eAskQuestionRes\x12\x16\n" +
	"\x06answer\x18\x01 \x01(\tR\x06answer\x12\x18\n" +
	"\asources\x18\x02 \x03(\tR\asources\"\x81\x01\n" +
	"\x14AskQuestionStreamRes\x12\x14\n" +
	"\x05delta\x18\x01 \x01(\tR\x05delta\x12\x18\n" +
	"\asources\x18\x02 \x03(\tR\asources\x12\x1a\n" +
	"\bfinished\x18\x03 \x01(\bR\bfinished\x12\x1d\n" +
	"\n" +
	"session_id\x18\x04 \x01(\tR\tsessionId\"n\n" +
	"\x1bGenerateCoursewareStreamRes\x12\x14\n" +
	"\x05delta\x18\x01 \x01(\tR\x05delta\x12\x1a\n" +
	"\bfinished\x18\x02 \x01(\bR\bfinished\x12\x1d\n" +
	"\n" +
	"session_id\x18\x03 \x01(\tR\tsessionId\"\xa8\x01\n" +
	"\x14GenerateQuestionsReq\x12\x1b\n" +
	"\tcourse_id\x18\x01 \x01(\x03R\bcourseId\x12)\n" +
	"\x10knowledge_points\x18\x02 \x01(\tR\x0fknowledgePoints\x12\x14\n" +
	"\x05count\x18\x03 \x01(\x05R\x05count\x12\x12\n" +
	"\x04type\x18\x04 \x01(\x05R\x04type\x12\x1e\n" +
	"\n" +
	"difficulty\x18\x05 \x01(\x05R\n" +
	"difficulty\"\xd6\x01\n" +
	"\x11GeneratedQuestion\x12\x18\n" +
	"\acontent\x18\x01 \x01(\tR\acontent\x12\x16\n" +
	"\x06answer\x18\x02 \x01(\tR\x06answer\x12\x1a\n" +
	"\banalysis\x18\x03 \x01(\tR\banalysis\x12)\n" +
	"\x10knowledge_points\x18\x04 \x01(\tR\x0fknowledgePoints\x12\x14\n" +
	"\x05score\x18\x05 \x01(\tR\x05score\x12\x12\n" +
	"\x04type\x18\x06 \x01(\x05R\x04type\x12\x1e\n" +
	"\n" +
	"difficulty\x18\a \x01(\x05R\n" +
	"difficulty\"q\n" +
	"\x18GenerateCourseOutlineReq\x12\x1b\n" +
	"\tcourse_id\x18\x01 \x01(\x03R\bcourseId\x12\x14\n" +
	"\x05topic\x18\x02 \x01(\tR\x05topic\x12\"\n" +
	"\frequirements\x18\x03 \x01(\tR\frequirements\"\x92\x01\n" +
	"\x15GenerateCoursewareReq\x12\x1d\n" +
	"\n" +
	"chapter_id\x18\x01 \x01(\x03R\tchapterId\x12\"\n" +
	"\frequirements\x18\x02 \x01(\tR\frequirements\x12\x17\n" +
	"\auser_id\x18\x03 \x01(\x03R\x06userId\x12\x1d\n" +
	"\n" +
	"session_id\x18\x04 \x01(\tR\tsessionId\"*\n" +
	"\x0fGenerateTaskRes\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\"-\n" +
	"\x12GetAiTaskStatusReq\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\"^\n" +
	"\x12GetAiTaskStatusRes\x12\x16\n" +
	"\x06status\x18\x01 \x01(\x05R\x06status\x12\x16\n" +
	"\x06result\x18\x02 \x01(\tR\x06result\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage2\xa0\x06\n" +
	"\bAiBridge\x12Y\n" +
	"\x17GradeSubjectiveQuestion\x12\x1e.ai.GradeSubjectiveQuestionReq\x1a\x1e.ai.GradeSubjectiveQuestionRes\x12M\n" +
	"\x13GradeExamSubjective\x12\x1a.ai.GradeExamSubjectiveReq\x1a\x1a.ai.GradeExamSubjectiveRes\x12;\n" +
	"\rEmbedMaterial\x12\x14.ai.EmbedMaterialReq\x1a\x14.ai.EmbedMaterialRes\x12>\n" +
	"\x0eGetEmbedStatus\x12\x15.ai.GetEmbedStatusReq\x1a\x15.ai.GetEmbedStatusRes\x125\n" +
	"\vAskQuestion\x12\x12.ai.AskQuestionReq\x1a\x12.ai.AskQuestionRes\x12C\n" +
	"\x11AskQuestionStream\x12\x12.ai.AskQuestionReq\x1a\x18.ai.AskQuestionStreamRes0\x01\x12B\n" +
	"\x11GenerateQuestions\x12\x18.ai.GenerateQuestionsReq\x1a\x13.ai.GenerateTaskRes\x12J\n" +
	"\x15GenerateCourseOutline\x12\x1c.ai.GenerateCourseOutlineReq\x1a\x13.ai.GenerateTaskRes\x12D\n" +
	"\x12GenerateCourseware\x12\x19.ai.GenerateCoursewareReq\x1a\x13.ai.GenerateTaskRes\x12X\n" +
	"\x18GenerateCoursewareStream\x12\x19.ai.GenerateCoursewareReq\x1a\x1f.ai.GenerateCoursewareStreamRes0\x01\x12A\n" +
	"\x0fGetAiTaskStatus\x12\x16.ai.GetAiTaskStatusReq\x1a\x16.ai.GetAiTaskStatusResB\x06Z\x04./pbb\x06proto3"

var (
	file_ai_proto_rawDescOnce sync.Once
	file_ai_proto_rawDescData []byte
)

func file_ai_proto_rawDescGZIP() []byte {
	file_ai_proto_rawDescOnce.Do(func() {
		file_ai_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_ai_proto_rawDesc), len(file_ai_proto_rawDesc)))
	})
	return file_ai_proto_rawDescData
}

var file_ai_proto_msgTypes = make([]protoimpl.MessageInfo, 20)
var file_ai_proto_goTypes = []any{
	(*SubjectiveQuestionInput)(nil),     // 0: ai.SubjectiveQuestionInput
	(*GradeSubjectiveQuestionReq)(nil),  // 1: ai.GradeSubjectiveQuestionReq
	(*GradeSubjectiveQuestionRes)(nil),  // 2: ai.GradeSubjectiveQuestionRes
	(*GradeExamSubjectiveReq)(nil),      // 3: ai.GradeExamSubjectiveReq
	(*GradeExamSubjectiveRes)(nil),      // 4: ai.GradeExamSubjectiveRes
	(*EmbedMaterialReq)(nil),            // 5: ai.EmbedMaterialReq
	(*EmbedMaterialRes)(nil),            // 6: ai.EmbedMaterialRes
	(*GetEmbedStatusReq)(nil),           // 7: ai.GetEmbedStatusReq
	(*GetEmbedStatusRes)(nil),           // 8: ai.GetEmbedStatusRes
	(*AskQuestionReq)(nil),              // 9: ai.AskQuestionReq
	(*AskQuestionRes)(nil),              // 10: ai.AskQuestionRes
	(*AskQuestionStreamRes)(nil),        // 11: ai.AskQuestionStreamRes
	(*GenerateCoursewareStreamRes)(nil), // 12: ai.GenerateCoursewareStreamRes
	(*GenerateQuestionsReq)(nil),        // 13: ai.GenerateQuestionsReq
	(*GeneratedQuestion)(nil),           // 14: ai.GeneratedQuestion
	(*GenerateCourseOutlineReq)(nil),    // 15: ai.GenerateCourseOutlineReq
	(*GenerateCoursewareReq)(nil),       // 16: ai.GenerateCoursewareReq
	(*GenerateTaskRes)(nil),             // 17: ai.GenerateTaskRes
	(*GetAiTaskStatusReq)(nil),          // 18: ai.GetAiTaskStatusReq
	(*GetAiTaskStatusRes)(nil),          // 19: ai.GetAiTaskStatusRes
}
var file_ai_proto_depIdxs = []int32{
	0,  // 0: ai.GradeSubjectiveQuestionReq.input:type_name -> ai.SubjectiveQuestionInput
	0,  // 1: ai.GradeExamSubjectiveReq.questions:type_name -> ai.SubjectiveQuestionInput
	2,  // 2: ai.GradeExamSubjectiveRes.results:type_name -> ai.GradeSubjectiveQuestionRes
	1,  // 3: ai.AiBridge.GradeSubjectiveQuestion:input_type -> ai.GradeSubjectiveQuestionReq
	3,  // 4: ai.AiBridge.GradeExamSubjective:input_type -> ai.GradeExamSubjectiveReq
	5,  // 5: ai.AiBridge.EmbedMaterial:input_type -> ai.EmbedMaterialReq
	7,  // 6: ai.AiBridge.GetEmbedStatus:input_type -> ai.GetEmbedStatusReq
	9,  // 7: ai.AiBridge.AskQuestion:input_type -> ai.AskQuestionReq
	9,  // 8: ai.AiBridge.AskQuestionStream:input_type -> ai.AskQuestionReq
	13, // 9: ai.AiBridge.GenerateQuestions:input_type -> ai.GenerateQuestionsReq
	15, // 10: ai.AiBridge.GenerateCourseOutline:input_type -> ai.GenerateCourseOutlineReq
	16, // 11: ai.AiBridge.GenerateCourseware:input_type -> ai.GenerateCoursewareReq
	16, // 12: ai.AiBridge.GenerateCoursewareStream:input_type -> ai.GenerateCoursewareReq
	18, // 13: ai.AiBridge.GetAiTaskStatus:input_type -> ai.GetAiTaskStatusReq
	2,  // 14: ai.AiBridge.GradeSubjectiveQuestion:output_type -> ai.GradeSubjectiveQuestionRes
	4,  // 15: ai.AiBridge.GradeExamSubjective:output_type -> ai.GradeExamSubjectiveRes
	6,  // 16: ai.AiBridge.EmbedMaterial:output_type -> ai.EmbedMaterialRes
	8,  // 17: ai.AiBridge.GetEmbedStatus:output_type -> ai.GetEmbedStatusRes
	10, // 18: ai.AiBridge.AskQuestion:output_type -> ai.AskQuestionRes
	11, // 19: ai.AiBridge.AskQuestionStream:output_type -> ai.AskQuestionStreamRes
	17, // 20: ai.AiBridge.GenerateQuestions:output_type -> ai.GenerateTaskRes
	17, // 21: ai.AiBridge.GenerateCourseOutline:output_type -> ai.GenerateTaskRes
	17, // 22: ai.AiBridge.GenerateCourseware:output_type -> ai.GenerateTaskRes
	12, // 23: ai.AiBridge.GenerateCoursewareStream:output_type -> ai.GenerateCoursewareStreamRes
	19, // 24: ai.AiBridge.GetAiTaskStatus:output_type -> ai.GetAiTaskStatusRes
	14, // [14:25] is the sub-list for method output_type
	3,  // [3:14] is the sub-list for method input_type
	3,  // [3:3] is the sub-list for extension type_name
	3,  // [3:3] is the sub-list for extension extendee
	0,  // [0:3] is the sub-list for field type_name
}

func init() { file_ai_proto_init() }
func file_ai_proto_init() {
	if File_ai_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_ai_proto_rawDesc), len(file_ai_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   20,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_ai_proto_goTypes,
		DependencyIndexes: file_ai_proto_depIdxs,
		MessageInfos:      file_ai_proto_msgTypes,
	}.Build()
	File_ai_proto = out.File
	file_ai_proto_goTypes = nil
	file_ai_proto_depIdxs = nil
}
