// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v3.19.4
// source: ai.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	AiBridge_GradeSubjectiveQuestion_FullMethodName  = "/ai.AiBridge/GradeSubjectiveQuestion"
	AiBridge_GradeExamSubjective_FullMethodName      = "/ai.AiBridge/GradeExamSubjective"
	AiBridge_EmbedMaterial_FullMethodName            = "/ai.AiBridge/EmbedMaterial"
	AiBridge_GetEmbedStatus_FullMethodName           = "/ai.AiBridge/GetEmbedStatus"
	AiBridge_AskQuestion_FullMethodName              = "/ai.AiBridge/AskQuestion"
	AiBridge_AskQuestionStream_FullMethodName        = "/ai.AiBridge/AskQuestionStream"
	AiBridge_GenerateQuestions_FullMethodName        = "/ai.AiBridge/GenerateQuestions"
	AiBridge_GenerateCourseOutline_FullMethodName    = "/ai.AiBridge/GenerateCourseOutline"
	AiBridge_GenerateCourseware_FullMethodName       = "/ai.AiBridge/GenerateCourseware"
	AiBridge_GenerateCoursewareStream_FullMethodName = "/ai.AiBridge/GenerateCoursewareStream"
	AiBridge_GetAiTaskStatus_FullMethodName          = "/ai.AiBridge/GetAiTaskStatus"
)

// AiBridgeClient is the client API for AiBridge service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AiBridgeClient interface {
	GradeSubjectiveQuestion(ctx context.Context, in *GradeSubjectiveQuestionReq, opts ...grpc.CallOption) (*GradeSubjectiveQuestionRes, error)
	GradeExamSubjective(ctx context.Context, in *GradeExamSubjectiveReq, opts ...grpc.CallOption) (*GradeExamSubjectiveRes, error)
	EmbedMaterial(ctx context.Context, in *EmbedMaterialReq, opts ...grpc.CallOption) (*EmbedMaterialRes, error)
	GetEmbedStatus(ctx context.Context, in *GetEmbedStatusReq, opts ...grpc.CallOption) (*GetEmbedStatusRes, error)
	AskQuestion(ctx context.Context, in *AskQuestionReq, opts ...grpc.CallOption) (*AskQuestionRes, error)
	AskQuestionStream(ctx context.Context, in *AskQuestionReq, opts ...grpc.CallOption) (grpc.ServerStreamingClient[AskQuestionStreamRes], error)
	GenerateQuestions(ctx context.Context, in *GenerateQuestionsReq, opts ...grpc.CallOption) (*GenerateTaskRes, error)
	GenerateCourseOutline(ctx context.Context, in *GenerateCourseOutlineReq, opts ...grpc.CallOption) (*GenerateTaskRes, error)
	GenerateCourseware(ctx context.Context, in *GenerateCoursewareReq, opts ...grpc.CallOption) (*GenerateTaskRes, error)
	GenerateCoursewareStream(ctx context.Context, in *GenerateCoursewareReq, opts ...grpc.CallOption) (grpc.ServerStreamingClient[GenerateCoursewareStreamRes], error)
	GetAiTaskStatus(ctx context.Context, in *GetAiTaskStatusReq, opts ...grpc.CallOption) (*GetAiTaskStatusRes, error)
}

type aiBridgeClient struct {
	cc grpc.ClientConnInterface
}

func NewAiBridgeClient(cc grpc.ClientConnInterface) AiBridgeClient {
	return &aiBridgeClient{cc}
}

func (c *aiBridgeClient) GradeSubjectiveQuestion(ctx context.Context, in *GradeSubjectiveQuestionReq, opts ...grpc.CallOption) (*GradeSubjectiveQuestionRes, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GradeSubjectiveQuestionRes)
	err := c.cc.Invoke(ctx, AiBridge_GradeSubjectiveQuestion_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aiBridgeClient) GradeExamSubjective(ctx context.Context, in *GradeExamSubjectiveReq, opts ...grpc.CallOption) (*GradeExamSubjectiveRes, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GradeExamSubjectiveRes)
	err := c.cc.Invoke(ctx, AiBridge_GradeExamSubjective_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aiBridgeClient) EmbedMaterial(ctx context.Context, in *EmbedMaterialReq, opts ...grpc.CallOption) (*EmbedMaterialRes, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EmbedMaterialRes)
	err := c.cc.Invoke(ctx, AiBridge_EmbedMaterial_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aiBridgeClient) GetEmbedStatus(ctx context.Context, in *GetEmbedStatusReq, opts ...grpc.CallOption) (*GetEmbedStatusRes, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetEmbedStatusRes)
	err := c.cc.Invoke(ctx, AiBridge_GetEmbedStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aiBridgeClient) AskQuestion(ctx context.Context, in *AskQuestionReq, opts ...grpc.CallOption) (*AskQuestionRes, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AskQuestionRes)
	err := c.cc.Invoke(ctx, AiBridge_AskQuestion_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aiBridgeClient) AskQuestionStream(ctx context.Context, in *AskQuestionReq, opts ...grpc.CallOption) (grpc.ServerStreamingClient[AskQuestionStreamRes], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &AiBridge_ServiceDesc.Streams[0], AiBridge_AskQuestionStream_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[AskQuestionReq, AskQuestionStreamRes]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type AiBridge_AskQuestionStreamClient = grpc.ServerStreamingClient[AskQuestionStreamRes]

func (c *aiBridgeClient) GenerateQuestions(ctx context.Context, in *GenerateQuestionsReq, opts ...grpc.CallOption) (*GenerateTaskRes, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GenerateTaskRes)
	err := c.cc.Invoke(ctx, AiBridge_GenerateQuestions_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aiBridgeClient) GenerateCourseOutline(ctx context.Context, in *GenerateCourseOutlineReq, opts ...grpc.CallOption) (*GenerateTaskRes, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GenerateTaskRes)
	err := c.cc.Invoke(ctx, AiBridge_GenerateCourseOutline_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aiBridgeClient) GenerateCourseware(ctx context.Context, in *GenerateCoursewareReq, opts ...grpc.CallOption) (*GenerateTaskRes, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GenerateTaskRes)
	err := c.cc.Invoke(ctx, AiBridge_GenerateCourseware_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aiBridgeClient) GenerateCoursewareStream(ctx context.Context, in *GenerateCoursewareReq, opts ...grpc.CallOption) (grpc.ServerStreamingClient[GenerateCoursewareStreamRes], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &AiBridge_ServiceDesc.Streams[1], AiBridge_GenerateCoursewareStream_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[GenerateCoursewareReq, GenerateCoursewareStreamRes]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type AiBridge_GenerateCoursewareStreamClient = grpc.ServerStreamingClient[GenerateCoursewareStreamRes]

func (c *aiBridgeClient) GetAiTaskStatus(ctx context.Context, in *GetAiTaskStatusReq, opts ...grpc.CallOption) (*GetAiTaskStatusRes, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetAiTaskStatusRes)
	err := c.cc.Invoke(ctx, AiBridge_GetAiTaskStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AiBridgeServer is the server API for AiBridge service.
// All implementations must embed UnimplementedAiBridgeServer
// for forward compatibility.
type AiBridgeServer interface {
	GradeSubjectiveQuestion(context.Context, *GradeSubjectiveQuestionReq) (*GradeSubjectiveQuestionRes, error)
	GradeExamSubjective(context.Context, *GradeExamSubjectiveReq) (*GradeExamSubjectiveRes, error)
	EmbedMaterial(context.Context, *EmbedMaterialReq) (*EmbedMaterialRes, error)
	GetEmbedStatus(context.Context, *GetEmbedStatusReq) (*GetEmbedStatusRes, error)
	AskQuestion(context.Context, *AskQuestionReq) (*AskQuestionRes, error)
	AskQuestionStream(*AskQuestionReq, grpc.ServerStreamingServer[AskQuestionStreamRes]) error
	GenerateQuestions(context.Context, *GenerateQuestionsReq) (*GenerateTaskRes, error)
	GenerateCourseOutline(context.Context, *GenerateCourseOutlineReq) (*GenerateTaskRes, error)
	GenerateCourseware(context.Context, *GenerateCoursewareReq) (*GenerateTaskRes, error)
	GenerateCoursewareStream(*GenerateCoursewareReq, grpc.ServerStreamingServer[GenerateCoursewareStreamRes]) error
	GetAiTaskStatus(context.Context, *GetAiTaskStatusReq) (*GetAiTaskStatusRes, error)
	mustEmbedUnimplementedAiBridgeServer()
}

// UnimplementedAiBridgeServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAiBridgeServer struct{}

func (UnimplementedAiBridgeServer) GradeSubjectiveQuestion(context.Context, *GradeSubjectiveQuestionReq) (*GradeSubjectiveQuestionRes, error) {
	return nil, status.Error(codes.Unimplemented, "method GradeSubjectiveQuestion not implemented")
}
func (UnimplementedAiBridgeServer) GradeExamSubjective(context.Context, *GradeExamSubjectiveReq) (*GradeExamSubjectiveRes, error) {
	return nil, status.Error(codes.Unimplemented, "method GradeExamSubjective not implemented")
}
func (UnimplementedAiBridgeServer) EmbedMaterial(context.Context, *EmbedMaterialReq) (*EmbedMaterialRes, error) {
	return nil, status.Error(codes.Unimplemented, "method EmbedMaterial not implemented")
}
func (UnimplementedAiBridgeServer) GetEmbedStatus(context.Context, *GetEmbedStatusReq) (*GetEmbedStatusRes, error) {
	return nil, status.Error(codes.Unimplemented, "method GetEmbedStatus not implemented")
}
func (UnimplementedAiBridgeServer) AskQuestion(context.Context, *AskQuestionReq) (*AskQuestionRes, error) {
	return nil, status.Error(codes.Unimplemented, "method AskQuestion not implemented")
}
func (UnimplementedAiBridgeServer) AskQuestionStream(*AskQuestionReq, grpc.ServerStreamingServer[AskQuestionStreamRes]) error {
	return status.Error(codes.Unimplemented, "method AskQuestionStream not implemented")
}
func (UnimplementedAiBridgeServer) GenerateQuestions(context.Context, *GenerateQuestionsReq) (*GenerateTaskRes, error) {
	return nil, status.Error(codes.Unimplemented, "method GenerateQuestions not implemented")
}
func (UnimplementedAiBridgeServer) GenerateCourseOutline(context.Context, *GenerateCourseOutlineReq) (*GenerateTaskRes, error) {
	return nil, status.Error(codes.Unimplemented, "method GenerateCourseOutline not implemented")
}
func (UnimplementedAiBridgeServer) GenerateCourseware(context.Context, *GenerateCoursewareReq) (*GenerateTaskRes, error) {
	return nil, status.Error(codes.Unimplemented, "method GenerateCourseware not implemented")
}
func (UnimplementedAiBridgeServer) GenerateCoursewareStream(*GenerateCoursewareReq, grpc.ServerStreamingServer[GenerateCoursewareStreamRes]) error {
	return status.Error(codes.Unimplemented, "method GenerateCoursewareStream not implemented")
}
func (UnimplementedAiBridgeServer) GetAiTaskStatus(context.Context, *GetAiTaskStatusReq) (*GetAiTaskStatusRes, error) {
	return nil, status.Error(codes.Unimplemented, "method GetAiTaskStatus not implemented")
}
func (UnimplementedAiBridgeServer) mustEmbedUnimplementedAiBridgeServer() {}
func (UnimplementedAiBridgeServer) testEmbeddedByValue()                  {}

// UnsafeAiBridgeServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AiBridgeServer will
// result in compilation errors.
type UnsafeAiBridgeServer interface {
	mustEmbedUnimplementedAiBridgeServer()
}

func RegisterAiBridgeServer(s grpc.ServiceRegistrar, srv AiBridgeServer) {
	// If the following call panics, it indicates UnimplementedAiBridgeServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AiBridge_ServiceDesc, srv)
}

func _AiBridge_GradeSubjectiveQuestion_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GradeSubjectiveQuestionReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AiBridgeServer).GradeSubjectiveQuestion(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AiBridge_GradeSubjectiveQuestion_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AiBridgeServer).GradeSubjectiveQuestion(ctx, req.(*GradeSubjectiveQuestionReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _AiBridge_GradeExamSubjective_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GradeExamSubjectiveReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AiBridgeServer).GradeExamSubjective(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AiBridge_GradeExamSubjective_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AiBridgeServer).GradeExamSubjective(ctx, req.(*GradeExamSubjectiveReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _AiBridge_EmbedMaterial_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EmbedMaterialReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AiBridgeServer).EmbedMaterial(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AiBridge_EmbedMaterial_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AiBridgeServer).EmbedMaterial(ctx, req.(*EmbedMaterialReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _AiBridge_GetEmbedStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetEmbedStatusReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AiBridgeServer).GetEmbedStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AiBridge_GetEmbedStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AiBridgeServer).GetEmbedStatus(ctx, req.(*GetEmbedStatusReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _AiBridge_AskQuestion_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AskQuestionReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AiBridgeServer).AskQuestion(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AiBridge_AskQuestion_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AiBridgeServer).AskQuestion(ctx, req.(*AskQuestionReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _AiBridge_AskQuestionStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(AskQuestionReq)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(AiBridgeServer).AskQuestionStream(m, &grpc.GenericServerStream[AskQuestionReq, AskQuestionStreamRes]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type AiBridge_AskQuestionStreamServer = grpc.ServerStreamingServer[AskQuestionStreamRes]

func _AiBridge_GenerateQuestions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GenerateQuestionsReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AiBridgeServer).GenerateQuestions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AiBridge_GenerateQuestions_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AiBridgeServer).GenerateQuestions(ctx, req.(*GenerateQuestionsReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _AiBridge_GenerateCourseOutline_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GenerateCourseOutlineReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AiBridgeServer).GenerateCourseOutline(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AiBridge_GenerateCourseOutline_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AiBridgeServer).GenerateCourseOutline(ctx, req.(*GenerateCourseOutlineReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _AiBridge_GenerateCourseware_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GenerateCoursewareReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AiBridgeServer).GenerateCourseware(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AiBridge_GenerateCourseware_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AiBridgeServer).GenerateCourseware(ctx, req.(*GenerateCoursewareReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _AiBridge_GenerateCoursewareStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(GenerateCoursewareReq)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(AiBridgeServer).GenerateCoursewareStream(m, &grpc.GenericServerStream[GenerateCoursewareReq, GenerateCoursewareStreamRes]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type AiBridge_GenerateCoursewareStreamServer = grpc.ServerStreamingServer[GenerateCoursewareStreamRes]

func _AiBridge_GetAiTaskStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAiTaskStatusReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AiBridgeServer).GetAiTaskStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AiBridge_GetAiTaskStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AiBridgeServer).GetAiTaskStatus(ctx, req.(*GetAiTaskStatusReq))
	}
	return interceptor(ctx, in, info, handler)
}

// AiBridge_ServiceDesc is the grpc.ServiceDesc for AiBridge service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AiBridge_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "ai.AiBridge",
	HandlerType: (*AiBridgeServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GradeSubjectiveQuestion",
			Handler:    _AiBridge_GradeSubjectiveQuestion_Handler,
		},
		{
			MethodName: "GradeExamSubjective",
			Handler:    _AiBridge_GradeExamSubjective_Handler,
		},
		{
			MethodName: "EmbedMaterial",
			Handler:    _AiBridge_EmbedMaterial_Handler,
		},
		{
			MethodName: "GetEmbedStatus",
			Handler:    _AiBridge_GetEmbedStatus_Handler,
		},
		{
			MethodName: "AskQuestion",
			Handler:    _AiBridge_AskQuestion_Handler,
		},
		{
			MethodName: "GenerateQuestions",
			Handler:    _AiBridge_GenerateQuestions_Handler,
		},
		{
			MethodName: "GenerateCourseOutline",
			Handler:    _AiBridge_GenerateCourseOutline_Handler,
		},
		{
			MethodName: "GenerateCourseware",
			Handler:    _AiBridge_GenerateCourseware_Handler,
		},
		{
			MethodName: "GetAiTaskStatus",
			Handler:    _AiBridge_GetAiTaskStatus_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "AskQuestionStream",
			Handler:       _AiBridge_AskQuestionStream_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "GenerateCoursewareStream",
			Handler:       _AiBridge_GenerateCoursewareStream_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "ai.proto",
}
