// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2

package handler

import (
	"net/http"

	ai "teaching-backend/application/applet/api/internal/handler/ai"
	chapter "teaching-backend/application/applet/api/internal/handler/chapter"
	course "teaching-backend/application/applet/api/internal/handler/course"
	enrollment "teaching-backend/application/applet/api/internal/handler/enrollment"
	exam "teaching-backend/application/applet/api/internal/handler/exam"
	examRecord "teaching-backend/application/applet/api/internal/handler/examRecord"
	material "teaching-backend/application/applet/api/internal/handler/material"
	progress "teaching-backend/application/applet/api/internal/handler/progress"
	question "teaching-backend/application/applet/api/internal/handler/question"
	resource "teaching-backend/application/applet/api/internal/handler/resource"
	teacher "teaching-backend/application/applet/api/internal/handler/teacher"
	user "teaching-backend/application/applet/api/internal/handler/user"
	"teaching-backend/application/applet/api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				// 智能助教问答 (基于课件RAG)
				Method:  http.MethodPost,
				Path:    "/ai/ask",
				Handler: ai.AskQuestionHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
		rest.WithPrefix("/v1"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				// 章节列表
				Method:  http.MethodGet,
				Path:    "/chapter/list",
				Handler: chapter.ChapterListHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
		rest.WithPrefix("/v1"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				// 课程详情
				Method:  http.MethodGet,
				Path:    "/course/detail/:id",
				Handler: course.CourseDetailHandler(serverCtx),
			},
			{
				// 课程列表
				Method:  http.MethodGet,
				Path:    "/course/list",
				Handler: course.CourseListHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
		rest.WithPrefix("/v1"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				// 检查是否已选课
				Method:  http.MethodGet,
				Path:    "/enrollment/check",
				Handler: enrollment.CheckEnrollmentHandler(serverCtx),
			},
			{
				// 学生退课
				Method:  http.MethodPost,
				Path:    "/enrollment/drop",
				Handler: enrollment.DropCourseHandler(serverCtx),
			},
			{
				// 学生选课
				Method:  http.MethodPost,
				Path:    "/enrollment/enroll",
				Handler: enrollment.EnrollCourseHandler(serverCtx),
			},
			{
				// 我的选课列表
				Method:  http.MethodGet,
				Path:    "/enrollment/list",
				Handler: enrollment.MyEnrollmentListHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
		rest.WithPrefix("/v1"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				// 试卷详情
				Method:  http.MethodGet,
				Path:    "/exam/detail/:id",
				Handler: exam.ExamDetailHandler(serverCtx),
			},
			{
				// 试卷列表
				Method:  http.MethodGet,
				Path:    "/exam/list",
				Handler: exam.ExamListHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
		rest.WithPrefix("/v1"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				// 获取答题明细
				Method:  http.MethodGet,
				Path:    "/exam-record/answers/:record_id",
				Handler: examRecord.GetUserAnswersHandler(serverCtx),
			},
			{
				// 获取考试结果
				Method:  http.MethodGet,
				Path:    "/exam-record/result/:record_id",
				Handler: examRecord.GetExamResultHandler(serverCtx),
			},
			{
				// 考试过程心跳与答案快照同步
				Method:  http.MethodPost,
				Path:    "/exam-record/snapshot",
				Handler: examRecord.SaveAnswerSnapshotHandler(serverCtx),
			},
			{
				// 开始考试
				Method:  http.MethodPost,
				Path:    "/exam-record/start",
				Handler: examRecord.StartExamHandler(serverCtx),
			},
			{
				// 提交答卷
				Method:  http.MethodPost,
				Path:    "/exam-record/submit",
				Handler: examRecord.SubmitExamHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
		rest.WithPrefix("/v1"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				// 课件列表
				Method:  http.MethodGet,
				Path:    "/material/list",
				Handler: material.MaterialListHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
		rest.WithPrefix("/v1"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				// 获取学习进度
				Method:  http.MethodGet,
				Path:    "/progress/get",
				Handler: progress.GetStudyProgressHandler(serverCtx),
			},
			{
				// 更新学习进度
				Method:  http.MethodPost,
				Path:    "/progress/update",
				Handler: progress.UpdateStudyProgressHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
		rest.WithPrefix("/v1"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				// 题目详情
				Method:  http.MethodGet,
				Path:    "/question/detail/:id",
				Handler: question.QuestionDetailHandler(serverCtx),
			},
			{
				// 题目列表
				Method:  http.MethodGet,
				Path:    "/question/list",
				Handler: question.QuestionListHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
		rest.WithPrefix("/v1"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				// 获取 OSS/MinIO 直传签名
				Method:  http.MethodGet,
				Path:    "/resource/upload-token",
				Handler: resource.GetUploadTokenHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
		rest.WithPrefix("/v1"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.CheckTeacherRole},
			[]rest.Route{
				{
					// AI 生成章节课件 - 异步
					Method:  http.MethodPost,
					Path:    "/ai/generate-courseware",
					Handler: teacher.GenerateCoursewareHandler(serverCtx),
				},
				{
					// AI 生成课件大纲 - 异步
					Method:  http.MethodPost,
					Path:    "/ai/generate-outline",
					Handler: teacher.GenerateCourseOutlineHandler(serverCtx),
				},
				{
					// AI 智能出题 (基于知识点) - 异步
					Method:  http.MethodPost,
					Path:    "/ai/generate-questions",
					Handler: teacher.GenerateQuestionsHandler(serverCtx),
				},
				{
					// 查询 AI 异步生成任务状态
					Method:  http.MethodGet,
					Path:    "/ai/task/status/:task_id",
					Handler: teacher.GetAiTaskStatusHandler(serverCtx),
				},
				{
					// 创建章节
					Method:  http.MethodPost,
					Path:    "/chapter/create",
					Handler: teacher.CreateChapterHandler(serverCtx),
				},
				{
					// 删除章节
					Method:  http.MethodDelete,
					Path:    "/chapter/delete/:id",
					Handler: teacher.DeleteChapterHandler(serverCtx),
				},
				{
					// 更新章节
					Method:  http.MethodPut,
					Path:    "/chapter/update/:id",
					Handler: teacher.UpdateChapterHandler(serverCtx),
				},
				{
					// 创建课程(教师)
					Method:  http.MethodPost,
					Path:    "/course/create",
					Handler: teacher.CreateCourseHandler(serverCtx),
				},
				{
					// 删除课程(教师)
					Method:  http.MethodDelete,
					Path:    "/course/delete/:id",
					Handler: teacher.DeleteCourseHandler(serverCtx),
				},
				{
					// 查看课程已选学生列表(教师)
					Method:  http.MethodGet,
					Path:    "/course/students",
					Handler: teacher.CourseStudentsHandler(serverCtx),
				},
				{
					// 更新课程(教师)
					Method:  http.MethodPut,
					Path:    "/course/update/:id",
					Handler: teacher.UpdateCourseHandler(serverCtx),
				},
				{
					// 创建试卷(教师)
					Method:  http.MethodPost,
					Path:    "/exam/create",
					Handler: teacher.CreateExamHandler(serverCtx),
				},
				{
					// 删除试卷(教师)
					Method:  http.MethodDelete,
					Path:    "/exam/delete/:id",
					Handler: teacher.DeleteExamHandler(serverCtx),
				},
				{
					// 添加题目到试卷
					Method:  http.MethodPost,
					Path:    "/exam/question/add",
					Handler: teacher.AddExamQuestionHandler(serverCtx),
				},
				{
					// 从试卷移除题目
					Method:  http.MethodPost,
					Path:    "/exam/question/remove",
					Handler: teacher.RemoveExamQuestionHandler(serverCtx),
				},
				{
					// 更新试卷(教师)
					Method:  http.MethodPut,
					Path:    "/exam/update/:id",
					Handler: teacher.UpdateExamHandler(serverCtx),
				},
				{
					// 上传课件(绑定资源)
					Method:  http.MethodPost,
					Path:    "/material/create",
					Handler: teacher.CreateMaterialHandler(serverCtx),
				},
				{
					// 删除课件
					Method:  http.MethodDelete,
					Path:    "/material/delete/:id",
					Handler: teacher.DeleteMaterialHandler(serverCtx),
				},
				{
					// 创建题目(教师)
					Method:  http.MethodPost,
					Path:    "/question/create",
					Handler: teacher.CreateQuestionHandler(serverCtx),
				},
				{
					// 删除题目(教师)
					Method:  http.MethodDelete,
					Path:    "/question/delete/:id",
					Handler: teacher.DeleteQuestionHandler(serverCtx),
				},
				{
					// 更新题目(教师)
					Method:  http.MethodPut,
					Path:    "/question/update/:id",
					Handler: teacher.UpdateQuestionHandler(serverCtx),
				},
			}...,
		),
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
		rest.WithPrefix("/v1"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				// 用户登录
				Method:  http.MethodPost,
				Path:    "/user/login",
				Handler: user.LoginHandler(serverCtx),
			},
			{
				// 用户注册
				Method:  http.MethodPost,
				Path:    "/user/register",
				Handler: user.RegisterHandler(serverCtx),
			},
			{
				// 发送验证码
				Method:  http.MethodPost,
				Path:    "/user/verify-code",
				Handler: user.SendVerifyCodeHandler(serverCtx),
			},
		},
		rest.WithPrefix("/v1"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				// 获取当前用户信息
				Method:  http.MethodGet,
				Path:    "/user/info",
				Handler: user.UserInfoHandler(serverCtx),
			},
			{
				// 编辑个人信息
				Method:  http.MethodPut,
				Path:    "/user/info",
				Handler: user.UpdateUserInfoHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
		rest.WithPrefix("/v1"),
	)
}
