// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.19.4
// source: course.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateCourseReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Title         string                 `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	Cover         string                 `protobuf:"bytes,2,opt,name=cover,proto3" json:"cover,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	TeacherId     int64                  `protobuf:"varint,4,opt,name=teacher_id,json=teacherId,proto3" json:"teacher_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateCourseReq) Reset() {
	*x = CreateCourseReq{}
	mi := &file_course_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateCourseReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateCourseReq) ProtoMessage() {}

func (x *CreateCourseReq) ProtoReflect() protoreflect.Message {
	mi := &file_course_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateCourseReq.ProtoReflect.Descriptor instead.
func (*CreateCourseReq) Descriptor() ([]byte, []int) {
	return file_course_proto_rawDescGZIP(), []int{0}
}

func (x *CreateCourseReq) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *CreateCourseReq) GetCover() string {
	if x != nil {
		return x.Cover
	}
	return ""
}

func (x *CreateCourseReq) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *CreateCourseReq) GetTeacherId() int64 {
	if x != nil {
		return x.TeacherId
	}
	return 0
}

type CreateCourseRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateCourseRes) Reset() {
	*x = CreateCourseRes{}
	mi := &file_course_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateCourseRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateCourseRes) ProtoMessage() {}

func (x *CreateCourseRes) ProtoReflect() protoreflect.Message {
	mi := &file_course_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateCourseRes.ProtoReflect.Descriptor instead.
func (*CreateCourseRes) Descriptor() ([]byte, []int) {
	return file_course_proto_rawDescGZIP(), []int{1}
}

func (x *CreateCourseRes) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type CourseListReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TeacherId     int64                  `protobuf:"varint,1,opt,name=teacher_id,json=teacherId,proto3" json:"teacher_id,omitempty"` // 为0则查全部
	Page          int64                  `protobuf:"varint,2,opt,name=page,proto3" json:"page,omitempty"`
	Size          int64                  `protobuf:"varint,3,opt,name=size,proto3" json:"size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CourseListReq) Reset() {
	*x = CourseListReq{}
	mi := &file_course_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CourseListReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CourseListReq) ProtoMessage() {}

func (x *CourseListReq) ProtoReflect() protoreflect.Message {
	mi := &file_course_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CourseListReq.ProtoReflect.Descriptor instead.
func (*CourseListReq) Descriptor() ([]byte, []int) {
	return file_course_proto_rawDescGZIP(), []int{2}
}

func (x *CourseListReq) GetTeacherId() int64 {
	if x != nil {
		return x.TeacherId
	}
	return 0
}

func (x *CourseListReq) GetPage() int64 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *CourseListReq) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

type CourseItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Cover         string                 `protobuf:"bytes,3,opt,name=cover,proto3" json:"cover,omitempty"`
	Description   string                 `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	TeacherId     int64                  `protobuf:"varint,5,opt,name=teacher_id,json=teacherId,proto3" json:"teacher_id,omitempty"`
	Status        int32                  `protobuf:"varint,6,opt,name=status,proto3" json:"status,omitempty"`
	CreateTime    int64                  `protobuf:"varint,7,opt,name=create_time,json=createTime,proto3" json:"create_time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CourseItem) Reset() {
	*x = CourseItem{}
	mi := &file_course_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CourseItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CourseItem) ProtoMessage() {}

func (x *CourseItem) ProtoReflect() protoreflect.Message {
	mi := &file_course_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CourseItem.ProtoReflect.Descriptor instead.
func (*CourseItem) Descriptor() ([]byte, []int) {
	return file_course_proto_rawDescGZIP(), []int{3}
}

func (x *CourseItem) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *CourseItem) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *CourseItem) GetCover() string {
	if x != nil {
		return x.Cover
	}
	return ""
}

func (x *CourseItem) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *CourseItem) GetTeacherId() int64 {
	if x != nil {
		return x.TeacherId
	}
	return 0
}

func (x *CourseItem) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *CourseItem) GetCreateTime() int64 {
	if x != nil {
		return x.CreateTime
	}
	return 0
}

type CourseListRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	List          []*CourseItem          `protobuf:"bytes,1,rep,name=list,proto3" json:"list,omitempty"`
	Total         int64                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CourseListRes) Reset() {
	*x = CourseListRes{}
	mi := &file_course_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CourseListRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CourseListRes) ProtoMessage() {}

func (x *CourseListRes) ProtoReflect() protoreflect.Message {
	mi := &file_course_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CourseListRes.ProtoReflect.Descriptor instead.
func (*CourseListRes) Descriptor() ([]byte, []int) {
	return file_course_proto_rawDescGZIP(), []int{4}
}

func (x *CourseListRes) GetList() []*CourseItem {
	if x != nil {
		return x.List
	}
	return nil
}

func (x *CourseListRes) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

type CourseDetailReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CourseDetailReq) Reset() {
	*x = CourseDetailReq{}
	mi := &file_course_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CourseDetailReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CourseDetailReq) ProtoMessage() {}

func (x *CourseDetailReq) ProtoReflect() protoreflect.Message {
	mi := &file_course_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CourseDetailReq.ProtoReflect.Descriptor instead.
func (*CourseDetailReq) Descriptor() ([]byte, []int) {
	return file_course_proto_rawDescGZIP(), []int{5}
}

func (x *CourseDetailReq) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type CourseDetailRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Course        *CourseItem            `protobuf:"bytes,1,opt,name=course,proto3" json:"course,omitempty"`
	Chapters      []*ChapterItem         `protobuf:"bytes,2,rep,name=chapters,proto3" json:"chapters,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CourseDetailRes) Reset() {
	*x = CourseDetailRes{}
	mi := &file_course_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CourseDetailRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CourseDetailRes) ProtoMessage() {}

func (x *CourseDetailRes) ProtoReflect() protoreflect.Message {
	mi := &file_course_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CourseDetailRes.ProtoReflect.Descriptor instead.
func (*CourseDetailRes) Descriptor() ([]byte, []int) {
	return file_course_proto_rawDescGZIP(), []int{6}
}

func (x *CourseDetailRes) GetCourse() *CourseItem {
	if x != nil {
		return x.Course
	}
	return nil
}

func (x *CourseDetailRes) GetChapters() []*ChapterItem {
	if x != nil {
		return x.Chapters
	}
	return nil
}

type UpdateCourseReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Cover         string                 `protobuf:"bytes,3,opt,name=cover,proto3" json:"cover,omitempty"`
	Description   string                 `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	Status        int32                  `protobuf:"varint,5,opt,name=status,proto3" json:"status,omitempty"`
	OperatorId    int64                  `protobuf:"varint,6,opt,name=operator_id,json=operatorId,proto3" json:"operator_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateCourseReq) Reset() {
	*x = UpdateCourseReq{}
	mi := &file_course_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateCourseReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateCourseReq) ProtoMessage() {}

func (x *UpdateCourseReq) ProtoReflect() protoreflect.Message {
	mi := &file_course_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateCourseReq.ProtoReflect.Descriptor instead.
func (*UpdateCourseReq) Descriptor() ([]byte, []int) {
	return file_course_proto_rawDescGZIP(), []int{7}
}

func (x *UpdateCourseReq) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UpdateCourseReq) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *UpdateCourseReq) GetCover() string {
	if x != nil {
		return x.Cover
	}
	return ""
}

func (x *UpdateCourseReq) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *UpdateCourseReq) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *UpdateCourseReq) GetOperatorId() int64 {
	if x != nil {
		return x.OperatorId
	}
	return 0
}

type UpdateCourseRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateCourseRes) Reset() {
	*x = UpdateCourseRes{}
	mi := &file_course_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateCourseRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateCourseRes) ProtoMessage() {}

func (x *UpdateCourseRes) ProtoReflect() protoreflect.Message {
	mi := &file_course_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateCourseRes.ProtoReflect.Descriptor instead.
func (*UpdateCourseRes) Descriptor() ([]byte, []int) {
	return file_course_proto_rawDescGZIP(), []int{8}
}

type DeleteCourseReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	OperatorId    int64                  `protobuf:"varint,2,opt,name=operator_id,json=operatorId,proto3" json:"operator_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteCourseReq) Reset() {
	*x = DeleteCourseReq{}
	mi := &file_course_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteCourseReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteCourseReq) ProtoMessage() {}

func (x *DeleteCourseReq) ProtoReflect() protoreflect.Message {
	mi := &file_course_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteCourseReq.ProtoReflect.Descriptor instead.
func (*DeleteCourseReq) Descriptor() ([]byte, []int) {
	return file_course_proto_rawDescGZIP(), []int{9}
}

func (x *DeleteCourseReq) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *DeleteCourseReq) GetOperatorId() int64 {
	if x != nil {
		return x.OperatorId
	}
	return 0
}

type DeleteCourseRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteCourseRes) Reset() {
	*x = DeleteCourseRes{}
	mi := &file_course_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteCourseRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteCourseRes) ProtoMessage() {}

func (x *DeleteCourseRes) ProtoReflect() protoreflect.Message {
	mi := &file_course_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteCourseRes.ProtoReflect.Descriptor instead.
func (*DeleteCourseRes) Descriptor() ([]byte, []int) {
	return file_course_proto_rawDescGZIP(), []int{10}
}

type CreateChapterReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CourseId      int64                  `protobuf:"varint,1,opt,name=course_id,json=courseId,proto3" json:"course_id,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Sort          int32                  `protobuf:"varint,3,opt,name=sort,proto3" json:"sort,omitempty"`
	OperatorId    int64                  `protobuf:"varint,4,opt,name=operator_id,json=operatorId,proto3" json:"operator_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateChapterReq) Reset() {
	*x = CreateChapterReq{}
	mi := &file_course_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateChapterReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateChapterReq) ProtoMessage() {}

func (x *CreateChapterReq) ProtoReflect() protoreflect.Message {
	mi := &file_course_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateChapterReq.ProtoReflect.Descriptor instead.
func (*CreateChapterReq) Descriptor() ([]byte, []int) {
	return file_course_proto_rawDescGZIP(), []int{11}
}

func (x *CreateChapterReq) GetCourseId() int64 {
	if x != nil {
		return x.CourseId
	}
	return 0
}

func (x *CreateChapterReq) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *CreateChapterReq) GetSort() int32 {
	if x != nil {
		return x.Sort
	}
	return 0
}

func (x *CreateChapterReq) GetOperatorId() int64 {
	if x != nil {
		return x.OperatorId
	}
	return 0
}

type CreateChapterRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateChapterRes) Reset() {
	*x = CreateChapterRes{}
	mi := &file_course_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateChapterRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateChapterRes) ProtoMessage() {}

func (x *CreateChapterRes) ProtoReflect() protoreflect.Message {
	mi := &file_course_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateChapterRes.ProtoReflect.Descriptor instead.
func (*CreateChapterRes) Descriptor() ([]byte, []int) {
	return file_course_proto_rawDescGZIP(), []int{12}
}

func (x *CreateChapterRes) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type ChapterListReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CourseId      int64                  `protobuf:"varint,1,opt,name=course_id,json=courseId,proto3" json:"course_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChapterListReq) Reset() {
	*x = ChapterListReq{}
	mi := &file_course_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChapterListReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChapterListReq) ProtoMessage() {}

func (x *ChapterListReq) ProtoReflect() protoreflect.Message {
	mi := &file_course_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChapterListReq.ProtoReflect.Descriptor instead.
func (*ChapterListReq) Descriptor() ([]byte, []int) {
	return file_course_proto_rawDescGZIP(), []int{13}
}

func (x *ChapterListReq) GetCourseId() int64 {
	if x != nil {
		return x.CourseId
	}
	return 0
}

type ChapterItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	CourseId      int64                  `protobuf:"varint,2,opt,name=course_id,json=courseId,proto3" json:"course_id,omitempty"`
	Title         string                 `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	Sort          int32                  `protobuf:"varint,4,opt,name=sort,proto3" json:"sort,omitempty"`
	Materials     []*MaterialItem        `protobuf:"bytes,5,rep,name=materials,proto3" json:"materials,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChapterItem) Reset() {
	*x = ChapterItem{}
	mi := &file_course_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChapterItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChapterItem) ProtoMessage() {}

func (x *ChapterItem) ProtoReflect() protoreflect.Message {
	mi := &file_course_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChapterItem.ProtoReflect.Descriptor instead.
func (*ChapterItem) Descriptor() ([]byte, []int) {
	return file_course_proto_rawDescGZIP(), []int{14}
}

func (x *ChapterItem) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ChapterItem) GetCourseId() int64 {
	if x != nil {
		return x.CourseId
	}
	return 0
}

func (x *ChapterItem) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *ChapterItem) GetSort() int32 {
	if x != nil {
		return x.Sort
	}
	return 0
}

func (x *ChapterItem) GetMaterials() []*MaterialItem {
	if x != nil {
		return x.Materials
	}
	return nil
}

type ChapterListRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	List          []*ChapterItem         `protobuf:"bytes,1,rep,name=list,proto3" json:"list,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChapterListRes) Reset() {
	*x = ChapterListRes{}
	mi := &file_course_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChapterListRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChapterListRes) ProtoMessage() {}

func (x *ChapterListRes) ProtoReflect() protoreflect.Message {
	mi := &file_course_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChapterListRes.ProtoReflect.Descriptor instead.
func (*ChapterListRes) Descriptor() ([]byte, []int) {
	return file_course_proto_rawDescGZIP(), []int{15}
}

func (x *ChapterListRes) GetList() []*ChapterItem {
	if x != nil {
		return x.List
	}
	return nil
}

type UpdateChapterReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Sort          int32                  `protobuf:"varint,3,opt,name=sort,proto3" json:"sort,omitempty"`
	OperatorId    int64                  `protobuf:"varint,4,opt,name=operator_id,json=operatorId,proto3" json:"operator_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateChapterReq) Reset() {
	*x = UpdateChapterReq{}
	mi := &file_course_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateChapterReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateChapterReq) ProtoMessage() {}

func (x *UpdateChapterReq) ProtoReflect() protoreflect.Message {
	mi := &file_course_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateChapterReq.ProtoReflect.Descriptor instead.
func (*UpdateChapterReq) Descriptor() ([]byte, []int) {
	return file_course_proto_rawDescGZIP(), []int{16}
}

func (x *UpdateChapterReq) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UpdateChapterReq) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *UpdateChapterReq) GetSort() int32 {
	if x != nil {
		return x.Sort
	}
	return 0
}

func (x *UpdateChapterReq) GetOperatorId() int64 {
	if x != nil {
		return x.OperatorId
	}
	return 0
}

type UpdateChapterRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateChapterRes) Reset() {
	*x = UpdateChapterRes{}
	mi := &file_course_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateChapterRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateChapterRes) ProtoMessage() {}

func (x *UpdateChapterRes) ProtoReflect() protoreflect.Message {
	mi := &file_course_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateChapterRes.ProtoReflect.Descriptor instead.
func (*UpdateChapterRes) Descriptor() ([]byte, []int) {
	return file_course_proto_rawDescGZIP(), []int{17}
}

type DeleteChapterReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	OperatorId    int64                  `protobuf:"varint,2,opt,name=operator_id,json=operatorId,proto3" json:"operator_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteChapterReq) Reset() {
	*x = DeleteChapterReq{}
	mi := &file_course_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteChapterReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteChapterReq) ProtoMessage() {}

func (x *DeleteChapterReq) ProtoReflect() protoreflect.Message {
	mi := &file_course_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteChapterReq.ProtoReflect.Descriptor instead.
func (*DeleteChapterReq) Descriptor() ([]byte, []int) {
	return file_course_proto_rawDescGZIP(), []int{18}
}

func (x *DeleteChapterReq) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *DeleteChapterReq) GetOperatorId() int64 {
	if x != nil {
		return x.OperatorId
	}
	return 0
}

type DeleteChapterRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteChapterRes) Reset() {
	*x = DeleteChapterRes{}
	mi := &file_course_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteChapterRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteChapterRes) ProtoMessage() {}

func (x *DeleteChapterRes) ProtoReflect() protoreflect.Message {
	mi := &file_course_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteChapterRes.ProtoReflect.Descriptor instead.
func (*DeleteChapterRes) Descriptor() ([]byte, []int) {
	return file_course_proto_rawDescGZIP(), []int{19}
}

type CreateMaterialReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChapterId     int64                  `protobuf:"varint,1,opt,name=chapter_id,json=chapterId,proto3" json:"chapter_id,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Type          int32                  `protobuf:"varint,3,opt,name=type,proto3" json:"type,omitempty"` // 2:PDF 3:文档
	Url           string                 `protobuf:"bytes,4,opt,name=url,proto3" json:"url,omitempty"`
	FileHash      string                 `protobuf:"bytes,5,opt,name=file_hash,json=fileHash,proto3" json:"file_hash,omitempty"`
	FileSize      int64                  `protobuf:"varint,6,opt,name=file_size,json=fileSize,proto3" json:"file_size,omitempty"`
	Sort          int32                  `protobuf:"varint,7,opt,name=sort,proto3" json:"sort,omitempty"`
	OperatorId    int64                  `protobuf:"varint,8,opt,name=operator_id,json=operatorId,proto3" json:"operator_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateMaterialReq) Reset() {
	*x = CreateMaterialReq{}
	mi := &file_course_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateMaterialReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateMaterialReq) ProtoMessage() {}

func (x *CreateMaterialReq) ProtoReflect() protoreflect.Message {
	mi := &file_course_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateMaterialReq.ProtoReflect.Descriptor instead.
func (*CreateMaterialReq) Descriptor() ([]byte, []int) {
	return file_course_proto_rawDescGZIP(), []int{20}
}

func (x *CreateMaterialReq) GetChapterId() int64 {
	if x != nil {
		return x.ChapterId
	}
	return 0
}

func (x *CreateMaterialReq) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *CreateMaterialReq) GetType() int32 {
	if x != nil {
		return x.Type
	}
	return 0
}

func (x *CreateMaterialReq) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *CreateMaterialReq) GetFileHash() string {
	if x != nil {
		return x.FileHash
	}
	return ""
}

func (x *CreateMaterialReq) GetFileSize() int64 {
	if x != nil {
		return x.FileSize
	}
	return 0
}

func (x *CreateMaterialReq) GetSort() int32 {
	if x != nil {
		return x.Sort
	}
	return 0
}

func (x *CreateMaterialReq) GetOperatorId() int64 {
	if x != nil {
		return x.OperatorId
	}
	return 0
}

type CreateMaterialRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateMaterialRes) Reset() {
	*x = CreateMaterialRes{}
	mi := &file_course_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateMaterialRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateMaterialRes) ProtoMessage() {}

func (x *CreateMaterialRes) ProtoReflect() protoreflect.Message {
	mi := &file_course_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateMaterialRes.ProtoReflect.Descriptor instead.
func (*CreateMaterialRes) Descriptor() ([]byte, []int) {
	return file_course_proto_rawDescGZIP(), []int{21}
}

func (x *CreateMaterialRes) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type MaterialListReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChapterId     int64                  `protobuf:"varint,1,opt,name=chapter_id,json=chapterId,proto3" json:"chapter_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MaterialListReq) Reset() {
	*x = MaterialListReq{}
	mi := &file_course_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MaterialListReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MaterialListReq) ProtoMessage() {}

func (x *MaterialListReq) ProtoReflect() protoreflect.Message {
	mi := &file_course_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MaterialListReq.ProtoReflect.Descriptor instead.
func (*MaterialListReq) Descriptor() ([]byte, []int) {
	return file_course_proto_rawDescGZIP(), []int{22}
}

func (x *MaterialListReq) GetChapterId() int64 {
	if x != nil {
		return x.ChapterId
	}
	return 0
}

type MaterialItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	ChapterId     int64                  `protobuf:"varint,2,opt,name=chapter_id,json=chapterId,proto3" json:"chapter_id,omitempty"`
	Title         string                 `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	Type          int32                  `protobuf:"varint,4,opt,name=type,proto3" json:"type,omitempty"`
	Url           string                 `protobuf:"bytes,5,opt,name=url,proto3" json:"url,omitempty"`
	FileHash      string                 `protobuf:"bytes,6,opt,name=file_hash,json=fileHash,proto3" json:"file_hash,omitempty"`
	FileSize      int64                  `protobuf:"varint,7,opt,name=file_size,json=fileSize,proto3" json:"file_size,omitempty"`
	AiStatus      int32                  `protobuf:"varint,8,opt,name=ai_status,json=aiStatus,proto3" json:"ai_status,omitempty"`
	Sort          int32                  `protobuf:"varint,9,opt,name=sort,proto3" json:"sort,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MaterialItem) Reset() {
	*x = MaterialItem{}
	mi := &file_course_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MaterialItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MaterialItem) ProtoMessage() {}

func (x *MaterialItem) ProtoReflect() protoreflect.Message {
	mi := &file_course_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MaterialItem.ProtoReflect.Descriptor instead.
func (*MaterialItem) Descriptor() ([]byte, []int) {
	return file_course_proto_rawDescGZIP(), []int{23}
}

func (x *MaterialItem) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *MaterialItem) GetChapterId() int64 {
	if x != nil {
		return x.ChapterId
	}
	return 0
}

func (x *MaterialItem) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *MaterialItem) GetType() int32 {
	if x != nil {
		return x.Type
	}
	return 0
}

func (x *MaterialItem) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *MaterialItem) GetFileHash() string {
	if x != nil {
		return x.FileHash
	}
	return ""
}

func (x *MaterialItem) GetFileSize() int64 {
	if x != nil {
		return x.FileSize
	}
	return 0
}

func (x *MaterialItem) GetAiStatus() int32 {
	if x != nil {
		return x.AiStatus
	}
	return 0
}

func (x *MaterialItem) GetSort() int32 {
	if x != nil {
		return x.Sort
	}
	return 0
}

type MaterialListRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	List          []*MaterialItem        `protobuf:"bytes,1,rep,name=list,proto3" json:"list,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MaterialListRes) Reset() {
	*x = MaterialListRes{}
	mi := &file_course_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MaterialListRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MaterialListRes) ProtoMessage() {}

func (x *MaterialListRes) ProtoReflect() protoreflect.Message {
	mi := &file_course_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MaterialListRes.ProtoReflect.Descriptor instead.
func (*MaterialListRes) Descriptor() ([]byte, []int) {
	return file_course_proto_rawDescGZIP(), []int{24}
}

func (x *MaterialListRes) GetList() []*MaterialItem {
	if x != nil {
		return x.List
	}
	return nil
}

type DeleteMaterialReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	OperatorId    int64                  `protobuf:"varint,2,opt,name=operator_id,json=operatorId,proto3" json:"operator_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteMaterialReq) Reset() {
	*x = DeleteMaterialReq{}
	mi := &file_course_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteMaterialReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteMaterialReq) ProtoMessage() {}

func (x *DeleteMaterialReq) ProtoReflect() protoreflect.Message {
	mi := &file_course_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteMaterialReq.ProtoReflect.Descriptor instead.
func (*DeleteMaterialReq) Descriptor() ([]byte, []int) {
	return file_course_proto_rawDescGZIP(), []int{25}
}

func (x *DeleteMaterialReq) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *DeleteMaterialReq) GetOperatorId() int64 {
	if x != nil {
		return x.OperatorId
	}
	return 0
}

type DeleteMaterialRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteMaterialRes) Reset() {
	*x = DeleteMaterialRes{}
	mi := &file_course_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteMaterialRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteMaterialRes) ProtoMessage() {}

func (x *DeleteMaterialRes) ProtoReflect() protoreflect.Message {
	mi := &file_course_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteMaterialRes.ProtoReflect.Descriptor instead.
func (*DeleteMaterialRes) Descriptor() ([]byte, []int) {
	return file_course_proto_rawDescGZIP(), []int{26}
}

type UpdateStudyProgressReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	CourseId      int64                  `protobuf:"varint,2,opt,name=course_id,json=courseId,proto3" json:"course_id,omitempty"`
	ChapterId     int64                  `protobuf:"varint,3,opt,name=chapter_id,json=chapterId,proto3" json:"chapter_id,omitempty"`
	MaterialId    int64                  `protobuf:"varint,4,opt,name=material_id,json=materialId,proto3" json:"material_id,omitempty"`
	Progress      int32                  `protobuf:"varint,5,opt,name=progress,proto3" json:"progress,omitempty"` // 0~100
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateStudyProgressReq) Reset() {
	*x = UpdateStudyProgressReq{}
	mi := &file_course_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateStudyProgressReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateStudyProgressReq) ProtoMessage() {}

func (x *UpdateStudyProgressReq) ProtoReflect() protoreflect.Message {
	mi := &file_course_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateStudyProgressReq.ProtoReflect.Descriptor instead.
func (*UpdateStudyProgressReq) Descriptor() ([]byte, []int) {
	return file_course_proto_rawDescGZIP(), []int{27}
}

func (x *UpdateStudyProgressReq) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *UpdateStudyProgressReq) GetCourseId() int64 {
	if x != nil {
		return x.CourseId
	}
	return 0
}

func (x *UpdateStudyProgressReq) GetChapterId() int64 {
	if x != nil {
		return x.ChapterId
	}
	return 0
}

func (x *UpdateStudyProgressReq) GetMaterialId() int64 {
	if x != nil {
		return x.MaterialId
	}
	return 0
}

func (x *UpdateStudyProgressReq) GetProgress() int32 {
	if x != nil {
		return x.Progress
	}
	return 0
}

type UpdateStudyProgressRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateStudyProgressRes) Reset() {
	*x = UpdateStudyProgressRes{}
	mi := &file_course_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateStudyProgressRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateStudyProgressRes) ProtoMessage() {}

func (x *UpdateStudyProgressRes) ProtoReflect() protoreflect.Message {
	mi := &file_course_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateStudyProgressRes.ProtoReflect.Descriptor instead.
func (*UpdateStudyProgressRes) Descriptor() ([]byte, []int) {
	return file_course_proto_rawDescGZIP(), []int{28}
}

type GetStudyProgressReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	CourseId      int64                  `protobuf:"varint,2,opt,name=course_id,json=courseId,proto3" json:"course_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStudyProgressReq) Reset() {
	*x = GetStudyProgressReq{}
	mi := &file_course_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStudyProgressReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStudyProgressReq) ProtoMessage() {}

func (x *GetStudyProgressReq) ProtoReflect() protoreflect.Message {
	mi := &file_course_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStudyProgressReq.ProtoReflect.Descriptor instead.
func (*GetStudyProgressReq) Descriptor() ([]byte, []int) {
	return file_course_proto_rawDescGZIP(), []int{29}
}

func (x *GetStudyProgressReq) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *GetStudyProgressReq) GetCourseId() int64 {
	if x != nil {
		return x.CourseId
	}
	return 0
}

type StudyProgressItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MaterialId    int64                  `protobuf:"varint,1,opt,name=material_id,json=materialId,proto3" json:"material_id,omitempty"`
	ChapterId     int64                  `protobuf:"varint,2,opt,name=chapter_id,json=chapterId,proto3" json:"chapter_id,omitempty"`
	Progress      int32                  `protobuf:"varint,3,opt,name=progress,proto3" json:"progress,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StudyProgressItem) Reset() {
	*x = StudyProgressItem{}
	mi := &file_course_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StudyProgressItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StudyProgressItem) ProtoMessage() {}

func (x *StudyProgressItem) ProtoReflect() protoreflect.Message {
	mi := &file_course_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StudyProgressItem.ProtoReflect.Descriptor instead.
func (*StudyProgressItem) Descriptor() ([]byte, []int) {
	return file_course_proto_rawDescGZIP(), []int{30}
}

func (x *StudyProgressItem) GetMaterialId() int64 {
	if x != nil {
		return x.MaterialId
	}
	return 0
}

func (x *StudyProgressItem) GetChapterId() int64 {
	if x != nil {
		return x.ChapterId
	}
	return 0
}

func (x *StudyProgressItem) GetProgress() int32 {
	if x != nil {
		return x.Progress
	}
	return 0
}

type GetStudyProgressRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	List          []*StudyProgressItem   `protobuf:"bytes,1,rep,name=list,proto3" json:"list,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStudyProgressRes) Reset() {
	*x = GetStudyProgressRes{}
	mi := &file_course_proto_msgTypes[31]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStudyProgressRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStudyProgressRes) ProtoMessage() {}

func (x *GetStudyProgressRes) ProtoReflect() protoreflect.Message {
	mi := &file_course_proto_msgTypes[31]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStudyProgressRes.ProtoReflect.Descriptor instead.
func (*GetStudyProgressRes) Descriptor() ([]byte, []int) {
	return file_course_proto_rawDescGZIP(), []int{31}
}

func (x *GetStudyProgressRes) GetList() []*StudyProgressItem {
	if x != nil {
		return x.List
	}
	return nil
}

var File_course_proto protoreflect.FileDescriptor

const file_course_proto_rawDesc = "" +
	"\n" +
	"\fcourse.proto\x12\x06course\"~\n" +
	"\x0fCreateCourseReq\x12\x14\n" +
	"\x05title\x18\x01 \x01(\tR\x05title\x12\x14\n" +
	"\x05cover\x18\x02 \x01(\tR\x05cover\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x1d\n" +
	"\n" +
	"teacher_id\x18\x04 \x01(\x03R\tteacherId\"!\n" +
	"\x0fCreateCourseRes\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"V\n" +
	"\rCourseListReq\x12\x1d\n" +
	"\n" +
	"teacher_id\x18\x01 \x01(\x03R\tteacherId\x12\x12\n" +
	"\x04page\x18\x02 \x01(\x03R\x04page\x12\x12\n" +
	"\x04size\x18\x03 \x01(\x03R\x04size\"\xc2\x01\n" +
	"\n" +
	"CourseItem\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12\x14\n" +
	"\x05cover\x18\x03 \x01(\tR\x05cover\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\x12\x1d\n" +
	"\n" +
	"teacher_id\x18\x05 \x01(\x03R\tteacherId\x12\x16\n" +
	"\x06status\x18\x06 \x01(\x05R\x06status\x12\x1f\n" +
	"\vcreate_time\x18\a \x01(\x03R\n" +
	"createTime\"M\n" +
	"\rCourseListRes\x12&\n" +
	"\x04list\x18\x01 \x03(\v2\x12.course.CourseItemR\x04list\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x03R\x05total\"!\n" +
	"\x0fCourseDetailReq\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"n\n" +
	"\x0fCourseDetailRes\x12*\n" +
	"\x06course\x18\x01 \x01(\v2\x12.course.CourseItemR\x06course\x12/\n" +
	"\bchapters\x18\x02 \x03(\v2\x13.course.ChapterItemR\bchapters\"\xa8\x01\n" +
	"\x0fUpdateCourseReq\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12\x14\n" +
	"\x05cover\x18\x03 \x01(\tR\x05cover\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\x12\x16\n" +
	"\x06status\x18\x05 \x01(\x05R\x06status\x12\x1f\n" +
	"\voperator_id\x18\x06 \x01(\x03R\n" +
	"operatorId\"\x11\n" +
	"\x0fUpdateCourseRes\"B\n" +
	"\x0fDeleteCourseReq\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x1f\n" +
	"\voperator_id\x18\x02 \x01(\x03R\n" +
	"operatorId\"\x11\n" +
	"\x0fDeleteCourseRes\"z\n" +
	"\x10CreateChapterReq\x12\x1b\n" +
	"\tcourse_id\x18\x01 \x01(\x03R\bcourseId\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12\x12\n" +
	"\x04sort\x18\x03 \x01(\x05R\x04sort\x12\x1f\n" +
	"\voperator_id\x18\x04 \x01(\x03R\n" +
	"operatorId\"\"\n" +
	"\x10CreateChapterRes\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"-\n" +
	"\x0eChapterListReq\x12\x1b\n" +
	"\tcourse_id\x18\x01 \x01(\x03R\bcourseId\"\x98\x01\n" +
	"\vChapterItem\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x1b\n" +
	"\tcourse_id\x18\x02 \x01(\x03R\bcourseId\x12\x14\n" +
	"\x05title\x18\x03 \x01(\tR\x05title\x12\x12\n" +
	"\x04sort\x18\x04 \x01(\x05R\x04sort\x122\n" +
	"\tmaterials\x18\x05 \x03(\v2\x14.course.MaterialItemR\tmaterials\"9\n" +
	"\x0eChapterListRes\x12'\n" +
	"\x04list\x18\x01 \x03(\v2\x13.course.ChapterItemR\x04list\"m\n" +
	"\x10UpdateChapterReq\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12\x12\n" +
	"\x04sort\x18\x03 \x01(\x05R\x04sort\x12\x1f\n" +
	"\voperator_id\x18\x04 \x01(\x03R\n" +
	"operatorId\"\x12\n" +
	"\x10UpdateChapterRes\"C\n" +
	"\x10DeleteChapterReq\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x1f\n" +
	"\voperator_id\x18\x02 \x01(\x03R\n" +
	"operatorId\"\x12\n" +
	"\x10DeleteChapterRes\"\xdd\x01\n" +
	"\x11CreateMaterialReq\x12\x1d\n" +
	"\n" +
	"chapter_id\x18\x01 \x01(\x03R\tchapterId\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12\x12\n" +
	"\x04type\x18\x03 \x01(\x05R\x04type\x12\x10\n" +
	"\x03url\x18\x04 \x01(\tR\x03url\x12\x1b\n" +
	"\tfile_hash\x18\x05 \x01(\tR\bfileHash\x12\x1b\n" +
	"\tfile_size\x18\x06 \x01(\x03R\bfileSize\x12\x12\n" +
	"\x04sort\x18\a \x01(\x05R\x04sort\x12\x1f\n" +
	"\voperator_id\x18\b \x01(\x03R\n" +
	"operatorId\"#\n" +
	"\x11CreateMaterialRes\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"0\n" +
	"\x0fMaterialListReq\x12\x1d\n" +
	"\n" +
	"chapter_id\x18\x01 \x01(\x03R\tchapterId\"\xe4\x01\n" +
	"\fMaterialItem\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x1d\n" +
	"\n" +
	"chapter_id\x18\x02 \x01(\x03R\tchapterId\x12\x14\n" +
	"\x05title\x18\x03 \x01(\tR\x05title\x12\x12\n" +
	"\x04type\x18\x04 \x01(\x05R\x04type\x12\x10\n" +
	"\x03url\x18\x05 \x01(\tR\x03url\x12\x1b\n" +
	"\tfile_hash\x18\x06 \x01(\tR\bfileHash\x12\x1b\n" +
	"\tfile_size\x18\a \x01(\x03R\bfileSize\x12\x1b\n" +
	"\tai_status\x18\b \x01(\x05R\baiStatus\x12\x12\n" +
	"\x04sort\x18\t \x01(\x05R\x04sort\";\n" +
	"\x0fMaterialListRes\x12(\n" +
	"\x04list\x18\x01 \x03(\v2\x14.course.MaterialItemR\x04list\"D\n" +
	"\x11DeleteMaterialReq\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x1f\n" +
	"\voperator_id\x18\x02 \x01(\x03R\n" +
	"operatorId\"\x13\n" +
	"\x11DeleteMaterialRes\"\xaa\x01\n" +
	"\x16UpdateStudyProgressReq\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12\x1b\n" +
	"\tcourse_id\x18\x02 \x01(\x03R\bcourseId\x12\x1d\n" +
	"\n" +
	"chapter_id\x18\x03 \x01(\x03R\tchapterId\x12\x1f\n" +
	"\vmaterial_id\x18\x04 \x01(\x03R\n" +
	"materialId\x12\x1a\n" +
	"\bprogress\x18\x05 \x01(\x05R\bprogress\"\x18\n" +
	"\x16UpdateStudyProgressRes\"K\n" +
	"\x13GetStudyProgressReq\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12\x1b\n" +
	"\tcourse_id\x18\x02 \x01(\x03R\bcourseId\"o\n" +
	"\x11StudyProgressItem\x12\x1f\n" +
	"\vmaterial_id\x18\x01 \x01(\x03R\n" +
	"materialId\x12\x1d\n" +
	"\n" +
	"chapter_id\x18\x02 \x01(\x03R\tchapterId\x12\x1a\n" +
	"\bprogress\x18\x03 \x01(\x05R\bprogress\"D\n" +
	"\x13GetStudyProgressRes\x12-\n" +
	"\x04list\x18\x01 \x03(\v2\x19.course.StudyProgressItemR\x04list2\xd1\a\n" +
	"\x06Course\x12@\n" +
	"\fCreateCourse\x12\x17.course.CreateCourseReq\x1a\x17.course.CreateCourseRes\x12:\n" +
	"\n" +
	"CourseList\x12\x15.course.CourseListReq\x1a\x15.course.CourseListRes\x12@\n" +
	"\fCourseDetail\x12\x17.course.CourseDetailReq\x1a\x17.course.CourseDetailRes\x12@\n" +
	"\fUpdateCourse\x12\x17.course.UpdateCourseReq\x1a\x17.course.UpdateCourseRes\x12@\n" +
	"\fDeleteCourse\x12\x17.course.DeleteCourseReq\x1a\x17.course.DeleteCourseRes\x12C\n" +
	"\rCreateChapter\x12\x18.course.CreateChapterReq\x1a\x18.course.CreateChapterRes\x12=\n" +
	"\vChapterList\x12\x16.course.ChapterListReq\x1a\x16.course.ChapterListRes\x12C\n" +
	"\rUpdateChapter\x12\x18.course.UpdateChapterReq\x1a\x18.course.UpdateChapterRes\x12C\n" +
	"\rDeleteChapter\x12\x18.course.DeleteChapterReq\x1a\x18.course.DeleteChapterRes\x12F\n" +
	"\x0eCreateMaterial\x12\x19.course.CreateMaterialReq\x1a\x19.course.CreateMaterialRes\x12@\n" +
	"\fMaterialList\x12\x17.course.MaterialListReq\x1a\x17.course.MaterialListRes\x12F\n" +
	"\x0eDeleteMaterial\x12\x19.course.DeleteMaterialReq\x1a\x19.course.DeleteMaterialRes\x12U\n" +
	"\x13UpdateStudyProgress\x12\x1e.course.UpdateStudyProgressReq\x1a\x1e.course.UpdateStudyProgressRes\x12L\n" +
	"\x10GetStudyProgress\x12\x1b.course.GetStudyProgressReq\x1a\x1b.course.GetStudyProgressResB\x06Z\x04./pbb\x06proto3"

var (
	file_course_proto_rawDescOnce sync.Once
	file_course_proto_rawDescData []byte
)

func file_course_proto_rawDescGZIP() []byte {
	file_course_proto_rawDescOnce.Do(func() {
		file_course_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_course_proto_rawDesc), len(file_course_proto_rawDesc)))
	})
	return file_course_proto_rawDescData
}

var file_course_proto_msgTypes = make([]protoimpl.MessageInfo, 32)
var file_course_proto_goTypes = []any{
	(*CreateCourseReq)(nil),        // 0: course.CreateCourseReq
	(*CreateCourseRes)(nil),        // 1: course.CreateCourseRes
	(*CourseListReq)(nil),          // 2: course.CourseListReq
	(*CourseItem)(nil),             // 3: course.CourseItem
	(*CourseListRes)(nil),          // 4: course.CourseListRes
	(*CourseDetailReq)(nil),        // 5: course.CourseDetailReq
	(*CourseDetailRes)(nil),        // 6: course.CourseDetailRes
	(*UpdateCourseReq)(nil),        // 7: course.UpdateCourseReq
	(*UpdateCourseRes)(nil),        // 8: course.UpdateCourseRes
	(*DeleteCourseReq)(nil),        // 9: course.DeleteCourseReq
	(*DeleteCourseRes)(nil),        // 10: course.DeleteCourseRes
	(*CreateChapterReq)(nil),       // 11: course.CreateChapterReq
	(*CreateChapterRes)(nil),       // 12: course.CreateChapterRes
	(*ChapterListReq)(nil),         // 13: course.ChapterListReq
	(*ChapterItem)(nil),            // 14: course.ChapterItem
	(*ChapterListRes)(nil),         // 15: course.ChapterListRes
	(*UpdateChapterReq)(nil),       // 16: course.UpdateChapterReq
	(*UpdateChapterRes)(nil),       // 17: course.UpdateChapterRes
	(*DeleteChapterReq)(nil),       // 18: course.DeleteChapterReq
	(*DeleteChapterRes)(nil),       // 19: course.DeleteChapterRes
	(*CreateMaterialReq)(nil),      // 20: course.CreateMaterialReq
	(*CreateMaterialRes)(nil),      // 21: course.CreateMaterialRes
	(*MaterialListReq)(nil),        // 22: course.MaterialListReq
	(*MaterialItem)(nil),           // 23: course.MaterialItem
	(*MaterialListRes)(nil),        // 24: course.MaterialListRes
	(*DeleteMaterialReq)(nil),      // 25: course.DeleteMaterialReq
	(*DeleteMaterialRes)(nil),      // 26: course.DeleteMaterialRes
	(*UpdateStudyProgressReq)(nil), // 27: course.UpdateStudyProgressReq
	(*UpdateStudyProgressRes)(nil), // 28: course.UpdateStudyProgressRes
	(*GetStudyProgressReq)(nil),    // 29: course.GetStudyProgressReq
	(*StudyProgressItem)(nil),      // 30: course.StudyProgressItem
	(*GetStudyProgressRes)(nil),    // 31: course.GetStudyProgressRes
}
var file_course_proto_depIdxs = []int32{
	3,  // 0: course.CourseListRes.list:type_name -> course.CourseItem
	3,  // 1: course.CourseDetailRes.course:type_name -> course.CourseItem
	14, // 2: course.CourseDetailRes.chapters:type_name -> course.ChapterItem
	23, // 3: course.ChapterItem.materials:type_name -> course.MaterialItem
	14, // 4: course.ChapterListRes.list:type_name -> course.ChapterItem
	23, // 5: course.MaterialListRes.list:type_name -> course.MaterialItem
	30, // 6: course.GetStudyProgressRes.list:type_name -> course.StudyProgressItem
	0,  // 7: course.Course.CreateCourse:input_type -> course.CreateCourseReq
	2,  // 8: course.Course.CourseList:input_type -> course.CourseListReq
	5,  // 9: course.Course.CourseDetail:input_type -> course.CourseDetailReq
	7,  // 10: course.Course.UpdateCourse:input_type -> course.UpdateCourseReq
	9,  // 11: course.Course.DeleteCourse:input_type -> course.DeleteCourseReq
	11, // 12: course.Course.CreateChapter:input_type -> course.CreateChapterReq
	13, // 13: course.Course.ChapterList:input_type -> course.ChapterListReq
	16, // 14: course.Course.UpdateChapter:input_type -> course.UpdateChapterReq
	18, // 15: course.Course.DeleteChapter:input_type -> course.DeleteChapterReq
	20, // 16: course.Course.CreateMaterial:input_type -> course.CreateMaterialReq
	22, // 17: course.Course.MaterialList:input_type -> course.MaterialListReq
	25, // 18: course.Course.DeleteMaterial:input_type -> course.DeleteMaterialReq
	27, // 19: course.Course.UpdateStudyProgress:input_type -> course.UpdateStudyProgressReq
	29, // 20: course.Course.GetStudyProgress:input_type -> course.GetStudyProgressReq
	1,  // 21: course.Course.CreateCourse:output_type -> course.CreateCourseRes
	4,  // 22: course.Course.CourseList:output_type -> course.CourseListRes
	6,  // 23: course.Course.CourseDetail:output_type -> course.CourseDetailRes
	8,  // 24: course.Course.UpdateCourse:output_type -> course.UpdateCourseRes
	10, // 25: course.Course.DeleteCourse:output_type -> course.DeleteCourseRes
	12, // 26: course.Course.CreateChapter:output_type -> course.CreateChapterRes
	15, // 27: course.Course.ChapterList:output_type -> course.ChapterListRes
	17, // 28: course.Course.UpdateChapter:output_type -> course.UpdateChapterRes
	19, // 29: course.Course.DeleteChapter:output_type -> course.DeleteChapterRes
	21, // 30: course.Course.CreateMaterial:output_type -> course.CreateMaterialRes
	24, // 31: course.Course.MaterialList:output_type -> course.MaterialListRes
	26, // 32: course.Course.DeleteMaterial:output_type -> course.DeleteMaterialRes
	28, // 33: course.Course.UpdateStudyProgress:output_type -> course.UpdateStudyProgressRes
	31, // 34: course.Course.GetStudyProgress:output_type -> course.GetStudyProgressRes
	21, // [21:35] is the sub-list for method output_type
	7,  // [7:21] is the sub-list for method input_type
	7,  // [7:7] is the sub-list for extension type_name
	7,  // [7:7] is the sub-list for extension extendee
	0,  // [0:7] is the sub-list for field type_name
}

func init() { file_course_proto_init() }
func file_course_proto_init() {
	if File_course_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_course_proto_rawDesc), len(file_course_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   32,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_course_proto_goTypes,
		DependencyIndexes: file_course_proto_depIdxs,
		MessageInfos:      file_course_proto_msgTypes,
	}.Build()
	File_course_proto = out.File
	file_course_proto_goTypes = nil
	file_course_proto_depIdxs = nil
}
