// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v3.19.4
// source: agent.proto

package agentpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	AgentService_GradeSubjective_FullMethodName          = "/agent.AgentService/GradeSubjective"
	AgentService_EmbedMaterial_FullMethodName            = "/agent.AgentService/EmbedMaterial"
	AgentService_GetEmbedStatus_FullMethodName           = "/agent.AgentService/GetEmbedStatus"
	AgentService_AskQuestion_FullMethodName              = "/agent.AgentService/AskQuestion"
	AgentService_AskQuestionStream_FullMethodName        = "/agent.AgentService/AskQuestionStream"
	AgentService_GenerateQuestions_FullMethodName        = "/agent.AgentService/GenerateQuestions"
	AgentService_GenerateCourseOutline_FullMethodName    = "/agent.AgentService/GenerateCourseOutline"
	AgentService_GenerateCourseware_FullMethodName       = "/agent.AgentService/GenerateCourseware"
	AgentService_GenerateCoursewareStream_FullMethodName = "/agent.AgentService/GenerateCoursewareStream"
	AgentService_GetTaskStatus_FullMethodName            = "/agent.AgentService/GetTaskStatus"
)

// AgentServiceClient is the client API for AgentService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// AgentService — Python AI Agent 对外暴露的 gRPC 服务
// 由 Go 侧 AI Bridge 作为 gRPC Client 调用
type AgentServiceClient interface {
	// ========== 判卷 ==========
	GradeSubjective(ctx context.Context, in *GradeSubjectiveReq, opts ...grpc.CallOption) (*GradeSubjectiveRes, error)
	// ========== 课件向量化 ==========
	EmbedMaterial(ctx context.Context, in *EmbedMaterialReq, opts ...grpc.CallOption) (*EmbedMaterialRes, error)
	GetEmbedStatus(ctx context.Context, in *GetEmbedStatusReq, opts ...grpc.CallOption) (*GetEmbedStatusRes, error)
	// ========== 智能助教 RAG ==========
	AskQuestion(ctx context.Context, in *AskQuestionReq, opts ...grpc.CallOption) (*AskQuestionRes, error)
	// 流式回答 (SSE 打字机效果)，支持多轮对话（携带 session_id）
	AskQuestionStream(ctx context.Context, in *AskQuestionReq, opts ...grpc.CallOption) (grpc.ServerStreamingClient[StreamDelta], error)
	// ========== 智能生成 (异步 task_id 模式) ==========
	GenerateQuestions(ctx context.Context, in *GenerateQuestionsReq, opts ...grpc.CallOption) (*GenerateTaskRes, error)
	GenerateCourseOutline(ctx context.Context, in *GenerateCourseOutlineReq, opts ...grpc.CallOption) (*GenerateTaskRes, error)
	GenerateCourseware(ctx context.Context, in *GenerateCoursewareReq, opts ...grpc.CallOption) (*GenerateTaskRes, error)
	// 流式生成课件 Markdown，支持多轮对话（携带 session_id）
	GenerateCoursewareStream(ctx context.Context, in *GenerateCoursewareReq, opts ...grpc.CallOption) (grpc.ServerStreamingClient[StreamDelta], error)
	GetTaskStatus(ctx context.Context, in *GetTaskStatusReq, opts ...grpc.CallOption) (*GetTaskStatusRes, error)
}

type agentServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAgentServiceClient(cc grpc.ClientConnInterface) AgentServiceClient {
	return &agentServiceClient{cc}
}

func (c *agentServiceClient) GradeSubjective(ctx context.Context, in *GradeSubjectiveReq, opts ...grpc.CallOption) (*GradeSubjectiveRes, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GradeSubjectiveRes)
	err := c.cc.Invoke(ctx, AgentService_GradeSubjective_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentServiceClient) EmbedMaterial(ctx context.Context, in *EmbedMaterialReq, opts ...grpc.CallOption) (*EmbedMaterialRes, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EmbedMaterialRes)
	err := c.cc.Invoke(ctx, AgentService_EmbedMaterial_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentServiceClient) GetEmbedStatus(ctx context.Context, in *GetEmbedStatusReq, opts ...grpc.CallOption) (*GetEmbedStatusRes, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetEmbedStatusRes)
	err := c.cc.Invoke(ctx, AgentService_GetEmbedStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentServiceClient) AskQuestion(ctx context.Context, in *AskQuestionReq, opts ...grpc.CallOption) (*AskQuestionRes, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AskQuestionRes)
	err := c.cc.Invoke(ctx, AgentService_AskQuestion_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentServiceClient) AskQuestionStream(ctx context.Context, in *AskQuestionReq, opts ...grpc.CallOption) (grpc.ServerStreamingClient[StreamDelta], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &AgentService_ServiceDesc.Streams[0], AgentService_AskQuestionStream_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[AskQuestionReq, StreamDelta]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type AgentService_AskQuestionStreamClient = grpc.ServerStreamingClient[StreamDelta]

func (c *agentServiceClient) GenerateQuestions(ctx context.Context, in *GenerateQuestionsReq, opts ...grpc.CallOption) (*GenerateTaskRes, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GenerateTaskRes)
	err := c.cc.Invoke(ctx, AgentService_GenerateQuestions_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentServiceClient) GenerateCourseOutline(ctx context.Context, in *GenerateCourseOutlineReq, opts ...grpc.CallOption) (*GenerateTaskRes, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GenerateTaskRes)
	err := c.cc.Invoke(ctx, AgentService_GenerateCourseOutline_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentServiceClient) GenerateCourseware(ctx context.Context, in *GenerateCoursewareReq, opts ...grpc.CallOption) (*GenerateTaskRes, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GenerateTaskRes)
	err := c.cc.Invoke(ctx, AgentService_GenerateCourseware_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentServiceClient) GenerateCoursewareStream(ctx context.Context, in *GenerateCoursewareReq, opts ...grpc.CallOption) (grpc.ServerStreamingClient[StreamDelta], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &AgentService_ServiceDesc.Streams[1], AgentService_GenerateCoursewareStream_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[GenerateCoursewareReq, StreamDelta]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type AgentService_GenerateCoursewareStreamClient = grpc.ServerStreamingClient[StreamDelta]

func (c *agentServiceClient) GetTaskStatus(ctx context.Context, in *GetTaskStatusReq, opts ...grpc.CallOption) (*GetTaskStatusRes, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetTaskStatusRes)
	err := c.cc.Invoke(ctx, AgentService_GetTaskStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AgentServiceServer is the server API for AgentService service.
// All implementations must embed UnimplementedAgentServiceServer
// for forward compatibility.
//
// AgentService — Python AI Agent 对外暴露的 gRPC 服务
// 由 Go 侧 AI Bridge 作为 gRPC Client 调用
type AgentServiceServer interface {
	// ========== 判卷 ==========
	GradeSubjective(context.Context, *GradeSubjectiveReq) (*GradeSubjectiveRes, error)
	// ========== 课件向量化 ==========
	EmbedMaterial(context.Context, *EmbedMaterialReq) (*EmbedMaterialRes, error)
	GetEmbedStatus(context.Context, *GetEmbedStatusReq) (*GetEmbedStatusRes, error)
	// ========== 智能助教 RAG ==========
	AskQuestion(context.Context, *AskQuestionReq) (*AskQuestionRes, error)
	// 流式回答 (SSE 打字机效果)，支持多轮对话（携带 session_id）
	AskQuestionStream(*AskQuestionReq, grpc.ServerStreamingServer[StreamDelta]) error
	// ========== 智能生成 (异步 task_id 模式) ==========
	GenerateQuestions(context.Context, *GenerateQuestionsReq) (*GenerateTaskRes, error)
	GenerateCourseOutline(context.Context, *GenerateCourseOutlineReq) (*GenerateTaskRes, error)
	GenerateCourseware(context.Context, *GenerateCoursewareReq) (*GenerateTaskRes, error)
	// 流式生成课件 Markdown，支持多轮对话（携带 session_id）
	GenerateCoursewareStream(*GenerateCoursewareReq, grpc.ServerStreamingServer[StreamDelta]) error
	GetTaskStatus(context.Context, *GetTaskStatusReq) (*GetTaskStatusRes, error)
	mustEmbedUnimplementedAgentServiceServer()
}

// UnimplementedAgentServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAgentServiceServer struct{}

func (UnimplementedAgentServiceServer) GradeSubjective(context.Context, *GradeSubjectiveReq) (*GradeSubjectiveRes, error) {
	return nil, status.Error(codes.Unimplemented, "method GradeSubjective not implemented")
}
func (UnimplementedAgentServiceServer) EmbedMaterial(context.Context, *EmbedMaterialReq) (*EmbedMaterialRes, error) {
	return nil, status.Error(codes.Unimplemented, "method EmbedMaterial not implemented")
}
func (UnimplementedAgentServiceServer) GetEmbedStatus(context.Context, *GetEmbedStatusReq) (*GetEmbedStatusRes, error) {
	return nil, status.Error(codes.Unimplemented, "method GetEmbedStatus not implemented")
}
func (UnimplementedAgentServiceServer) AskQuestion(context.Context, *AskQuestionReq) (*AskQuestionRes, error) {
	return nil, status.Error(codes.Unimplemented, "method AskQuestion not implemented")
}
func (UnimplementedAgentServiceServer) AskQuestionStream(*AskQuestionReq, grpc.ServerStreamingServer[StreamDelta]) error {
	return status.Error(codes.Unimplemented, "method AskQuestionStream not implemented")
}
func (UnimplementedAgentServiceServer) GenerateQuestions(context.Context, *GenerateQuestionsReq) (*GenerateTaskRes, error) {
	return nil, status.Error(codes.Unimplemented, "method GenerateQuestions not implemented")
}
func (UnimplementedAgentServiceServer) GenerateCourseOutline(context.Context, *GenerateCourseOutlineReq) (*GenerateTaskRes, error) {
	return nil, status.Error(codes.Unimplemented, "method GenerateCourseOutline not implemented")
}
func (UnimplementedAgentServiceServer) GenerateCourseware(context.Context, *GenerateCoursewareReq) (*GenerateTaskRes, error) {
	return nil, status.Error(codes.Unimplemented, "method GenerateCourseware not implemented")
}
func (UnimplementedAgentServiceServer) GenerateCoursewareStream(*GenerateCoursewareReq, grpc.ServerStreamingServer[StreamDelta]) error {
	return status.Error(codes.Unimplemented, "method GenerateCoursewareStream not implemented")
}
func (UnimplementedAgentServiceServer) GetTaskStatus(context.Context, *GetTaskStatusReq) (*GetTaskStatusRes, error) {
	return nil, status.Error(codes.Unimplemented, "method GetTaskStatus not implemented")
}
func (UnimplementedAgentServiceServer) mustEmbedUnimplementedAgentServiceServer() {}
func (UnimplementedAgentServiceServer) testEmbeddedByValue()                      {}

// UnsafeAgentServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AgentServiceServer will
// result in compilation errors.
type UnsafeAgentServiceServer interface {
	mustEmbedUnimplementedAgentServiceServer()
}

func RegisterAgentServiceServer(s grpc.ServiceRegistrar, srv AgentServiceServer) {
	// If the following call panics, it indicates UnimplementedAgentServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AgentService_ServiceDesc, srv)
}

func _AgentService_GradeSubjective_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GradeSubjectiveReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServiceServer).GradeSubjective(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentService_GradeSubjective_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServiceServer).GradeSubjective(ctx, req.(*GradeSubjectiveReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentService_EmbedMaterial_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EmbedMaterialReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServiceServer).EmbedMaterial(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentService_EmbedMaterial_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServiceServer).EmbedMaterial(ctx, req.(*EmbedMaterialReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentService_GetEmbedStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetEmbedStatusReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServiceServer).GetEmbedStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentService_GetEmbedStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServiceServer).GetEmbedStatus(ctx, req.(*GetEmbedStatusReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentService_AskQuestion_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AskQuestionReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServiceServer).AskQuestion(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentService_AskQuestion_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServiceServer).AskQuestion(ctx, req.(*AskQuestionReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentService_AskQuestionStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(AskQuestionReq)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(AgentServiceServer).AskQuestionStream(m, &grpc.GenericServerStream[AskQuestionReq, StreamDelta]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type AgentService_AskQuestionStreamServer = grpc.ServerStreamingServer[StreamDelta]

func _AgentService_GenerateQuestions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GenerateQuestionsReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServiceServer).GenerateQuestions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentService_GenerateQuestions_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServiceServer).GenerateQuestions(ctx, req.(*GenerateQuestionsReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentService_GenerateCourseOutline_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GenerateCourseOutlineReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServiceServer).GenerateCourseOutline(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentService_GenerateCourseOutline_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServiceServer).GenerateCourseOutline(ctx, req.(*GenerateCourseOutlineReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentService_GenerateCourseware_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GenerateCoursewareReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServiceServer).GenerateCourseware(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentService_GenerateCourseware_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServiceServer).GenerateCourseware(ctx, req.(*GenerateCoursewareReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentService_GenerateCoursewareStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(GenerateCoursewareReq)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(AgentServiceServer).GenerateCoursewareStream(m, &grpc.GenericServerStream[GenerateCoursewareReq, StreamDelta]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type AgentService_GenerateCoursewareStreamServer = grpc.ServerStreamingServer[StreamDelta]

func _AgentService_GetTaskStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTaskStatusReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServiceServer).GetTaskStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentService_GetTaskStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServiceServer).GetTaskStatus(ctx, req.(*GetTaskStatusReq))
	}
	return interceptor(ctx, in, info, handler)
}

// AgentService_ServiceDesc is the grpc.ServiceDesc for AgentService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AgentService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "agent.AgentService",
	HandlerType: (*AgentServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GradeSubjective",
			Handler:    _AgentService_GradeSubjective_Handler,
		},
		{
			MethodName: "EmbedMaterial",
			Handler:    _AgentService_EmbedMaterial_Handler,
		},
		{
			MethodName: "GetEmbedStatus",
			Handler:    _AgentService_GetEmbedStatus_Handler,
		},
		{
			MethodName: "AskQuestion",
			Handler:    _AgentService_AskQuestion_Handler,
		},
		{
			MethodName: "GenerateQuestions",
			Handler:    _AgentService_GenerateQuestions_Handler,
		},
		{
			MethodName: "GenerateCourseOutline",
			Handler:    _AgentService_GenerateCourseOutline_Handler,
		},
		{
			MethodName: "GenerateCourseware",
			Handler:    _AgentService_GenerateCourseware_Handler,
		},
		{
			MethodName: "GetTaskStatus",
			Handler:    _AgentService_GetTaskStatus_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "AskQuestionStream",
			Handler:       _AgentService_AskQuestionStream_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "GenerateCoursewareStream",
			Handler:       _AgentService_GenerateCoursewareStream_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "agent.proto",
}
