// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.19.4
// source: agent.proto

package agentpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 通用流式增量消息体 (AskQuestionStream 和 GenerateCoursewareStream 共用)
type StreamDelta struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Delta         string                 `protobuf:"bytes,1,opt,name=delta,proto3" json:"delta,omitempty"`                          // 增量文本片段
	Sources       []string               `protobuf:"bytes,2,rep,name=sources,proto3" json:"sources,omitempty"`                      // 引用来源 (RAG 场景最后一帧携带)
	Finished      bool                   `protobuf:"varint,3,opt,name=finished,proto3" json:"finished,omitempty"`                   // 是否是最后一帧
	SessionId     string                 `protobuf:"bytes,4,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"` // 首帧返回，供客户端后续多轮使用
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamDelta) Reset() {
	*x = StreamDelta{}
	mi := &file_agent_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamDelta) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamDelta) ProtoMessage() {}

func (x *StreamDelta) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamDelta.ProtoReflect.Descriptor instead.
func (*StreamDelta) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{0}
}

func (x *StreamDelta) GetDelta() string {
	if x != nil {
		return x.Delta
	}
	return ""
}

func (x *StreamDelta) GetSources() []string {
	if x != nil {
		return x.Sources
	}
	return nil
}

func (x *StreamDelta) GetFinished() bool {
	if x != nil {
		return x.Finished
	}
	return false
}

func (x *StreamDelta) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

type GradeSubjectiveReq struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	RecordId        int64                  `protobuf:"varint,1,opt,name=record_id,json=recordId,proto3" json:"record_id,omitempty"`
	QuestionId      int64                  `protobuf:"varint,2,opt,name=question_id,json=questionId,proto3" json:"question_id,omitempty"`
	QuestionContent string                 `protobuf:"bytes,3,opt,name=question_content,json=questionContent,proto3" json:"question_content,omitempty"`
	StandardAnswer  string                 `protobuf:"bytes,4,opt,name=standard_answer,json=standardAnswer,proto3" json:"standard_answer,omitempty"`
	KnowledgePoints string                 `protobuf:"bytes,5,opt,name=knowledge_points,json=knowledgePoints,proto3" json:"knowledge_points,omitempty"`
	UserAnswer      string                 `protobuf:"bytes,6,opt,name=user_answer,json=userAnswer,proto3" json:"user_answer,omitempty"`
	MaxScore        string                 `protobuf:"bytes,7,opt,name=max_score,json=maxScore,proto3" json:"max_score,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *GradeSubjectiveReq) Reset() {
	*x = GradeSubjectiveReq{}
	mi := &file_agent_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GradeSubjectiveReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GradeSubjectiveReq) ProtoMessage() {}

func (x *GradeSubjectiveReq) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GradeSubjectiveReq.ProtoReflect.Descriptor instead.
func (*GradeSubjectiveReq) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{1}
}

func (x *GradeSubjectiveReq) GetRecordId() int64 {
	if x != nil {
		return x.RecordId
	}
	return 0
}

func (x *GradeSubjectiveReq) GetQuestionId() int64 {
	if x != nil {
		return x.QuestionId
	}
	return 0
}

func (x *GradeSubjectiveReq) GetQuestionContent() string {
	if x != nil {
		return x.QuestionContent
	}
	return ""
}

func (x *GradeSubjectiveReq) GetStandardAnswer() string {
	if x != nil {
		return x.StandardAnswer
	}
	return ""
}

func (x *GradeSubjectiveReq) GetKnowledgePoints() string {
	if x != nil {
		return x.KnowledgePoints
	}
	return ""
}

func (x *GradeSubjectiveReq) GetUserAnswer() string {
	if x != nil {
		return x.UserAnswer
	}
	return ""
}

func (x *GradeSubjectiveReq) GetMaxScore() string {
	if x != nil {
		return x.MaxScore
	}
	return ""
}

type GradeSubjectiveRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	QuestionId    int64                  `protobuf:"varint,1,opt,name=question_id,json=questionId,proto3" json:"question_id,omitempty"`
	Score         string                 `protobuf:"bytes,2,opt,name=score,proto3" json:"score,omitempty"`
	IsCorrect     int32                  `protobuf:"varint,3,opt,name=is_correct,json=isCorrect,proto3" json:"is_correct,omitempty"` // 0:错误 1:正确 2:部分得分
	AiComment     string                 `protobuf:"bytes,4,opt,name=ai_comment,json=aiComment,proto3" json:"ai_comment,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GradeSubjectiveRes) Reset() {
	*x = GradeSubjectiveRes{}
	mi := &file_agent_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GradeSubjectiveRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GradeSubjectiveRes) ProtoMessage() {}

func (x *GradeSubjectiveRes) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GradeSubjectiveRes.ProtoReflect.Descriptor instead.
func (*GradeSubjectiveRes) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{2}
}

func (x *GradeSubjectiveRes) GetQuestionId() int64 {
	if x != nil {
		return x.QuestionId
	}
	return 0
}

func (x *GradeSubjectiveRes) GetScore() string {
	if x != nil {
		return x.Score
	}
	return ""
}

func (x *GradeSubjectiveRes) GetIsCorrect() int32 {
	if x != nil {
		return x.IsCorrect
	}
	return 0
}

func (x *GradeSubjectiveRes) GetAiComment() string {
	if x != nil {
		return x.AiComment
	}
	return ""
}

type EmbedMaterialReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MaterialId    int64                  `protobuf:"varint,1,opt,name=material_id,json=materialId,proto3" json:"material_id,omitempty"`
	CourseId      int64                  `protobuf:"varint,2,opt,name=course_id,json=courseId,proto3" json:"course_id,omitempty"`
	Title         string                 `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	Url           string                 `protobuf:"bytes,4,opt,name=url,proto3" json:"url,omitempty"`
	Type          int32                  `protobuf:"varint,5,opt,name=type,proto3" json:"type,omitempty"` // 2:PDF 3:文档
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EmbedMaterialReq) Reset() {
	*x = EmbedMaterialReq{}
	mi := &file_agent_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EmbedMaterialReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmbedMaterialReq) ProtoMessage() {}

func (x *EmbedMaterialReq) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmbedMaterialReq.ProtoReflect.Descriptor instead.
func (*EmbedMaterialReq) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{3}
}

func (x *EmbedMaterialReq) GetMaterialId() int64 {
	if x != nil {
		return x.MaterialId
	}
	return 0
}

func (x *EmbedMaterialReq) GetCourseId() int64 {
	if x != nil {
		return x.CourseId
	}
	return 0
}

func (x *EmbedMaterialReq) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *EmbedMaterialReq) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *EmbedMaterialReq) GetType() int32 {
	if x != nil {
		return x.Type
	}
	return 0
}

type EmbedMaterialRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Accepted      bool                   `protobuf:"varint,1,opt,name=accepted,proto3" json:"accepted,omitempty"`
	TaskId        string                 `protobuf:"bytes,2,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"` // 异步任务 ID，可通过 GetEmbedStatus 查询进度
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EmbedMaterialRes) Reset() {
	*x = EmbedMaterialRes{}
	mi := &file_agent_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EmbedMaterialRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmbedMaterialRes) ProtoMessage() {}

func (x *EmbedMaterialRes) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmbedMaterialRes.ProtoReflect.Descriptor instead.
func (*EmbedMaterialRes) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{4}
}

func (x *EmbedMaterialRes) GetAccepted() bool {
	if x != nil {
		return x.Accepted
	}
	return false
}

func (x *EmbedMaterialRes) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

type GetEmbedStatusReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MaterialId    int64                  `protobuf:"varint,1,opt,name=material_id,json=materialId,proto3" json:"material_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetEmbedStatusReq) Reset() {
	*x = GetEmbedStatusReq{}
	mi := &file_agent_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetEmbedStatusReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetEmbedStatusReq) ProtoMessage() {}

func (x *GetEmbedStatusReq) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetEmbedStatusReq.ProtoReflect.Descriptor instead.
func (*GetEmbedStatusReq) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{5}
}

func (x *GetEmbedStatusReq) GetMaterialId() int64 {
	if x != nil {
		return x.MaterialId
	}
	return 0
}

type GetEmbedStatusRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AiStatus      int32                  `protobuf:"varint,1,opt,name=ai_status,json=aiStatus,proto3" json:"ai_status,omitempty"` // 0:未处理 1:处理中 2:已完成 3:失败
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetEmbedStatusRes) Reset() {
	*x = GetEmbedStatusRes{}
	mi := &file_agent_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetEmbedStatusRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetEmbedStatusRes) ProtoMessage() {}

func (x *GetEmbedStatusRes) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetEmbedStatusRes.ProtoReflect.Descriptor instead.
func (*GetEmbedStatusRes) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{6}
}

func (x *GetEmbedStatusRes) GetAiStatus() int32 {
	if x != nil {
		return x.AiStatus
	}
	return 0
}

func (x *GetEmbedStatusRes) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type AskQuestionReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CourseId      int64                  `protobuf:"varint,1,opt,name=course_id,json=courseId,proto3" json:"course_id,omitempty"`
	UserId        int64                  `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Question      string                 `protobuf:"bytes,3,opt,name=question,proto3" json:"question,omitempty"`
	History       []string               `protobuf:"bytes,4,rep,name=history,proto3" json:"history,omitempty"`
	SessionId     string                 `protobuf:"bytes,5,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"` // 多轮对话标识；为空则服务端新建会话并在首帧 StreamDelta 中返回
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AskQuestionReq) Reset() {
	*x = AskQuestionReq{}
	mi := &file_agent_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AskQuestionReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AskQuestionReq) ProtoMessage() {}

func (x *AskQuestionReq) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AskQuestionReq.ProtoReflect.Descriptor instead.
func (*AskQuestionReq) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{7}
}

func (x *AskQuestionReq) GetCourseId() int64 {
	if x != nil {
		return x.CourseId
	}
	return 0
}

func (x *AskQuestionReq) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *AskQuestionReq) GetQuestion() string {
	if x != nil {
		return x.Question
	}
	return ""
}

func (x *AskQuestionReq) GetHistory() []string {
	if x != nil {
		return x.History
	}
	return nil
}

func (x *AskQuestionReq) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

type AskQuestionRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Answer        string                 `protobuf:"bytes,1,opt,name=answer,proto3" json:"answer,omitempty"`
	Sources       []string               `protobuf:"bytes,2,rep,name=sources,proto3" json:"sources,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AskQuestionRes) Reset() {
	*x = AskQuestionRes{}
	mi := &file_agent_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AskQuestionRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AskQuestionRes) ProtoMessage() {}

func (x *AskQuestionRes) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AskQuestionRes.ProtoReflect.Descriptor instead.
func (*AskQuestionRes) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{8}
}

func (x *AskQuestionRes) GetAnswer() string {
	if x != nil {
		return x.Answer
	}
	return ""
}

func (x *AskQuestionRes) GetSources() []string {
	if x != nil {
		return x.Sources
	}
	return nil
}

type GenerateQuestionsReq struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	CourseId        int64                  `protobuf:"varint,1,opt,name=course_id,json=courseId,proto3" json:"course_id,omitempty"`
	KnowledgePoints string                 `protobuf:"bytes,2,opt,name=knowledge_points,json=knowledgePoints,proto3" json:"knowledge_points,omitempty"`
	Count           int32                  `protobuf:"varint,3,opt,name=count,proto3" json:"count,omitempty"`
	Type            int32                  `protobuf:"varint,4,opt,name=type,proto3" json:"type,omitempty"`
	Difficulty      int32                  `protobuf:"varint,5,opt,name=difficulty,proto3" json:"difficulty,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *GenerateQuestionsReq) Reset() {
	*x = GenerateQuestionsReq{}
	mi := &file_agent_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenerateQuestionsReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateQuestionsReq) ProtoMessage() {}

func (x *GenerateQuestionsReq) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerateQuestionsReq.ProtoReflect.Descriptor instead.
func (*GenerateQuestionsReq) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{9}
}

func (x *GenerateQuestionsReq) GetCourseId() int64 {
	if x != nil {
		return x.CourseId
	}
	return 0
}

func (x *GenerateQuestionsReq) GetKnowledgePoints() string {
	if x != nil {
		return x.KnowledgePoints
	}
	return ""
}

func (x *GenerateQuestionsReq) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

func (x *GenerateQuestionsReq) GetType() int32 {
	if x != nil {
		return x.Type
	}
	return 0
}

func (x *GenerateQuestionsReq) GetDifficulty() int32 {
	if x != nil {
		return x.Difficulty
	}
	return 0
}

type GenerateCourseOutlineReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CourseId      int64                  `protobuf:"varint,1,opt,name=course_id,json=courseId,proto3" json:"course_id,omitempty"`
	Topic         string                 `protobuf:"bytes,2,opt,name=topic,proto3" json:"topic,omitempty"`
	Requirements  string                 `protobuf:"bytes,3,opt,name=requirements,proto3" json:"requirements,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GenerateCourseOutlineReq) Reset() {
	*x = GenerateCourseOutlineReq{}
	mi := &file_agent_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenerateCourseOutlineReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateCourseOutlineReq) ProtoMessage() {}

func (x *GenerateCourseOutlineReq) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerateCourseOutlineReq.ProtoReflect.Descriptor instead.
func (*GenerateCourseOutlineReq) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{10}
}

func (x *GenerateCourseOutlineReq) GetCourseId() int64 {
	if x != nil {
		return x.CourseId
	}
	return 0
}

func (x *GenerateCourseOutlineReq) GetTopic() string {
	if x != nil {
		return x.Topic
	}
	return ""
}

func (x *GenerateCourseOutlineReq) GetRequirements() string {
	if x != nil {
		return x.Requirements
	}
	return ""
}

type GenerateCoursewareReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChapterId     int64                  `protobuf:"varint,1,opt,name=chapter_id,json=chapterId,proto3" json:"chapter_id,omitempty"`
	Requirements  string                 `protobuf:"bytes,2,opt,name=requirements,proto3" json:"requirements,omitempty"`
	UserId        int64                  `protobuf:"varint,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`         // 用于 session 隔离
	SessionId     string                 `protobuf:"bytes,4,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"` // 多轮对话标识；为空则服务端新建会话并在首帧 StreamDelta 中返回
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GenerateCoursewareReq) Reset() {
	*x = GenerateCoursewareReq{}
	mi := &file_agent_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenerateCoursewareReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateCoursewareReq) ProtoMessage() {}

func (x *GenerateCoursewareReq) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerateCoursewareReq.ProtoReflect.Descriptor instead.
func (*GenerateCoursewareReq) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{11}
}

func (x *GenerateCoursewareReq) GetChapterId() int64 {
	if x != nil {
		return x.ChapterId
	}
	return 0
}

func (x *GenerateCoursewareReq) GetRequirements() string {
	if x != nil {
		return x.Requirements
	}
	return ""
}

func (x *GenerateCoursewareReq) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *GenerateCoursewareReq) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

type GenerateTaskRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GenerateTaskRes) Reset() {
	*x = GenerateTaskRes{}
	mi := &file_agent_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenerateTaskRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateTaskRes) ProtoMessage() {}

func (x *GenerateTaskRes) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerateTaskRes.ProtoReflect.Descriptor instead.
func (*GenerateTaskRes) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{12}
}

func (x *GenerateTaskRes) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

type GetTaskStatusReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTaskStatusReq) Reset() {
	*x = GetTaskStatusReq{}
	mi := &file_agent_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTaskStatusReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTaskStatusReq) ProtoMessage() {}

func (x *GetTaskStatusReq) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTaskStatusReq.ProtoReflect.Descriptor instead.
func (*GetTaskStatusReq) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{13}
}

func (x *GetTaskStatusReq) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

type GetTaskStatusRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        int32                  `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"` // 0:处理中 1:已完成 2:失败
	Result        string                 `protobuf:"bytes,2,opt,name=result,proto3" json:"result,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTaskStatusRes) Reset() {
	*x = GetTaskStatusRes{}
	mi := &file_agent_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTaskStatusRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTaskStatusRes) ProtoMessage() {}

func (x *GetTaskStatusRes) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTaskStatusRes.ProtoReflect.Descriptor instead.
func (*GetTaskStatusRes) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{14}
}

func (x *GetTaskStatusRes) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *GetTaskStatusRes) GetResult() string {
	if x != nil {
		return x.Result
	}
	return ""
}

func (x *GetTaskStatusRes) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_agent_proto protoreflect.FileDescriptor

const file_agent_proto_rawDesc = "" +
	"\n" +
	"\vagent.proto\x12\x05agent\"x\n" +
	"\vStreamDelta\x12\x14\n" +
	"\x05delta\x18\x01 \x01(\tR\x05delta\x12\x18\n" +
	"\asources\x18\x02 \x03(\tR\asources\x12\x1a\n" +
	"\bfinished\x18\x03 \x01(\bR\bfinished\x12\x1d\n" +
	"\n" +
	"session_id\x18\x04 \x01(\tR\tsessionId\"\x8f\x02\n" +
	"\x12GradeSubjectiveReq\x12\x1b\n" +
	"\trecord_id\x18\x01 \x01(\x03R\brecordId\x12\x1f\n" +
	"\vquestion_id\x18\x02 \x01(\x03R\n" +
	"questionId\x12)\n" +
	"\x10question_content\x18\x03 \x01(\tR\x0fquestionContent\x12'\n" +
	"\x0fstandard_answer\x18\x04 \x01(\tR\x0estandardAnswer\x12)\n" +
	"\x10knowledge_points\x18\x05 \x01(\tR\x0fknowledgePoints\x12\x1f\n" +
	"\vuser_answer\x18\x06 \x01(\tR\n" +
	"userAnswer\x12\x1b\n" +
	"\tmax_score\x18\a \x01(\tR\bmaxScore\"\x89\x01\n" +
	"\x12GradeSubjectiveRes\x12\x1f\n" +
	"\vquestion_id\x18\x01 \x01(\x03R\n" +
	"questionId\x12\x14\n" +
	"\x05score\x18\x02 \x01(\tR\x05score\x12\x1d\n" +
	"\n" +
	"is_correct\x18\x03 \x01(\x05R\tisCorrect\x12\x1d\n" +
	"\n" +
	"ai_comment\x18\x04 \x01(\tR\taiComment\"\x8c\x01\n" +
	"\x10EmbedMaterialReq\x12\x1f\n" +
	"\vmaterial_id\x18\x01 \x01(\x03R\n" +
	"materialId\x12\x1b\n" +
	"\tcourse_id\x18\x02 \x01(\x03R\bcourseId\x12\x14\n" +
	"\x05title\x18\x03 \x01(\tR\x05title\x12\x10\n" +
	"\x03url\x18\x04 \x01(\tR\x03url\x12\x12\n" +
	"\x04type\x18\x05 \x01(\x05R\x04type\"G\n" +
	"\x10EmbedMaterialRes\x12\x1a\n" +
	"\baccepted\x18\x01 \x01(\bR\baccepted\x12\x17\n" +
	"\atask_id\x18\x02 \x01(\tR\x06taskId\"4\n" +
	"\x11GetEmbedStatusReq\x12\x1f\n" +
	"\vmaterial_id\x18\x01 \x01(\x03R\n" +
	"materialId\"J\n" +
	"\x11GetEmbedStatusRes\x12\x1b\n" +
	"\tai_status\x18\x01 \x01(\x05R\baiStatus\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\x9b\x01\n" +
	"\x0eAskQuestionReq\x12\x1b\n" +
	"\tcourse_id\x18\x01 \x01(\x03R\bcourseId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\x03R\x06userId\x12\x1a\n" +
	"\bquestion\x18\x03 \x01(\tR\bquestion\x12\x18\n" +
	"\ahistory\x18\x04 \x03(\tR\ahistory\x12\x1d\n" +
	"\n" +
	"session_id\x18\x05 \x01(\tR\tsessionId\"B\n" +
	"\x0eAskQuestionRes\x12\x16\n" +
	"\x06answer\x18\x01 \x01(\tR\x06answer\x12\x18\n" +
	"\asources\x18\x02 \x03(\tR\asources\"\xa8\x01\n" +
	"\x14GenerateQuestionsReq\x12\x1b\n" +
	"\tcourse_id\x18\x01 \x01(\x03R\bcourseId\x12)\n" +
	"\x10knowledge_points\x18\x02 \x01(\tR\x0fknowledgePoints\x12\x14\n" +
	"\x05count\x18\x03 \x01(\x05R\x05count\x12\x12\n" +
	"\x04type\x18\x04 \x01(\x05R\x04type\x12\x1e\n" +
	"\n" +
	"difficulty\x18\x05 \x01(\x05R\n" +
	"difficulty\"q\n" +
	"\x18GenerateCourseOutlineReq\x12\x1b\n" +
	"\tcourse_id\x18\x01 \x01(\x03R\bcourseId\x12\x14\n" +
	"\x05topic\x18\x02 \x01(\tR\x05topic\x12\"\n" +
	"\frequirements\x18\x03 \x01(\tR\frequirements\"\x92\x01\n" +
	"\x15GenerateCoursewareReq\x12\x1d\n" +
	"\n" +
	"chapter_id\x18\x01 \x01(\x03R\tchapterId\x12\"\n" +
	"\frequirements\x18\x02 \x01(\tR\frequirements\x12\x17\n" +
	"\auser_id\x18\x03 \x01(\x03R\x06userId\x12\x1d\n" +
	"\n" +
	"session_id\x18\x04 \x01(\tR\tsessionId\"*\n" +
	"\x0fGenerateTaskRes\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\"+\n" +
	"\x10GetTaskStatusReq\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\"\\\n" +
	"\x10GetTaskStatusRes\x12\x16\n" +
	"\x06status\x18\x01 \x01(\x05R\x06status\x12\x16\n" +
	"\x06result\x18\x02 \x01(\tR\x06result\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage2\xda\x05\n" +
	"\fAgentService\x12G\n" +
	"\x0fGradeSubjective\x12\x19.agent.GradeSubjectiveReq\x1a\x19.agent.GradeSubjectiveRes\x12A\n" +
	"\rEmbedMaterial\x12\x17.agent.EmbedMaterialReq\x1a\x17.agent.EmbedMaterialRes\x12D\n" +
	"\x0eGetEmbedStatus\x12\x18.agent.GetEmbedStatusReq\x1a\x18.agent.GetEmbedStatusRes\x12;\n" +
	"\vAskQuestion\x12\x15.agent.AskQuestionReq\x1a\x15.agent.AskQuestionRes\x12@\n" +
	"\x11AskQuestionStream\x12\x15.agent.AskQuestionReq\x1a\x12.agent.StreamDelta0\x01\x12H\n" +
	"\x11GenerateQuestions\x12\x1b.agent.GenerateQuestionsReq\x1a\x16.agent.GenerateTaskRes\x12P\n" +
	"\x15GenerateCourseOutline\x12\x1f.agent.GenerateCourseOutlineReq\x1a\x16.agent.GenerateTaskRes\x12J\n" +
	"\x12GenerateCourseware\x12\x1c.agent.GenerateCoursewareReq\x1a\x16.agent.GenerateTaskRes\x12N\n" +
	"\x18GenerateCoursewareStream\x12\x1c.agent.GenerateCoursewareReq\x1a\x12.agent.StreamDelta0\x01\x12A\n" +
	"\rGetTaskStatus\x12\x17.agent.GetTaskStatusReq\x1a\x17.agent.GetTaskStatusResB\vZ\t./agentpbb\x06proto3"

var (
	file_agent_proto_rawDescOnce sync.Once
	file_agent_proto_rawDescData []byte
)

func file_agent_proto_rawDescGZIP() []byte {
	file_agent_proto_rawDescOnce.Do(func() {
		file_agent_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_agent_proto_rawDesc), len(file_agent_proto_rawDesc)))
	})
	return file_agent_proto_rawDescData
}

var file_agent_proto_msgTypes = make([]protoimpl.MessageInfo, 15)
var file_agent_proto_goTypes = []any{
	(*StreamDelta)(nil),              // 0: agent.StreamDelta
	(*GradeSubjectiveReq)(nil),       // 1: agent.GradeSubjectiveReq
	(*GradeSubjectiveRes)(nil),       // 2: agent.GradeSubjectiveRes
	(*EmbedMaterialReq)(nil),         // 3: agent.EmbedMaterialReq
	(*EmbedMaterialRes)(nil),         // 4: agent.EmbedMaterialRes
	(*GetEmbedStatusReq)(nil),        // 5: agent.GetEmbedStatusReq
	(*GetEmbedStatusRes)(nil),        // 6: agent.GetEmbedStatusRes
	(*AskQuestionReq)(nil),           // 7: agent.AskQuestionReq
	(*AskQuestionRes)(nil),           // 8: agent.AskQuestionRes
	(*GenerateQuestionsReq)(nil),     // 9: agent.GenerateQuestionsReq
	(*GenerateCourseOutlineReq)(nil), // 10: agent.GenerateCourseOutlineReq
	(*GenerateCoursewareReq)(nil),    // 11: agent.GenerateCoursewareReq
	(*GenerateTaskRes)(nil),          // 12: agent.GenerateTaskRes
	(*GetTaskStatusReq)(nil),         // 13: agent.GetTaskStatusReq
	(*GetTaskStatusRes)(nil),         // 14: agent.GetTaskStatusRes
}
var file_agent_proto_depIdxs = []int32{
	1,  // 0: agent.AgentService.GradeSubjective:input_type -> agent.GradeSubjectiveReq
	3,  // 1: agent.AgentService.EmbedMaterial:input_type -> agent.EmbedMaterialReq
	5,  // 2: agent.AgentService.GetEmbedStatus:input_type -> agent.GetEmbedStatusReq
	7,  // 3: agent.AgentService.AskQuestion:input_type -> agent.AskQuestionReq
	7,  // 4: agent.AgentService.AskQuestionStream:input_type -> agent.AskQuestionReq
	9,  // 5: agent.AgentService.GenerateQuestions:input_type -> agent.GenerateQuestionsReq
	10, // 6: agent.AgentService.GenerateCourseOutline:input_type -> agent.GenerateCourseOutlineReq
	11, // 7: agent.AgentService.GenerateCourseware:input_type -> agent.GenerateCoursewareReq
	11, // 8: agent.AgentService.GenerateCoursewareStream:input_type -> agent.GenerateCoursewareReq
	13, // 9: agent.AgentService.GetTaskStatus:input_type -> agent.GetTaskStatusReq
	2,  // 10: agent.AgentService.GradeSubjective:output_type -> agent.GradeSubjectiveRes
	4,  // 11: agent.AgentService.EmbedMaterial:output_type -> agent.EmbedMaterialRes
	6,  // 12: agent.AgentService.GetEmbedStatus:output_type -> agent.GetEmbedStatusRes
	8,  // 13: agent.AgentService.AskQuestion:output_type -> agent.AskQuestionRes
	0,  // 14: agent.AgentService.AskQuestionStream:output_type -> agent.StreamDelta
	12, // 15: agent.AgentService.GenerateQuestions:output_type -> agent.GenerateTaskRes
	12, // 16: agent.AgentService.GenerateCourseOutline:output_type -> agent.GenerateTaskRes
	12, // 17: agent.AgentService.GenerateCourseware:output_type -> agent.GenerateTaskRes
	0,  // 18: agent.AgentService.GenerateCoursewareStream:output_type -> agent.StreamDelta
	14, // 19: agent.AgentService.GetTaskStatus:output_type -> agent.GetTaskStatusRes
	10, // [10:20] is the sub-list for method output_type
	0,  // [0:10] is the sub-list for method input_type
	0,  // [0:0] is the sub-list for extension type_name
	0,  // [0:0] is the sub-list for extension extendee
	0,  // [0:0] is the sub-list for field type_name
}

func init() { file_agent_proto_init() }
func file_agent_proto_init() {
	if File_agent_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_agent_proto_rawDesc), len(file_agent_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   15,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_agent_proto_goTypes,
		DependencyIndexes: file_agent_proto_depIdxs,
		MessageInfos:      file_agent_proto_msgTypes,
	}.Build()
	File_agent_proto = out.File
	file_agent_proto_goTypes = nil
	file_agent_proto_depIdxs = nil
}
