// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2
// Source: ai.proto

package server

import (
	"context"

	"teaching-backend/application/ai/rpc/internal/logic"
	"teaching-backend/application/ai/rpc/internal/svc"
	"teaching-backend/application/ai/rpc/pb"
)

type AiBridgeServer struct {
	svcCtx *svc.ServiceContext
	pb.UnimplementedAiBridgeServer
}

func NewAiBridgeServer(svcCtx *svc.ServiceContext) *AiBridgeServer {
	return &AiBridgeServer{
		svcCtx: svcCtx,
	}
}

func (s *AiBridgeServer) GradeSubjectiveQuestion(ctx context.Context, in *pb.GradeSubjectiveQuestionReq) (*pb.GradeSubjectiveQuestionRes, error) {
	l := logic.NewGradeSubjectiveQuestionLogic(ctx, s.svcCtx)
	return l.GradeSubjectiveQuestion(in)
}

func (s *AiBridgeServer) GradeExamSubjective(ctx context.Context, in *pb.GradeExamSubjectiveReq) (*pb.GradeExamSubjectiveRes, error) {
	l := logic.NewGradeExamSubjectiveLogic(ctx, s.svcCtx)
	return l.GradeExamSubjective(in)
}

func (s *AiBridgeServer) EmbedMaterial(ctx context.Context, in *pb.EmbedMaterialReq) (*pb.EmbedMaterialRes, error) {
	l := logic.NewEmbedMaterialLogic(ctx, s.svcCtx)
	return l.EmbedMaterial(in)
}

func (s *AiBridgeServer) GetEmbedStatus(ctx context.Context, in *pb.GetEmbedStatusReq) (*pb.GetEmbedStatusRes, error) {
	l := logic.NewGetEmbedStatusLogic(ctx, s.svcCtx)
	return l.GetEmbedStatus(in)
}

func (s *AiBridgeServer) AskQuestion(ctx context.Context, in *pb.AskQuestionReq) (*pb.AskQuestionRes, error) {
	l := logic.NewAskQuestionLogic(ctx, s.svcCtx)
	return l.AskQuestion(in)
}

func (s *AiBridgeServer) AskQuestionStream(in *pb.AskQuestionReq, stream pb.AiBridge_AskQuestionStreamServer) error {
	l := logic.NewAskQuestionStreamLogic(stream.Context(), s.svcCtx)
	return l.AskQuestionStream(in, stream)
}

func (s *AiBridgeServer) GenerateQuestions(ctx context.Context, in *pb.GenerateQuestionsReq) (*pb.GenerateTaskRes, error) {
	l := logic.NewGenerateQuestionsLogic(ctx, s.svcCtx)
	return l.GenerateQuestions(in)
}

func (s *AiBridgeServer) GenerateCourseOutline(ctx context.Context, in *pb.GenerateCourseOutlineReq) (*pb.GenerateTaskRes, error) {
	l := logic.NewGenerateCourseOutlineLogic(ctx, s.svcCtx)
	return l.GenerateCourseOutline(in)
}

func (s *AiBridgeServer) GenerateCourseware(ctx context.Context, in *pb.GenerateCoursewareReq) (*pb.GenerateTaskRes, error) {
	l := logic.NewGenerateCoursewareLogic(ctx, s.svcCtx)
	return l.GenerateCourseware(in)
}

func (s *AiBridgeServer) GenerateCoursewareStream(in *pb.GenerateCoursewareReq, stream pb.AiBridge_GenerateCoursewareStreamServer) error {
	l := logic.NewGenerateCoursewareStreamLogic(stream.Context(), s.svcCtx)
	return l.GenerateCoursewareStream(in, stream)
}

func (s *AiBridgeServer) GetAiTaskStatus(ctx context.Context, in *pb.GetAiTaskStatusReq) (*pb.GetAiTaskStatusRes, error) {
	l := logic.NewGetAiTaskStatusLogic(ctx, s.svcCtx)
	return l.GetAiTaskStatus(in)
}
