// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2
// Source: user.proto

package server

import (
	"context"

	"teaching-backend/application/user/rpc/internal/logic"
	"teaching-backend/application/user/rpc/internal/svc"
	"teaching-backend/application/user/rpc/pb"
)

type UserServer struct {
	svcCtx *svc.ServiceContext
	pb.UnimplementedUserServer
}

func NewUserServer(svcCtx *svc.ServiceContext) *UserServer {
	return &UserServer{
		svcCtx: svcCtx,
	}
}

// 注册
func (s *UserServer) Register(ctx context.Context, in *pb.RegisterReq) (*pb.RegisterRes, error) {
	l := logic.NewRegisterLogic(ctx, s.svcCtx)
	return l.Register(in)
}

// 根据ID获取用户信息
func (s *UserServer) FindById(ctx context.Context, in *pb.FindByIdReq) (*pb.FindByIdRes, error) {
	l := logic.NewFindByIdLogic(ctx, s.svcCtx)
	return l.FindById(in)
}

// 根据邮箱获取用户信息
func (s *UserServer) FindByEmail(ctx context.Context, in *pb.FindByEmailReq) (*pb.FindByEmailRes, error) {
	l := logic.NewFindByEmailLogic(ctx, s.svcCtx)
	return l.FindByEmail(in)
}

// 更新用户信息
func (s *UserServer) UpdateUser(ctx context.Context, in *pb.UpdateUserReq) (*pb.UpdateUserRes, error) {
	l := logic.NewUpdateUserLogic(ctx, s.svcCtx)
	return l.UpdateUser(in)
}
