// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2
// Source: user.proto

package server

import (
	"context"

	"teaching-backend/application/user/rpc/internal/logic"
	"teaching-backend/application/user/rpc/internal/svc"
	"teaching-backend/application/user/rpc/pb"
)

type UserServer struct {
	svcCtx *svc.ServiceContext
	pb.UnimplementedUserServer
}

func NewUserServer(svcCtx *svc.ServiceContext) *UserServer {
	return &UserServer{
		svcCtx: svcCtx,
	}
}

// 注册
func (s *UserServer) Register(ctx context.Context, in *pb.RegisterReq) (*pb.RegisterRes, error) {
	l := logic.NewRegisterLogic(ctx, s.svcCtx)
	return l.Register(in)
}

// 登录
func (s *UserServer) Login(ctx context.Context, in *pb.LoginReq) (*pb.LoginRes, error) {
	l := logic.NewLoginLogic(ctx, s.svcCtx)
	return l.Login(in)
}

// 根据ID获取用户信息
func (s *UserServer) FindById(ctx context.Context, in *pb.FindByIdReq) (*pb.FindByIdRes, error) {
	l := logic.NewFindByIdLogic(ctx, s.svcCtx)
	return l.FindById(in)
}

// 根据手机号获取用户信息
func (s *UserServer) FindByMobile(ctx context.Context, in *pb.FindByMobileReq) (*pb.FindByMobileRes, error) {
	l := logic.NewFindByMobileLogic(ctx, s.svcCtx)
	return l.FindByMobile(in)
}
