// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v3.19.4
// source: exam.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Exam_CreateQuestion_FullMethodName     = "/exam.Exam/CreateQuestion"
	Exam_QuestionList_FullMethodName       = "/exam.Exam/QuestionList"
	Exam_QuestionDetail_FullMethodName     = "/exam.Exam/QuestionDetail"
	Exam_UpdateQuestion_FullMethodName     = "/exam.Exam/UpdateQuestion"
	Exam_DeleteQuestion_FullMethodName     = "/exam.Exam/DeleteQuestion"
	Exam_CreateExam_FullMethodName         = "/exam.Exam/CreateExam"
	Exam_ExamList_FullMethodName           = "/exam.Exam/ExamList"
	Exam_ExamDetail_FullMethodName         = "/exam.Exam/ExamDetail"
	Exam_UpdateExam_FullMethodName         = "/exam.Exam/UpdateExam"
	Exam_DeleteExam_FullMethodName         = "/exam.Exam/DeleteExam"
	Exam_AddExamQuestion_FullMethodName    = "/exam.Exam/AddExamQuestion"
	Exam_RemoveExamQuestion_FullMethodName = "/exam.Exam/RemoveExamQuestion"
	Exam_StartExam_FullMethodName          = "/exam.Exam/StartExam"
	Exam_SubmitExam_FullMethodName         = "/exam.Exam/SubmitExam"
	Exam_SaveAnswerSnapshot_FullMethodName = "/exam.Exam/SaveAnswerSnapshot"
	Exam_GetExamResult_FullMethodName      = "/exam.Exam/GetExamResult"
	Exam_GetUserAnswers_FullMethodName     = "/exam.Exam/GetUserAnswers"
)

// ExamClient is the client API for Exam service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// 考试服务
type ExamClient interface {
	// ========== 题库管理 ==========
	// 创建题目
	CreateQuestion(ctx context.Context, in *CreateQuestionReq, opts ...grpc.CallOption) (*CreateQuestionRes, error)
	// 题目列表
	QuestionList(ctx context.Context, in *QuestionListReq, opts ...grpc.CallOption) (*QuestionListRes, error)
	// 题目详情
	QuestionDetail(ctx context.Context, in *QuestionDetailReq, opts ...grpc.CallOption) (*QuestionDetailRes, error)
	// 更新题目
	UpdateQuestion(ctx context.Context, in *UpdateQuestionReq, opts ...grpc.CallOption) (*UpdateQuestionRes, error)
	// 删除题目
	DeleteQuestion(ctx context.Context, in *DeleteQuestionReq, opts ...grpc.CallOption) (*DeleteQuestionRes, error)
	// ========== 试卷管理 ==========
	// 创建试卷
	CreateExam(ctx context.Context, in *CreateExamReq, opts ...grpc.CallOption) (*CreateExamRes, error)
	// 试卷列表
	ExamList(ctx context.Context, in *ExamListReq, opts ...grpc.CallOption) (*ExamListRes, error)
	// 试卷详情(含题目)
	ExamDetail(ctx context.Context, in *ExamDetailReq, opts ...grpc.CallOption) (*ExamDetailRes, error)
	// 更新试卷
	UpdateExam(ctx context.Context, in *UpdateExamReq, opts ...grpc.CallOption) (*UpdateExamRes, error)
	// 删除试卷
	DeleteExam(ctx context.Context, in *DeleteExamReq, opts ...grpc.CallOption) (*DeleteExamRes, error)
	// 给试卷添加题目
	AddExamQuestion(ctx context.Context, in *AddExamQuestionReq, opts ...grpc.CallOption) (*AddExamQuestionRes, error)
	// 移除试卷题目
	RemoveExamQuestion(ctx context.Context, in *RemoveExamQuestionReq, opts ...grpc.CallOption) (*RemoveExamQuestionRes, error)
	// ========== 考试作答 ==========
	// 开始考试(创建答卷记录)
	StartExam(ctx context.Context, in *StartExamReq, opts ...grpc.CallOption) (*StartExamRes, error)
	// 提交答卷
	SubmitExam(ctx context.Context, in *SubmitExamReq, opts ...grpc.CallOption) (*SubmitExamRes, error)
	// 考试心跳与答案快照保存 (存Redis)
	SaveAnswerSnapshot(ctx context.Context, in *SaveAnswerSnapshotReq, opts ...grpc.CallOption) (*SaveAnswerSnapshotRes, error)
	// 获取考试结果
	GetExamResult(ctx context.Context, in *GetExamResultReq, opts ...grpc.CallOption) (*GetExamResultRes, error)
	// 获取学生答题明细
	GetUserAnswers(ctx context.Context, in *GetUserAnswersReq, opts ...grpc.CallOption) (*GetUserAnswersRes, error)
}

type examClient struct {
	cc grpc.ClientConnInterface
}

func NewExamClient(cc grpc.ClientConnInterface) ExamClient {
	return &examClient{cc}
}

func (c *examClient) CreateQuestion(ctx context.Context, in *CreateQuestionReq, opts ...grpc.CallOption) (*CreateQuestionRes, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateQuestionRes)
	err := c.cc.Invoke(ctx, Exam_CreateQuestion_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *examClient) QuestionList(ctx context.Context, in *QuestionListReq, opts ...grpc.CallOption) (*QuestionListRes, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(QuestionListRes)
	err := c.cc.Invoke(ctx, Exam_QuestionList_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *examClient) QuestionDetail(ctx context.Context, in *QuestionDetailReq, opts ...grpc.CallOption) (*QuestionDetailRes, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(QuestionDetailRes)
	err := c.cc.Invoke(ctx, Exam_QuestionDetail_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *examClient) UpdateQuestion(ctx context.Context, in *UpdateQuestionReq, opts ...grpc.CallOption) (*UpdateQuestionRes, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateQuestionRes)
	err := c.cc.Invoke(ctx, Exam_UpdateQuestion_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *examClient) DeleteQuestion(ctx context.Context, in *DeleteQuestionReq, opts ...grpc.CallOption) (*DeleteQuestionRes, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteQuestionRes)
	err := c.cc.Invoke(ctx, Exam_DeleteQuestion_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *examClient) CreateExam(ctx context.Context, in *CreateExamReq, opts ...grpc.CallOption) (*CreateExamRes, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateExamRes)
	err := c.cc.Invoke(ctx, Exam_CreateExam_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *examClient) ExamList(ctx context.Context, in *ExamListReq, opts ...grpc.CallOption) (*ExamListRes, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ExamListRes)
	err := c.cc.Invoke(ctx, Exam_ExamList_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *examClient) ExamDetail(ctx context.Context, in *ExamDetailReq, opts ...grpc.CallOption) (*ExamDetailRes, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ExamDetailRes)
	err := c.cc.Invoke(ctx, Exam_ExamDetail_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *examClient) UpdateExam(ctx context.Context, in *UpdateExamReq, opts ...grpc.CallOption) (*UpdateExamRes, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateExamRes)
	err := c.cc.Invoke(ctx, Exam_UpdateExam_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *examClient) DeleteExam(ctx context.Context, in *DeleteExamReq, opts ...grpc.CallOption) (*DeleteExamRes, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteExamRes)
	err := c.cc.Invoke(ctx, Exam_DeleteExam_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *examClient) AddExamQuestion(ctx context.Context, in *AddExamQuestionReq, opts ...grpc.CallOption) (*AddExamQuestionRes, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AddExamQuestionRes)
	err := c.cc.Invoke(ctx, Exam_AddExamQuestion_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *examClient) RemoveExamQuestion(ctx context.Context, in *RemoveExamQuestionReq, opts ...grpc.CallOption) (*RemoveExamQuestionRes, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RemoveExamQuestionRes)
	err := c.cc.Invoke(ctx, Exam_RemoveExamQuestion_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *examClient) StartExam(ctx context.Context, in *StartExamReq, opts ...grpc.CallOption) (*StartExamRes, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StartExamRes)
	err := c.cc.Invoke(ctx, Exam_StartExam_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *examClient) SubmitExam(ctx context.Context, in *SubmitExamReq, opts ...grpc.CallOption) (*SubmitExamRes, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SubmitExamRes)
	err := c.cc.Invoke(ctx, Exam_SubmitExam_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *examClient) SaveAnswerSnapshot(ctx context.Context, in *SaveAnswerSnapshotReq, opts ...grpc.CallOption) (*SaveAnswerSnapshotRes, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SaveAnswerSnapshotRes)
	err := c.cc.Invoke(ctx, Exam_SaveAnswerSnapshot_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *examClient) GetExamResult(ctx context.Context, in *GetExamResultReq, opts ...grpc.CallOption) (*GetExamResultRes, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetExamResultRes)
	err := c.cc.Invoke(ctx, Exam_GetExamResult_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *examClient) GetUserAnswers(ctx context.Context, in *GetUserAnswersReq, opts ...grpc.CallOption) (*GetUserAnswersRes, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetUserAnswersRes)
	err := c.cc.Invoke(ctx, Exam_GetUserAnswers_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ExamServer is the server API for Exam service.
// All implementations must embed UnimplementedExamServer
// for forward compatibility.
//
// 考试服务
type ExamServer interface {
	// ========== 题库管理 ==========
	// 创建题目
	CreateQuestion(context.Context, *CreateQuestionReq) (*CreateQuestionRes, error)
	// 题目列表
	QuestionList(context.Context, *QuestionListReq) (*QuestionListRes, error)
	// 题目详情
	QuestionDetail(context.Context, *QuestionDetailReq) (*QuestionDetailRes, error)
	// 更新题目
	UpdateQuestion(context.Context, *UpdateQuestionReq) (*UpdateQuestionRes, error)
	// 删除题目
	DeleteQuestion(context.Context, *DeleteQuestionReq) (*DeleteQuestionRes, error)
	// ========== 试卷管理 ==========
	// 创建试卷
	CreateExam(context.Context, *CreateExamReq) (*CreateExamRes, error)
	// 试卷列表
	ExamList(context.Context, *ExamListReq) (*ExamListRes, error)
	// 试卷详情(含题目)
	ExamDetail(context.Context, *ExamDetailReq) (*ExamDetailRes, error)
	// 更新试卷
	UpdateExam(context.Context, *UpdateExamReq) (*UpdateExamRes, error)
	// 删除试卷
	DeleteExam(context.Context, *DeleteExamReq) (*DeleteExamRes, error)
	// 给试卷添加题目
	AddExamQuestion(context.Context, *AddExamQuestionReq) (*AddExamQuestionRes, error)
	// 移除试卷题目
	RemoveExamQuestion(context.Context, *RemoveExamQuestionReq) (*RemoveExamQuestionRes, error)
	// ========== 考试作答 ==========
	// 开始考试(创建答卷记录)
	StartExam(context.Context, *StartExamReq) (*StartExamRes, error)
	// 提交答卷
	SubmitExam(context.Context, *SubmitExamReq) (*SubmitExamRes, error)
	// 考试心跳与答案快照保存 (存Redis)
	SaveAnswerSnapshot(context.Context, *SaveAnswerSnapshotReq) (*SaveAnswerSnapshotRes, error)
	// 获取考试结果
	GetExamResult(context.Context, *GetExamResultReq) (*GetExamResultRes, error)
	// 获取学生答题明细
	GetUserAnswers(context.Context, *GetUserAnswersReq) (*GetUserAnswersRes, error)
	mustEmbedUnimplementedExamServer()
}

// UnimplementedExamServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedExamServer struct{}

func (UnimplementedExamServer) CreateQuestion(context.Context, *CreateQuestionReq) (*CreateQuestionRes, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateQuestion not implemented")
}
func (UnimplementedExamServer) QuestionList(context.Context, *QuestionListReq) (*QuestionListRes, error) {
	return nil, status.Error(codes.Unimplemented, "method QuestionList not implemented")
}
func (UnimplementedExamServer) QuestionDetail(context.Context, *QuestionDetailReq) (*QuestionDetailRes, error) {
	return nil, status.Error(codes.Unimplemented, "method QuestionDetail not implemented")
}
func (UnimplementedExamServer) UpdateQuestion(context.Context, *UpdateQuestionReq) (*UpdateQuestionRes, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateQuestion not implemented")
}
func (UnimplementedExamServer) DeleteQuestion(context.Context, *DeleteQuestionReq) (*DeleteQuestionRes, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteQuestion not implemented")
}
func (UnimplementedExamServer) CreateExam(context.Context, *CreateExamReq) (*CreateExamRes, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateExam not implemented")
}
func (UnimplementedExamServer) ExamList(context.Context, *ExamListReq) (*ExamListRes, error) {
	return nil, status.Error(codes.Unimplemented, "method ExamList not implemented")
}
func (UnimplementedExamServer) ExamDetail(context.Context, *ExamDetailReq) (*ExamDetailRes, error) {
	return nil, status.Error(codes.Unimplemented, "method ExamDetail not implemented")
}
func (UnimplementedExamServer) UpdateExam(context.Context, *UpdateExamReq) (*UpdateExamRes, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateExam not implemented")
}
func (UnimplementedExamServer) DeleteExam(context.Context, *DeleteExamReq) (*DeleteExamRes, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteExam not implemented")
}
func (UnimplementedExamServer) AddExamQuestion(context.Context, *AddExamQuestionReq) (*AddExamQuestionRes, error) {
	return nil, status.Error(codes.Unimplemented, "method AddExamQuestion not implemented")
}
func (UnimplementedExamServer) RemoveExamQuestion(context.Context, *RemoveExamQuestionReq) (*RemoveExamQuestionRes, error) {
	return nil, status.Error(codes.Unimplemented, "method RemoveExamQuestion not implemented")
}
func (UnimplementedExamServer) StartExam(context.Context, *StartExamReq) (*StartExamRes, error) {
	return nil, status.Error(codes.Unimplemented, "method StartExam not implemented")
}
func (UnimplementedExamServer) SubmitExam(context.Context, *SubmitExamReq) (*SubmitExamRes, error) {
	return nil, status.Error(codes.Unimplemented, "method SubmitExam not implemented")
}
func (UnimplementedExamServer) SaveAnswerSnapshot(context.Context, *SaveAnswerSnapshotReq) (*SaveAnswerSnapshotRes, error) {
	return nil, status.Error(codes.Unimplemented, "method SaveAnswerSnapshot not implemented")
}
func (UnimplementedExamServer) GetExamResult(context.Context, *GetExamResultReq) (*GetExamResultRes, error) {
	return nil, status.Error(codes.Unimplemented, "method GetExamResult not implemented")
}
func (UnimplementedExamServer) GetUserAnswers(context.Context, *GetUserAnswersReq) (*GetUserAnswersRes, error) {
	return nil, status.Error(codes.Unimplemented, "method GetUserAnswers not implemented")
}
func (UnimplementedExamServer) mustEmbedUnimplementedExamServer() {}
func (UnimplementedExamServer) testEmbeddedByValue()              {}

// UnsafeExamServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ExamServer will
// result in compilation errors.
type UnsafeExamServer interface {
	mustEmbedUnimplementedExamServer()
}

func RegisterExamServer(s grpc.ServiceRegistrar, srv ExamServer) {
	// If the following call panics, it indicates UnimplementedExamServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Exam_ServiceDesc, srv)
}

func _Exam_CreateQuestion_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateQuestionReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ExamServer).CreateQuestion(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Exam_CreateQuestion_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ExamServer).CreateQuestion(ctx, req.(*CreateQuestionReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Exam_QuestionList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QuestionListReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ExamServer).QuestionList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Exam_QuestionList_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ExamServer).QuestionList(ctx, req.(*QuestionListReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Exam_QuestionDetail_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QuestionDetailReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ExamServer).QuestionDetail(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Exam_QuestionDetail_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ExamServer).QuestionDetail(ctx, req.(*QuestionDetailReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Exam_UpdateQuestion_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateQuestionReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ExamServer).UpdateQuestion(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Exam_UpdateQuestion_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ExamServer).UpdateQuestion(ctx, req.(*UpdateQuestionReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Exam_DeleteQuestion_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteQuestionReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ExamServer).DeleteQuestion(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Exam_DeleteQuestion_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ExamServer).DeleteQuestion(ctx, req.(*DeleteQuestionReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Exam_CreateExam_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateExamReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ExamServer).CreateExam(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Exam_CreateExam_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ExamServer).CreateExam(ctx, req.(*CreateExamReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Exam_ExamList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ExamListReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ExamServer).ExamList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Exam_ExamList_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ExamServer).ExamList(ctx, req.(*ExamListReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Exam_ExamDetail_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ExamDetailReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ExamServer).ExamDetail(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Exam_ExamDetail_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ExamServer).ExamDetail(ctx, req.(*ExamDetailReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Exam_UpdateExam_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateExamReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ExamServer).UpdateExam(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Exam_UpdateExam_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ExamServer).UpdateExam(ctx, req.(*UpdateExamReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Exam_DeleteExam_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteExamReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ExamServer).DeleteExam(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Exam_DeleteExam_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ExamServer).DeleteExam(ctx, req.(*DeleteExamReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Exam_AddExamQuestion_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddExamQuestionReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ExamServer).AddExamQuestion(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Exam_AddExamQuestion_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ExamServer).AddExamQuestion(ctx, req.(*AddExamQuestionReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Exam_RemoveExamQuestion_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RemoveExamQuestionReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ExamServer).RemoveExamQuestion(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Exam_RemoveExamQuestion_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ExamServer).RemoveExamQuestion(ctx, req.(*RemoveExamQuestionReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Exam_StartExam_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StartExamReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ExamServer).StartExam(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Exam_StartExam_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ExamServer).StartExam(ctx, req.(*StartExamReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Exam_SubmitExam_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SubmitExamReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ExamServer).SubmitExam(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Exam_SubmitExam_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ExamServer).SubmitExam(ctx, req.(*SubmitExamReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Exam_SaveAnswerSnapshot_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SaveAnswerSnapshotReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ExamServer).SaveAnswerSnapshot(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Exam_SaveAnswerSnapshot_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ExamServer).SaveAnswerSnapshot(ctx, req.(*SaveAnswerSnapshotReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Exam_GetExamResult_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetExamResultReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ExamServer).GetExamResult(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Exam_GetExamResult_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ExamServer).GetExamResult(ctx, req.(*GetExamResultReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Exam_GetUserAnswers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUserAnswersReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ExamServer).GetUserAnswers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Exam_GetUserAnswers_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ExamServer).GetUserAnswers(ctx, req.(*GetUserAnswersReq))
	}
	return interceptor(ctx, in, info, handler)
}

// Exam_ServiceDesc is the grpc.ServiceDesc for Exam service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Exam_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "exam.Exam",
	HandlerType: (*ExamServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateQuestion",
			Handler:    _Exam_CreateQuestion_Handler,
		},
		{
			MethodName: "QuestionList",
			Handler:    _Exam_QuestionList_Handler,
		},
		{
			MethodName: "QuestionDetail",
			Handler:    _Exam_QuestionDetail_Handler,
		},
		{
			MethodName: "UpdateQuestion",
			Handler:    _Exam_UpdateQuestion_Handler,
		},
		{
			MethodName: "DeleteQuestion",
			Handler:    _Exam_DeleteQuestion_Handler,
		},
		{
			MethodName: "CreateExam",
			Handler:    _Exam_CreateExam_Handler,
		},
		{
			MethodName: "ExamList",
			Handler:    _Exam_ExamList_Handler,
		},
		{
			MethodName: "ExamDetail",
			Handler:    _Exam_ExamDetail_Handler,
		},
		{
			MethodName: "UpdateExam",
			Handler:    _Exam_UpdateExam_Handler,
		},
		{
			MethodName: "DeleteExam",
			Handler:    _Exam_DeleteExam_Handler,
		},
		{
			MethodName: "AddExamQuestion",
			Handler:    _Exam_AddExamQuestion_Handler,
		},
		{
			MethodName: "RemoveExamQuestion",
			Handler:    _Exam_RemoveExamQuestion_Handler,
		},
		{
			MethodName: "StartExam",
			Handler:    _Exam_StartExam_Handler,
		},
		{
			MethodName: "SubmitExam",
			Handler:    _Exam_SubmitExam_Handler,
		},
		{
			MethodName: "SaveAnswerSnapshot",
			Handler:    _Exam_SaveAnswerSnapshot_Handler,
		},
		{
			MethodName: "GetExamResult",
			Handler:    _Exam_GetExamResult_Handler,
		},
		{
			MethodName: "GetUserAnswers",
			Handler:    _Exam_GetUserAnswers_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "exam.proto",
}
