// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2
// Source: ai.proto

package aibridge

import (
	"context"

	"teaching-backend/application/ai/rpc/pb"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	AskQuestionReq              = pb.AskQuestionReq
	AskQuestionRes              = pb.AskQuestionRes
	AskQuestionStreamRes        = pb.AskQuestionStreamRes
	EmbedMaterialReq            = pb.EmbedMaterialReq
	EmbedMaterialRes            = pb.EmbedMaterialRes
	GenerateCourseOutlineReq    = pb.GenerateCourseOutlineReq
	GenerateCoursewareReq       = pb.GenerateCoursewareReq
	GenerateCoursewareStreamRes = pb.GenerateCoursewareStreamRes
	GenerateQuestionsReq        = pb.GenerateQuestionsReq
	GenerateTaskRes             = pb.GenerateTaskRes
	GeneratedQuestion           = pb.GeneratedQuestion
	GetAiTaskStatusReq          = pb.GetAiTaskStatusReq
	GetAiTaskStatusRes          = pb.GetAiTaskStatusRes
	GetEmbedStatusReq           = pb.GetEmbedStatusReq
	GetEmbedStatusRes           = pb.GetEmbedStatusRes
	GradeExamSubjectiveReq      = pb.GradeExamSubjectiveReq
	GradeExamSubjectiveRes      = pb.GradeExamSubjectiveRes
	GradeSubjectiveQuestionReq  = pb.GradeSubjectiveQuestionReq
	GradeSubjectiveQuestionRes  = pb.GradeSubjectiveQuestionRes
	SubjectiveQuestionInput     = pb.SubjectiveQuestionInput

	AiBridge interface {
		GradeSubjectiveQuestion(ctx context.Context, in *GradeSubjectiveQuestionReq, opts ...grpc.CallOption) (*GradeSubjectiveQuestionRes, error)
		GradeExamSubjective(ctx context.Context, in *GradeExamSubjectiveReq, opts ...grpc.CallOption) (*GradeExamSubjectiveRes, error)
		EmbedMaterial(ctx context.Context, in *EmbedMaterialReq, opts ...grpc.CallOption) (*EmbedMaterialRes, error)
		GetEmbedStatus(ctx context.Context, in *GetEmbedStatusReq, opts ...grpc.CallOption) (*GetEmbedStatusRes, error)
		AskQuestion(ctx context.Context, in *AskQuestionReq, opts ...grpc.CallOption) (*AskQuestionRes, error)
		AskQuestionStream(ctx context.Context, in *AskQuestionReq, opts ...grpc.CallOption) (pb.AiBridge_AskQuestionStreamClient, error)
		GenerateQuestions(ctx context.Context, in *GenerateQuestionsReq, opts ...grpc.CallOption) (*GenerateTaskRes, error)
		GenerateCourseOutline(ctx context.Context, in *GenerateCourseOutlineReq, opts ...grpc.CallOption) (*GenerateTaskRes, error)
		GenerateCourseware(ctx context.Context, in *GenerateCoursewareReq, opts ...grpc.CallOption) (*GenerateTaskRes, error)
		GenerateCoursewareStream(ctx context.Context, in *GenerateCoursewareReq, opts ...grpc.CallOption) (pb.AiBridge_GenerateCoursewareStreamClient, error)
		GetAiTaskStatus(ctx context.Context, in *GetAiTaskStatusReq, opts ...grpc.CallOption) (*GetAiTaskStatusRes, error)
	}

	defaultAiBridge struct {
		cli zrpc.Client
	}
)

func NewAiBridge(cli zrpc.Client) AiBridge {
	return &defaultAiBridge{
		cli: cli,
	}
}

func (m *defaultAiBridge) GradeSubjectiveQuestion(ctx context.Context, in *GradeSubjectiveQuestionReq, opts ...grpc.CallOption) (*GradeSubjectiveQuestionRes, error) {
	client := pb.NewAiBridgeClient(m.cli.Conn())
	return client.GradeSubjectiveQuestion(ctx, in, opts...)
}

func (m *defaultAiBridge) GradeExamSubjective(ctx context.Context, in *GradeExamSubjectiveReq, opts ...grpc.CallOption) (*GradeExamSubjectiveRes, error) {
	client := pb.NewAiBridgeClient(m.cli.Conn())
	return client.GradeExamSubjective(ctx, in, opts...)
}

func (m *defaultAiBridge) EmbedMaterial(ctx context.Context, in *EmbedMaterialReq, opts ...grpc.CallOption) (*EmbedMaterialRes, error) {
	client := pb.NewAiBridgeClient(m.cli.Conn())
	return client.EmbedMaterial(ctx, in, opts...)
}

func (m *defaultAiBridge) GetEmbedStatus(ctx context.Context, in *GetEmbedStatusReq, opts ...grpc.CallOption) (*GetEmbedStatusRes, error) {
	client := pb.NewAiBridgeClient(m.cli.Conn())
	return client.GetEmbedStatus(ctx, in, opts...)
}

func (m *defaultAiBridge) AskQuestion(ctx context.Context, in *AskQuestionReq, opts ...grpc.CallOption) (*AskQuestionRes, error) {
	client := pb.NewAiBridgeClient(m.cli.Conn())
	return client.AskQuestion(ctx, in, opts...)
}

func (m *defaultAiBridge) AskQuestionStream(ctx context.Context, in *AskQuestionReq, opts ...grpc.CallOption) (pb.AiBridge_AskQuestionStreamClient, error) {
	client := pb.NewAiBridgeClient(m.cli.Conn())
	return client.AskQuestionStream(ctx, in, opts...)
}

func (m *defaultAiBridge) GenerateQuestions(ctx context.Context, in *GenerateQuestionsReq, opts ...grpc.CallOption) (*GenerateTaskRes, error) {
	client := pb.NewAiBridgeClient(m.cli.Conn())
	return client.GenerateQuestions(ctx, in, opts...)
}

func (m *defaultAiBridge) GenerateCourseOutline(ctx context.Context, in *GenerateCourseOutlineReq, opts ...grpc.CallOption) (*GenerateTaskRes, error) {
	client := pb.NewAiBridgeClient(m.cli.Conn())
	return client.GenerateCourseOutline(ctx, in, opts...)
}

func (m *defaultAiBridge) GenerateCourseware(ctx context.Context, in *GenerateCoursewareReq, opts ...grpc.CallOption) (*GenerateTaskRes, error) {
	client := pb.NewAiBridgeClient(m.cli.Conn())
	return client.GenerateCourseware(ctx, in, opts...)
}

func (m *defaultAiBridge) GenerateCoursewareStream(ctx context.Context, in *GenerateCoursewareReq, opts ...grpc.CallOption) (pb.AiBridge_GenerateCoursewareStreamClient, error) {
	client := pb.NewAiBridgeClient(m.cli.Conn())
	return client.GenerateCoursewareStream(ctx, in, opts...)
}

func (m *defaultAiBridge) GetAiTaskStatus(ctx context.Context, in *GetAiTaskStatusReq, opts ...grpc.CallOption) (*GetAiTaskStatusRes, error) {
	client := pb.NewAiBridgeClient(m.cli.Conn())
	return client.GetAiTaskStatus(ctx, in, opts...)
}
