// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2

package types

type AddExamQuestionReq struct {
	ExamId     int64  `json:"exam_id"`
	QuestionId int64  `json:"question_id"`
	Score      string `json:"score"`
	Sort       int    `json:"sort,optional"`
}

type AnswerItem struct {
	QuestionId int64  `json:"question_id"`
	Answer     string `json:"answer"`
}

type AskQuestionReq struct {
	CourseId  int64  `json:"course_id"`
	Question  string `json:"question"`
	SessionId string `json:"session_id,optional"` // 多轮对话标识；首轮不传
}

type AskQuestionRes struct {
	Answer  string   `json:"answer"`
	Sources []string `json:"sources"`
}

type AskQuestionStreamRes struct {
	Delta     string   `json:"delta"`
	Sources   []string `json:"sources,omitempty"`
	Finished  bool     `json:"finished"`
	SessionId string   `json:"session_id,omitempty"` // 首帧返回，客户端保存用于后续多轮
}

type ChapterItem struct {
	Id        int64          `json:"id"`
	CourseId  int64          `json:"course_id"`
	Title     string         `json:"title"`
	Sort      int            `json:"sort"`
	Materials []MaterialItem `json:"materials"`
}

type ChapterListReq struct {
	CourseId int64 `form:"course_id"`
}

type ChapterListRes struct {
	List []ChapterItem `json:"list"`
}

type CheckEnrollmentReq struct {
	CourseId int64 `form:"course_id"`
}

type CheckEnrollmentRes struct {
	IsEnrolled bool `json:"is_enrolled"`
}

type CourseDetailReq struct {
	Id int64 `path:"id"`
}

type CourseDetailRes struct {
	Course   CourseItem    `json:"course"`
	Chapters []ChapterItem `json:"chapters"`
}

type CourseItem struct {
	Id          int64  `json:"id"`
	Title       string `json:"title"`
	Cover       string `json:"cover"`
	Description string `json:"description"`
	TeacherId   int64  `json:"teacher_id"`
	Status      int    `json:"status"`
	CreateTime  int64  `json:"create_time"`
}

type CourseListReq struct {
	Page int `form:"page,default=1"`
	Size int `form:"size,default=10"`
}

type CourseListRes struct {
	List  []CourseItem `json:"list"`
	Total int64        `json:"total"`
}

type CourseStudentItem struct {
	UserId     int64  `json:"user_id"`
	Nickname   string `json:"nickname"`
	Avatar     string `json:"avatar"`
	Email      string `json:"email"`
	EnrollTime int64  `json:"enroll_time"`
}

type CourseStudentsReq struct {
	CourseId int64 `form:"course_id"`
	Page     int   `form:"page,default=1"`
	Size     int   `form:"size,default=10"`
}

type CourseStudentsRes struct {
	List  []CourseStudentItem `json:"list"`
	Total int64               `json:"total"`
}

type CreateChapterReq struct {
	CourseId int64  `json:"course_id"`
	Title    string `json:"title"`
	Sort     int    `json:"sort,optional"`
}

type CreateChapterRes struct {
	Id int64 `json:"id"`
}

type CreateCourseReq struct {
	Title       string `json:"title"`
	Cover       string `json:"cover"`
	Description string `json:"description"`
}

type CreateCourseRes struct {
	Id int64 `json:"id"`
}

type CreateExamReq struct {
	CourseId   int64  `json:"course_id"`
	Title      string `json:"title"`
	TotalScore string `json:"total_score"`
	PassScore  string `json:"pass_score"`
	Duration   int    `json:"duration"`
	StartTime  int64  `json:"start_time"`
	EndTime    int64  `json:"end_time"`
	ExamType   int    `json:"exam_type,options=1|2"` // 1:固定 2:随机
	RuleJson   string `json:"rule_json,optional"`    // 随机组卷规则JSON
}

type CreateExamRes struct {
	Id int64 `json:"id"`
}

type CreateMaterialReq struct {
	ChapterId int64  `json:"chapter_id"`
	Title     string `json:"title"`
	Type      int    `json:"type,options=2|3"` // 2:PDF 3:文档
	Url       string `json:"url"`
	FileHash  string `json:"file_hash"`
	FileSize  int64  `json:"file_size"`
	Sort      int    `json:"sort,optional"`
}

type CreateMaterialRes struct {
	Id int64 `json:"id"`
}

type CreateQuestionReq struct {
	CourseId        int64  `json:"course_id"`
	Type            int    `json:"type,options=1|2|3|4|5"` // 1:单选 2:多选 3:判断 4:填空 5:简答
	Content         string `json:"content"`
	Answer          string `json:"answer"`
	Analysis        string `json:"analysis,optional"`
	KnowledgePoints string `json:"knowledge_points,optional"`
	Score           string `json:"score"`
	Difficulty      int    `json:"difficulty,options=1|2|3"` // 1:简单 2:中等 3:困难
}

type CreateQuestionRes struct {
	Id int64 `json:"id"`
}

type DeleteChapterReq struct {
	Id int64 `path:"id"`
}

type DeleteCourseReq struct {
	Id int64 `path:"id"`
}

type DeleteExamReq struct {
	Id int64 `path:"id"`
}

type DeleteMaterialReq struct {
	Id int64 `path:"id"`
}

type DeleteQuestionReq struct {
	Id int64 `path:"id"`
}

type DropCourseReq struct {
	CourseId int64 `json:"course_id"`
}

type Empty struct {
}

type EnrollCourseReq struct {
	CourseId int64 `json:"course_id"`
}

type EnrollmentCourseItem struct {
	Id          int64  `json:"id"`
	Title       string `json:"title"`
	Cover       string `json:"cover"`
	Description string `json:"description"`
	TeacherId   int64  `json:"teacher_id"`
	Status      int    `json:"status"`
	EnrollTime  int64  `json:"enroll_time"`
}

type ExamDetailReq struct {
	Id int64 `path:"id"`
}

type ExamDetailRes struct {
	Exam      ExamItem           `json:"exam"`
	Questions []ExamQuestionItem `json:"questions"`
}

type ExamItem struct {
	Id         int64  `json:"id"`
	CourseId   int64  `json:"course_id"`
	Title      string `json:"title"`
	TotalScore string `json:"total_score"`
	PassScore  string `json:"pass_score"`
	Duration   int    `json:"duration"`
	StartTime  int64  `json:"start_time"`
	EndTime    int64  `json:"end_time"`
	Status     int    `json:"status"`
	ExamType   int    `json:"exam_type"` // 1:固定 2:随机
	CreateTime int64  `json:"create_time"`
}

type ExamListReq struct {
	CourseId int64 `form:"course_id"`
	Page     int   `form:"page,default=1"`
	Size     int   `form:"size,default=10"`
}

type ExamListRes struct {
	List  []ExamItem `json:"list"`
	Total int64      `json:"total"`
}

type ExamQuestionItem struct {
	QuestionId int64        `json:"question_id"`
	Score      string       `json:"score"`
	Sort       int          `json:"sort"`
	Question   QuestionItem `json:"question"`
}

type GenerateCourseOutlineReq struct {
	CourseId     int64  `json:"course_id"`
	Topic        string `json:"topic"`
	Requirements string `json:"requirements,optional"`
}

type GenerateCoursewareReq struct {
	ChapterId    int64  `json:"chapter_id"`
	Requirements string `json:"requirements"`
	SessionId    string `json:"session_id,optional"` // 多轮对话标识；首轮不传
}

type GenerateCoursewareStreamRes struct {
	Delta     string `json:"delta"`
	Finished  bool   `json:"finished"`
	SessionId string `json:"session_id,omitempty"` // 首帧返回，客户端保存用于后续多轮
}

type GenerateQuestionsReq struct {
	CourseId        int64  `json:"course_id"`
	KnowledgePoints string `json:"knowledge_points"`
	Count           int    `json:"count"`
	Type            int    `json:"type,options=1|2|3|4|5"`
	Difficulty      int    `json:"difficulty,options=1|2|3"`
}

type GenerateTaskRes struct {
	TaskId string `json:"task_id"`
}

type GetAiTaskStatusReq struct {
	TaskId string `path:"task_id"`
}

type GetAiTaskStatusRes struct {
	Status  int    `json:"status"`           // 0:生成中 1:完成 2:失败
	Result  string `json:"result,optional"`  // 成功后的结果(JSON序列化或Markdown)
	Message string `json:"message,optional"` // 失败信息
}

type GetExamResultReq struct {
	RecordId int64 `path:"record_id"`
}

type GetExamResultRes struct {
	ExamId     int64  `json:"exam_id"`
	Score      string `json:"score"`
	Status     int    `json:"status"`
	SubmitTime int64  `json:"submit_time"`
}

type GetStudyProgressReq struct {
	CourseId int64 `form:"course_id"`
}

type GetStudyProgressRes struct {
	List []StudyProgressItem `json:"list"`
}

type GetUploadTokenRes struct {
	AccessKeyId string `json:"access_key_id"`
	Policy      string `json:"policy"`
	Signature   string `json:"signature"`
	Algorithm   string `json:"algorithm"`
	Date        string `json:"date"`
	Bucket      string `json:"bucket"`
	Host        string `json:"host"`
	Dir         string `json:"dir"`
}

type GetUserAnswersReq struct {
	RecordId int64 `path:"record_id"`
}

type GetUserAnswersRes struct {
	List []UserAnswerItem `json:"list"`
}

type LoginReq struct {
	Email    string `json:"email"`
	Password string `json:"password"`
}

type LoginRes struct {
	UserId int64  `json:"user_id"`
	Token  string `json:"token"`
	Role   int    `json:"role"`
}

type MaterialItem struct {
	Id        int64  `json:"id"`
	ChapterId int64  `json:"chapter_id"`
	Title     string `json:"title"`
	Type      int    `json:"type"`
	Url       string `json:"url"`
	FileHash  string `json:"file_hash"`
	FileSize  int64  `json:"file_size"`
	AiStatus  int    `json:"ai_status"`
	Sort      int    `json:"sort"`
}

type MaterialListReq struct {
	ChapterId int64 `form:"chapter_id"`
}

type MaterialListRes struct {
	List []MaterialItem `json:"list"`
}

type MyEnrollmentListReq struct {
	Page int `form:"page,default=1"`
	Size int `form:"size,default=10"`
}

type MyEnrollmentListRes struct {
	List  []EnrollmentCourseItem `json:"list"`
	Total int64                  `json:"total"`
}

type QuestionDetailReq struct {
	Id int64 `path:"id"`
}

type QuestionDetailRes struct {
	Question QuestionItem `json:"question"`
}

type QuestionItem struct {
	Id              int64  `json:"id"`
	CourseId        int64  `json:"course_id"`
	Type            int    `json:"type"`
	Content         string `json:"content"`
	Answer          string `json:"answer"`
	Analysis        string `json:"analysis"`
	KnowledgePoints string `json:"knowledge_points"`
	Score           string `json:"score"`
	Difficulty      int    `json:"difficulty"`
	CreateTime      int64  `json:"create_time"`
}

type QuestionListReq struct {
	CourseId   int64 `form:"course_id"`
	Type       int   `form:"type,optional"`
	Difficulty int   `form:"difficulty,optional"`
	Page       int   `form:"page,default=1"`
	Size       int   `form:"size,default=10"`
}

type QuestionListRes struct {
	List  []QuestionItem `json:"list"`
	Total int64          `json:"total"`
}

type RegisterReq struct {
	Email    string `json:"email"`
	Password string `json:"password"`
	Code     string `json:"code"`
	Role     int    `json:"role,options=1|2"` // 1:学生 2:教师
}

type RegisterRes struct {
	UserId int64  `json:"user_id"`
	Token  string `json:"token"`
}

type RemoveExamQuestionReq struct {
	ExamId     int64 `json:"exam_id"`
	QuestionId int64 `json:"question_id"`
}

type SaveAnswerSnapshotReq struct {
	RecordId int64        `json:"record_id"`
	Answers  []AnswerItem `json:"answers"`
}

type SendVerifyCodeReq struct {
	Email string `json:"email"`
}

type SendVerifyCodeRes struct {
}

type StartExamReq struct {
	ExamId int64 `json:"exam_id"`
}

type StartExamRes struct {
	RecordId int64 `json:"record_id"`
}

type StudyProgressItem struct {
	MaterialId int64 `json:"material_id"`
	ChapterId  int64 `json:"chapter_id"`
	Progress   int   `json:"progress"`
}

type SubmitExamReq struct {
	RecordId int64        `json:"record_id"`
	ExamId   int64        `json:"exam_id"`
	Answers  []AnswerItem `json:"answers"`
}

type SubmitExamRes struct {
	Success bool `json:"success"`
}

type UpdateChapterReq struct {
	Id    int64  `path:"id"`
	Title string `json:"title,optional"`
	Sort  int    `json:"sort,optional"`
}

type UpdateCourseReq struct {
	Id          int64  `path:"id"`
	Title       string `json:"title,optional"`
	Cover       string `json:"cover,optional"`
	Description string `json:"description,optional"`
	Status      int    `json:"status,optional"`
}

type UpdateExamReq struct {
	Id         int64  `path:"id"`
	Title      string `json:"title,optional"`
	TotalScore string `json:"total_score,optional"`
	PassScore  string `json:"pass_score,optional"`
	Duration   int    `json:"duration,optional"`
	StartTime  int64  `json:"start_time,optional"`
	EndTime    int64  `json:"end_time,optional"`
	Status     int    `json:"status,optional"`
}

type UpdateQuestionReq struct {
	Id              int64  `path:"id"`
	Content         string `json:"content,optional"`
	Answer          string `json:"answer,optional"`
	Analysis        string `json:"analysis,optional"`
	KnowledgePoints string `json:"knowledge_points,optional"`
	Score           string `json:"score,optional"`
	Difficulty      int    `json:"difficulty,options=1|2|3,optional"`
}

type UpdateStudyProgressReq struct {
	CourseId   int64 `json:"course_id"`
	ChapterId  int64 `json:"chapter_id"`
	MaterialId int64 `json:"material_id"`
	Progress   int   `json:"progress"` // 0~100
}

type UpdateUserInfoReq struct {
	Nickname string `json:"nickname,optional"`
	Avatar   string `json:"avatar,optional"`
}

type UserAnswerItem struct {
	QuestionId int64  `json:"question_id"`
	UserAnswer string `json:"user_answer"`
	IsCorrect  int    `json:"is_correct"`
	Score      string `json:"score"`
	AiStatus   int    `json:"ai_status"`
	AiComment  string `json:"ai_comment"`
}

type UserInfoRes struct {
	UserId   int64  `json:"user_id"`
	Email    string `json:"email"`
	Nickname string `json:"nickname"`
	Avatar   string `json:"avatar"`
	Role     int    `json:"role"`
}
