// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2
// Source: exam.proto

package server

import (
	"context"

	"teaching-backend/application/exam/rpc/internal/logic"
	"teaching-backend/application/exam/rpc/internal/svc"
	"teaching-backend/application/exam/rpc/pb"
)

type ExamServer struct {
	svcCtx *svc.ServiceContext
	pb.UnimplementedExamServer
}

func NewExamServer(svcCtx *svc.ServiceContext) *ExamServer {
	return &ExamServer{
		svcCtx: svcCtx,
	}
}

// ========== 题库管理 ==========
func (s *ExamServer) CreateQuestion(ctx context.Context, in *pb.CreateQuestionReq) (*pb.CreateQuestionRes, error) {
	l := logic.NewCreateQuestionLogic(ctx, s.svcCtx)
	return l.CreateQuestion(in)
}

// 题目列表
func (s *ExamServer) QuestionList(ctx context.Context, in *pb.QuestionListReq) (*pb.QuestionListRes, error) {
	l := logic.NewQuestionListLogic(ctx, s.svcCtx)
	return l.QuestionList(in)
}

// 题目详情
func (s *ExamServer) QuestionDetail(ctx context.Context, in *pb.QuestionDetailReq) (*pb.QuestionDetailRes, error) {
	l := logic.NewQuestionDetailLogic(ctx, s.svcCtx)
	return l.QuestionDetail(in)
}

// 更新题目
func (s *ExamServer) UpdateQuestion(ctx context.Context, in *pb.UpdateQuestionReq) (*pb.UpdateQuestionRes, error) {
	l := logic.NewUpdateQuestionLogic(ctx, s.svcCtx)
	return l.UpdateQuestion(in)
}

// 删除题目
func (s *ExamServer) DeleteQuestion(ctx context.Context, in *pb.DeleteQuestionReq) (*pb.DeleteQuestionRes, error) {
	l := logic.NewDeleteQuestionLogic(ctx, s.svcCtx)
	return l.DeleteQuestion(in)
}

// ========== 试卷管理 ==========
func (s *ExamServer) CreateExam(ctx context.Context, in *pb.CreateExamReq) (*pb.CreateExamRes, error) {
	l := logic.NewCreateExamLogic(ctx, s.svcCtx)
	return l.CreateExam(in)
}

// 试卷列表
func (s *ExamServer) ExamList(ctx context.Context, in *pb.ExamListReq) (*pb.ExamListRes, error) {
	l := logic.NewExamListLogic(ctx, s.svcCtx)
	return l.ExamList(in)
}

// 试卷详情(含题目)
func (s *ExamServer) ExamDetail(ctx context.Context, in *pb.ExamDetailReq) (*pb.ExamDetailRes, error) {
	l := logic.NewExamDetailLogic(ctx, s.svcCtx)
	return l.ExamDetail(in)
}

// 更新试卷
func (s *ExamServer) UpdateExam(ctx context.Context, in *pb.UpdateExamReq) (*pb.UpdateExamRes, error) {
	l := logic.NewUpdateExamLogic(ctx, s.svcCtx)
	return l.UpdateExam(in)
}

// 删除试卷
func (s *ExamServer) DeleteExam(ctx context.Context, in *pb.DeleteExamReq) (*pb.DeleteExamRes, error) {
	l := logic.NewDeleteExamLogic(ctx, s.svcCtx)
	return l.DeleteExam(in)
}

// 给试卷添加题目
func (s *ExamServer) AddExamQuestion(ctx context.Context, in *pb.AddExamQuestionReq) (*pb.AddExamQuestionRes, error) {
	l := logic.NewAddExamQuestionLogic(ctx, s.svcCtx)
	return l.AddExamQuestion(in)
}

// 移除试卷题目
func (s *ExamServer) RemoveExamQuestion(ctx context.Context, in *pb.RemoveExamQuestionReq) (*pb.RemoveExamQuestionRes, error) {
	l := logic.NewRemoveExamQuestionLogic(ctx, s.svcCtx)
	return l.RemoveExamQuestion(in)
}

// ========== 考试作答 ==========
func (s *ExamServer) StartExam(ctx context.Context, in *pb.StartExamReq) (*pb.StartExamRes, error) {
	l := logic.NewStartExamLogic(ctx, s.svcCtx)
	return l.StartExam(in)
}

// 提交答卷
func (s *ExamServer) SubmitExam(ctx context.Context, in *pb.SubmitExamReq) (*pb.SubmitExamRes, error) {
	l := logic.NewSubmitExamLogic(ctx, s.svcCtx)
	return l.SubmitExam(in)
}

// 考试心跳与答案快照保存 (存Redis)
func (s *ExamServer) SaveAnswerSnapshot(ctx context.Context, in *pb.SaveAnswerSnapshotReq) (*pb.SaveAnswerSnapshotRes, error) {
	l := logic.NewSaveAnswerSnapshotLogic(ctx, s.svcCtx)
	return l.SaveAnswerSnapshot(in)
}

// 获取考试结果
func (s *ExamServer) GetExamResult(ctx context.Context, in *pb.GetExamResultReq) (*pb.GetExamResultRes, error) {
	l := logic.NewGetExamResultLogic(ctx, s.svcCtx)
	return l.GetExamResult(in)
}

// 获取学生答题明细
func (s *ExamServer) GetUserAnswers(ctx context.Context, in *pb.GetUserAnswersReq) (*pb.GetUserAnswersRes, error) {
	l := logic.NewGetUserAnswersLogic(ctx, s.svcCtx)
	return l.GetUserAnswers(in)
}
