// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.9.2

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	userExamRecordFieldNames          = builder.RawFieldNames(&UserExamRecord{})
	userExamRecordRows                = strings.Join(userExamRecordFieldNames, ",")
	userExamRecordRowsExpectAutoSet   = strings.Join(stringx.Remove(userExamRecordFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	userExamRecordRowsWithPlaceHolder = strings.Join(stringx.Remove(userExamRecordFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"

	cacheUserExamRecordIdPrefix           = "cache:userExamRecord:id:"
	cacheUserExamRecordExamIdUserIdPrefix = "cache:userExamRecord:examId:userId:"
)

type (
	userExamRecordModel interface {
		Insert(ctx context.Context, data *UserExamRecord) (sql.Result, error)
		FindOne(ctx context.Context, id uint64) (*UserExamRecord, error)
		FindOneByExamIdUserId(ctx context.Context, examId uint64, userId uint64) (*UserExamRecord, error)
		Update(ctx context.Context, data *UserExamRecord) error
		Delete(ctx context.Context, id uint64) error
	}

	defaultUserExamRecordModel struct {
		sqlc.CachedConn
		table string
	}

	UserExamRecord struct {
		Id         uint64       `db:"id"`          // 主键ID
		ExamId     uint64       `db:"exam_id"`     // 试卷ID
		UserId     uint64       `db:"user_id"`     // 学生ID
		Score      float64      `db:"score"`       // 最终得分
		Status     int64        `db:"status"`      // 状态 0:答题中 1:已交卷待批改 2:已批改
		SubmitTime sql.NullTime `db:"submit_time"` // 交卷时间
		CreateTime time.Time    `db:"create_time"` // 创建时间
		UpdateTime time.Time    `db:"update_time"` // 更新时间
		DeletedAt  sql.NullTime `db:"deleted_at"`  // 删除时间
	}
)

func newUserExamRecordModel(conn sqlx.SqlConn, c cache.CacheConf, opts ...cache.Option) *defaultUserExamRecordModel {
	return &defaultUserExamRecordModel{
		CachedConn: sqlc.NewConn(conn, c, opts...),
		table:      "`user_exam_record`",
	}
}

func (m *defaultUserExamRecordModel) Delete(ctx context.Context, id uint64) error {
	data, err := m.FindOne(ctx, id)
	if err != nil {
		return err
	}

	userExamRecordExamIdUserIdKey := fmt.Sprintf("%s%v:%v", cacheUserExamRecordExamIdUserIdPrefix, data.ExamId, data.UserId)
	userExamRecordIdKey := fmt.Sprintf("%s%v", cacheUserExamRecordIdPrefix, id)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
		return conn.ExecCtx(ctx, query, id)
	}, userExamRecordExamIdUserIdKey, userExamRecordIdKey)
	return err
}

func (m *defaultUserExamRecordModel) FindOne(ctx context.Context, id uint64) (*UserExamRecord, error) {
	userExamRecordIdKey := fmt.Sprintf("%s%v", cacheUserExamRecordIdPrefix, id)
	var resp UserExamRecord
	err := m.QueryRowCtx(ctx, &resp, userExamRecordIdKey, func(ctx context.Context, conn sqlx.SqlConn, v any) error {
		query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", userExamRecordRows, m.table)
		return conn.QueryRowCtx(ctx, v, query, id)
	})
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultUserExamRecordModel) FindOneByExamIdUserId(ctx context.Context, examId uint64, userId uint64) (*UserExamRecord, error) {
	userExamRecordExamIdUserIdKey := fmt.Sprintf("%s%v:%v", cacheUserExamRecordExamIdUserIdPrefix, examId, userId)
	var resp UserExamRecord
	err := m.QueryRowIndexCtx(ctx, &resp, userExamRecordExamIdUserIdKey, m.formatPrimary, func(ctx context.Context, conn sqlx.SqlConn, v any) (i any, e error) {
		query := fmt.Sprintf("select %s from %s where `exam_id` = ? and `user_id` = ? limit 1", userExamRecordRows, m.table)
		if err := conn.QueryRowCtx(ctx, &resp, query, examId, userId); err != nil {
			return nil, err
		}
		return resp.Id, nil
	}, m.queryPrimary)
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultUserExamRecordModel) Insert(ctx context.Context, data *UserExamRecord) (sql.Result, error) {
	userExamRecordExamIdUserIdKey := fmt.Sprintf("%s%v:%v", cacheUserExamRecordExamIdUserIdPrefix, data.ExamId, data.UserId)
	userExamRecordIdKey := fmt.Sprintf("%s%v", cacheUserExamRecordIdPrefix, data.Id)
	ret, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?)", m.table, userExamRecordRowsExpectAutoSet)
		return conn.ExecCtx(ctx, query, data.ExamId, data.UserId, data.Score, data.Status, data.SubmitTime, data.DeletedAt)
	}, userExamRecordExamIdUserIdKey, userExamRecordIdKey)
	return ret, err
}

func (m *defaultUserExamRecordModel) Update(ctx context.Context, newData *UserExamRecord) error {
	data, err := m.FindOne(ctx, newData.Id)
	if err != nil {
		return err
	}

	userExamRecordExamIdUserIdKey := fmt.Sprintf("%s%v:%v", cacheUserExamRecordExamIdUserIdPrefix, data.ExamId, data.UserId)
	userExamRecordIdKey := fmt.Sprintf("%s%v", cacheUserExamRecordIdPrefix, data.Id)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, userExamRecordRowsWithPlaceHolder)
		return conn.ExecCtx(ctx, query, newData.ExamId, newData.UserId, newData.Score, newData.Status, newData.SubmitTime, newData.DeletedAt, newData.Id)
	}, userExamRecordExamIdUserIdKey, userExamRecordIdKey)
	return err
}

func (m *defaultUserExamRecordModel) formatPrimary(primary any) string {
	return fmt.Sprintf("%s%v", cacheUserExamRecordIdPrefix, primary)
}

func (m *defaultUserExamRecordModel) queryPrimary(ctx context.Context, conn sqlx.SqlConn, v, primary any) error {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", userExamRecordRows, m.table)
	return conn.QueryRowCtx(ctx, v, query, primary)
}

func (m *defaultUserExamRecordModel) tableName() string {
	return m.table
}
