// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.9.2

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	userAnswerFieldNames          = builder.RawFieldNames(&UserAnswer{})
	userAnswerRows                = strings.Join(userAnswerFieldNames, ",")
	userAnswerRowsExpectAutoSet   = strings.Join(stringx.Remove(userAnswerFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	userAnswerRowsWithPlaceHolder = strings.Join(stringx.Remove(userAnswerFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"

	cacheUserAnswerIdPrefix                 = "cache:userAnswer:id:"
	cacheUserAnswerRecordIdQuestionIdPrefix = "cache:userAnswer:recordId:questionId:"
)

type (
	userAnswerModel interface {
		Insert(ctx context.Context, data *UserAnswer) (sql.Result, error)
		FindOne(ctx context.Context, id uint64) (*UserAnswer, error)
		FindOneByRecordIdQuestionId(ctx context.Context, recordId uint64, questionId uint64) (*UserAnswer, error)
		Update(ctx context.Context, data *UserAnswer) error
		Delete(ctx context.Context, id uint64) error
	}

	defaultUserAnswerModel struct {
		sqlc.CachedConn
		table string
	}

	UserAnswer struct {
		Id         uint64         `db:"id"`          // 主键ID
		RecordId   uint64         `db:"record_id"`   // 答卷记录ID
		QuestionId uint64         `db:"question_id"` // 题目ID
		UserAnswer sql.NullString `db:"user_answer"` // 用户提交的答案
		IsCorrect  int64          `db:"is_correct"`  // 是否正确 0:错 1:对 2:半对/部分得分
		Score      float64        `db:"score"`       // 此题得分
		AiStatus   int64          `db:"ai_status"`   // AI批改状态 0:未批改 1:评卷中 2:已完成
		AiComment  sql.NullString `db:"ai_comment"`  // AI评语和解析
		CreateTime time.Time      `db:"create_time"` // 创建时间
		UpdateTime time.Time      `db:"update_time"` // 更新时间
		DeletedAt  sql.NullTime   `db:"deleted_at"`  // 删除时间
	}
)

func newUserAnswerModel(conn sqlx.SqlConn, c cache.CacheConf, opts ...cache.Option) *defaultUserAnswerModel {
	return &defaultUserAnswerModel{
		CachedConn: sqlc.NewConn(conn, c, opts...),
		table:      "`user_answer`",
	}
}

func (m *defaultUserAnswerModel) Delete(ctx context.Context, id uint64) error {
	data, err := m.FindOne(ctx, id)
	if err != nil {
		return err
	}

	userAnswerIdKey := fmt.Sprintf("%s%v", cacheUserAnswerIdPrefix, id)
	userAnswerRecordIdQuestionIdKey := fmt.Sprintf("%s%v:%v", cacheUserAnswerRecordIdQuestionIdPrefix, data.RecordId, data.QuestionId)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
		return conn.ExecCtx(ctx, query, id)
	}, userAnswerIdKey, userAnswerRecordIdQuestionIdKey)
	return err
}

func (m *defaultUserAnswerModel) FindOne(ctx context.Context, id uint64) (*UserAnswer, error) {
	userAnswerIdKey := fmt.Sprintf("%s%v", cacheUserAnswerIdPrefix, id)
	var resp UserAnswer
	err := m.QueryRowCtx(ctx, &resp, userAnswerIdKey, func(ctx context.Context, conn sqlx.SqlConn, v any) error {
		query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", userAnswerRows, m.table)
		return conn.QueryRowCtx(ctx, v, query, id)
	})
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultUserAnswerModel) FindOneByRecordIdQuestionId(ctx context.Context, recordId uint64, questionId uint64) (*UserAnswer, error) {
	userAnswerRecordIdQuestionIdKey := fmt.Sprintf("%s%v:%v", cacheUserAnswerRecordIdQuestionIdPrefix, recordId, questionId)
	var resp UserAnswer
	err := m.QueryRowIndexCtx(ctx, &resp, userAnswerRecordIdQuestionIdKey, m.formatPrimary, func(ctx context.Context, conn sqlx.SqlConn, v any) (i any, e error) {
		query := fmt.Sprintf("select %s from %s where `record_id` = ? and `question_id` = ? limit 1", userAnswerRows, m.table)
		if err := conn.QueryRowCtx(ctx, &resp, query, recordId, questionId); err != nil {
			return nil, err
		}
		return resp.Id, nil
	}, m.queryPrimary)
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultUserAnswerModel) Insert(ctx context.Context, data *UserAnswer) (sql.Result, error) {
	userAnswerIdKey := fmt.Sprintf("%s%v", cacheUserAnswerIdPrefix, data.Id)
	userAnswerRecordIdQuestionIdKey := fmt.Sprintf("%s%v:%v", cacheUserAnswerRecordIdQuestionIdPrefix, data.RecordId, data.QuestionId)
	ret, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?, ?, ?)", m.table, userAnswerRowsExpectAutoSet)
		return conn.ExecCtx(ctx, query, data.RecordId, data.QuestionId, data.UserAnswer, data.IsCorrect, data.Score, data.AiStatus, data.AiComment, data.DeletedAt)
	}, userAnswerIdKey, userAnswerRecordIdQuestionIdKey)
	return ret, err
}

func (m *defaultUserAnswerModel) Update(ctx context.Context, newData *UserAnswer) error {
	data, err := m.FindOne(ctx, newData.Id)
	if err != nil {
		return err
	}

	userAnswerIdKey := fmt.Sprintf("%s%v", cacheUserAnswerIdPrefix, data.Id)
	userAnswerRecordIdQuestionIdKey := fmt.Sprintf("%s%v:%v", cacheUserAnswerRecordIdQuestionIdPrefix, data.RecordId, data.QuestionId)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, userAnswerRowsWithPlaceHolder)
		return conn.ExecCtx(ctx, query, newData.RecordId, newData.QuestionId, newData.UserAnswer, newData.IsCorrect, newData.Score, newData.AiStatus, newData.AiComment, newData.DeletedAt, newData.Id)
	}, userAnswerIdKey, userAnswerRecordIdQuestionIdKey)
	return err
}

func (m *defaultUserAnswerModel) formatPrimary(primary any) string {
	return fmt.Sprintf("%s%v", cacheUserAnswerIdPrefix, primary)
}

func (m *defaultUserAnswerModel) queryPrimary(ctx context.Context, conn sqlx.SqlConn, v, primary any) error {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", userAnswerRows, m.table)
	return conn.QueryRowCtx(ctx, v, query, primary)
}

func (m *defaultUserAnswerModel) tableName() string {
	return m.table
}
