// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2
// Source: user.proto

package user

import (
	"context"

	"teaching-backend/application/user/rpc/pb"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	FindByEmailReq = pb.FindByEmailReq
	FindByEmailRes = pb.FindByEmailRes
	FindByIdReq    = pb.FindByIdReq
	FindByIdRes    = pb.FindByIdRes
	RegisterReq    = pb.RegisterReq
	RegisterRes    = pb.RegisterRes
	UpdateUserReq  = pb.UpdateUserReq
	UpdateUserRes  = pb.UpdateUserRes

	User interface {
		// 注册
		Register(ctx context.Context, in *RegisterReq, opts ...grpc.CallOption) (*RegisterRes, error)
		// 根据ID获取用户信息
		FindById(ctx context.Context, in *FindByIdReq, opts ...grpc.CallOption) (*FindByIdRes, error)
		// 根据邮箱获取用户信息
		FindByEmail(ctx context.Context, in *FindByEmailReq, opts ...grpc.CallOption) (*FindByEmailRes, error)
		// 更新用户信息
		UpdateUser(ctx context.Context, in *UpdateUserReq, opts ...grpc.CallOption) (*UpdateUserRes, error)
	}

	defaultUser struct {
		cli zrpc.Client
	}
)

func NewUser(cli zrpc.Client) User {
	return &defaultUser{
		cli: cli,
	}
}

// 注册
func (m *defaultUser) Register(ctx context.Context, in *RegisterReq, opts ...grpc.CallOption) (*RegisterRes, error) {
	client := pb.NewUserClient(m.cli.Conn())
	return client.Register(ctx, in, opts...)
}

// 根据ID获取用户信息
func (m *defaultUser) FindById(ctx context.Context, in *FindByIdReq, opts ...grpc.CallOption) (*FindByIdRes, error) {
	client := pb.NewUserClient(m.cli.Conn())
	return client.FindById(ctx, in, opts...)
}

// 根据邮箱获取用户信息
func (m *defaultUser) FindByEmail(ctx context.Context, in *FindByEmailReq, opts ...grpc.CallOption) (*FindByEmailRes, error) {
	client := pb.NewUserClient(m.cli.Conn())
	return client.FindByEmail(ctx, in, opts...)
}

// 更新用户信息
func (m *defaultUser) UpdateUser(ctx context.Context, in *UpdateUserReq, opts ...grpc.CallOption) (*UpdateUserRes, error) {
	client := pb.NewUserClient(m.cli.Conn())
	return client.UpdateUser(ctx, in, opts...)
}
