// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2
// Source: user.proto

package user

import (
	"context"

	"teaching-backend/application/user/rpc/pb"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	FindByIdReq     = pb.FindByIdReq
	FindByIdRes     = pb.FindByIdRes
	FindByMobileReq = pb.FindByMobileReq
	FindByMobileRes = pb.FindByMobileRes
	LoginReq        = pb.LoginReq
	LoginRes        = pb.LoginRes
	RegisterReq     = pb.RegisterReq
	RegisterRes     = pb.RegisterRes

	User interface {
		// 注册
		Register(ctx context.Context, in *RegisterReq, opts ...grpc.CallOption) (*RegisterRes, error)
		// 登录
		Login(ctx context.Context, in *LoginReq, opts ...grpc.CallOption) (*LoginRes, error)
		// 根据ID获取用户信息
		FindById(ctx context.Context, in *FindByIdReq, opts ...grpc.CallOption) (*FindByIdRes, error)
		// 根据手机号获取用户信息
		FindByMobile(ctx context.Context, in *FindByMobileReq, opts ...grpc.CallOption) (*FindByMobileRes, error)
	}

	defaultUser struct {
		cli zrpc.Client
	}
)

func NewUser(cli zrpc.Client) User {
	return &defaultUser{
		cli: cli,
	}
}

// 注册
func (m *defaultUser) Register(ctx context.Context, in *RegisterReq, opts ...grpc.CallOption) (*RegisterRes, error) {
	client := pb.NewUserClient(m.cli.Conn())
	return client.Register(ctx, in, opts...)
}

// 登录
func (m *defaultUser) Login(ctx context.Context, in *LoginReq, opts ...grpc.CallOption) (*LoginRes, error) {
	client := pb.NewUserClient(m.cli.Conn())
	return client.Login(ctx, in, opts...)
}

// 根据ID获取用户信息
func (m *defaultUser) FindById(ctx context.Context, in *FindByIdReq, opts ...grpc.CallOption) (*FindByIdRes, error) {
	client := pb.NewUserClient(m.cli.Conn())
	return client.FindById(ctx, in, opts...)
}

// 根据手机号获取用户信息
func (m *defaultUser) FindByMobile(ctx context.Context, in *FindByMobileReq, opts ...grpc.CallOption) (*FindByMobileRes, error) {
	client := pb.NewUserClient(m.cli.Conn())
	return client.FindByMobile(ctx, in, opts...)
}
