// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2
// Source: user.proto

package user

import (
	"context"

	"teaching-backend/application/user/rpc/pb"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	FindByEmailReq    = pb.FindByEmailReq
	FindByEmailRes    = pb.FindByEmailRes
	FindByIdReq       = pb.FindByIdReq
	FindByIdRes       = pb.FindByIdRes
	LoginReq          = pb.LoginReq
	LoginRes          = pb.LoginRes
	RegisterReq       = pb.RegisterReq
	RegisterRes       = pb.RegisterRes
	SendVerifyCodeReq = pb.SendVerifyCodeReq
	SendVerifyCodeRes = pb.SendVerifyCodeRes

	User interface {
		// 注册
		Register(ctx context.Context, in *RegisterReq, opts ...grpc.CallOption) (*RegisterRes, error)
		// 登录
		Login(ctx context.Context, in *LoginReq, opts ...grpc.CallOption) (*LoginRes, error)
		// 根据ID获取用户信息
		FindById(ctx context.Context, in *FindByIdReq, opts ...grpc.CallOption) (*FindByIdRes, error)
		// 根据邮箱获取用户信息
		FindByEmail(ctx context.Context, in *FindByEmailReq, opts ...grpc.CallOption) (*FindByEmailRes, error)
		// 发送验证码
		SendVerifyCode(ctx context.Context, in *SendVerifyCodeReq, opts ...grpc.CallOption) (*SendVerifyCodeRes, error)
	}

	defaultUser struct {
		cli zrpc.Client
	}
)

func NewUser(cli zrpc.Client) User {
	return &defaultUser{
		cli: cli,
	}
}

// 注册
func (m *defaultUser) Register(ctx context.Context, in *RegisterReq, opts ...grpc.CallOption) (*RegisterRes, error) {
	client := pb.NewUserClient(m.cli.Conn())
	return client.Register(ctx, in, opts...)
}

// 登录
func (m *defaultUser) Login(ctx context.Context, in *LoginReq, opts ...grpc.CallOption) (*LoginRes, error) {
	client := pb.NewUserClient(m.cli.Conn())
	return client.Login(ctx, in, opts...)
}

// 根据ID获取用户信息
func (m *defaultUser) FindById(ctx context.Context, in *FindByIdReq, opts ...grpc.CallOption) (*FindByIdRes, error) {
	client := pb.NewUserClient(m.cli.Conn())
	return client.FindById(ctx, in, opts...)
}

// 根据邮箱获取用户信息
func (m *defaultUser) FindByEmail(ctx context.Context, in *FindByEmailReq, opts ...grpc.CallOption) (*FindByEmailRes, error) {
	client := pb.NewUserClient(m.cli.Conn())
	return client.FindByEmail(ctx, in, opts...)
}

// 发送验证码
func (m *defaultUser) SendVerifyCode(ctx context.Context, in *SendVerifyCodeReq, opts ...grpc.CallOption) (*SendVerifyCodeRes, error) {
	client := pb.NewUserClient(m.cli.Conn())
	return client.SendVerifyCode(ctx, in, opts...)
}
